### ISSUE TITLE
Errore su: Impostazioni novità

### ISSUE THREAD

**Issue by greko17** [Stream4me/addon#11]
Salve,
quando clicco su una delle voci nella sezione indicata per la scelta dei canali da includere, appare questo
![immagine](https://user-images.githubusercontent.com/50103632/57102153-14195c00-6d23-11e9-9f17-625647fd3647.png)

Invece dell'elenco canali.
La ver. di kodi nella foto è la 17.6 ma ho lo stesso risultato su una ver. 18 su raspberry con su libreelec

**Comment by 4l3x87** [comment]
Ciao.
Per risolvere il problema basta andare su Impostazioni > Preferenze > Filtra canale per lingua e qui inserire tutto tranne "auto", così dovrebbe funzionare.

**Comment by 4l3x87** [comment]
> Salve,
> quando clicco su una delle voci nella sezione indicata per la scelta dei canali da includere, appare questo
> ![immagine](https://user-images.githubusercontent.com/50103632/57102153-14195c00-6d23-11e9-9f17-625647fd3647.png)
> 
> Invece dell'elenco canali.
> La ver. di kodi nella foto è la 17.6 ma ho lo stesso risultato su una ver. 18 su raspberry con su libreelec

Ciao.
Per risolvere il problema basta andare su Impostazioni > Preferenze > Filtra canale per lingua e qui inserire tutto tranne "auto", così dovrebbe funzionare.

**Comment by 4l3x87** [comment]
Ciao.
Per risolvere il problema basta andare su Impostazioni > Preferenze > Filtra canale per lingua e qui inserire tutto tranne "auto", così dovrebbe funzionare.

**Comment by greko17** [comment]
Ciao,
Testato e funziona!
Grazie!

Ma è corretto che funzioni così, e allora chiudo l'issue o lascio aperto come promemoria?

**Comment by 4l3x87** [comment]
Beh... lascialo aperto, sarebbe da gestire l'impostazione auto  o rimuoverla, decideranno gli admin se chiudere l'issue, io la lascerei aperta

**Comment by Alhaziel01** [comment]
Corretto!
