### ISSUE TITLE
Download: Scaricare senza aggiungere le info

### ISSUE THREAD

**Issue by fatshotty** [Stream4me/addon#110]
Mi e' capitato di voler scaricare una puntanta di un programma televisivo.
Nel menu contestuale ho cliccato su Download. Mi compare un ulteriore menu in cui mi chiede di "completare le info", "Immettere un altro nome", "cercare su tvdb.com".

Dopo aver provato tutte e 3 le voci senza successo, il download non partiva, bensí informava di un errore di KOD (e controllare il log).
Solo dopo altri tentativi mi sono accorto che bastava fare ESC per procedere comunque al download.

Sarebbe possibile aggiungere direttamente nel menu contestuale la voce "Scarica ugualmente" al pari delle 3 voci citate prima?
In questo modo non capitera' di scoprire questa funzionalita' per caso :)

Grazie in anticipo

**Comment by mac12m99** [comment]
Ciao e grazie della segnalazione!
Quella voce dovrebbe apparire solo quando kod non è riuscito ad ottenere il nome corretto della serie/film (è la stessa che appare in aggiungi in videoteca).
In pratica però, ora come ora, spesso è dovuto a una "mancanza" del singolo canale, con la riscrittura che stiamo facendo dovrebbe accadere molto meno spesso.

Comunque in quella schermata si dovrebbe inserire manualmente il nome della serie, se non ti ha dato risultati o hai sbagliato a scriverla o non esiste su tmdb (il che è strano).
Riesci a darmi maggiori info sulla serie / canale in questione?

**Comment by fatshotty** [comment]
Grazie della risposta.
In particolare cercavo di scaricare una puntata di XFactor, da eurostreming. L'episodio S13 E5

Grazie :)

**Comment by mac12m99** [comment]
Ho provato ed ho avuto questi risultati:
-dalla lista dei server, cliccando su uno e scegliendo download, non trova risultati perchè risulta che il nome della serie è "13x05 blabla", il che è un errore del canale, tuttavia nella schermata indicata scrivendo xfactor funziona
-dalla lista delle puntate funziona senza problemi

Considerando che in futuro ci sarà una maggiore integrazione tra download e videoteca (i download appaiono in videoteca ecc..), non credo sia il caso di aggiungere il pulsante "scarica ugualmente".
Comunque questo è un problema del canale e deve essere risolto, staremo più attenti a questo tipo di problemi nella riscrittura :+1:

**Comment by fatshotty** [comment]
Grazie mille per la spiegazione :)
