### ISSUE TITLE
Problema DreamSub

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#12]
Salve, volevo segnalare il seguente problema, una volta che é stata scelta la categoria e si va nella pagina successiva appaiono tutti gli anime non le pagini seguenti della categoria.

**Comment by mac12m99** [comment]
Non riesco a riprodurre il problema, potresti essere più preciso?

**Comment by hypno99** [comment]
Il canale dreamsub, della sezione film, ha un problema, se io scelgo una qualsiasi categoria mi appare la pagina giusta con la lista degli anime, se invece vado alla pagina successiva mi appaiono tutti gli anime del sito e non gli anime della categoria che avevo scelto.

**Comment by mac12m99** [comment]
Fixato, grazie della segnalazione, la patch sarà effettiva nel prossimo aggiornamento.
