### ISSUE TITLE
Non si installa

### ISSUE THREAD

**Issue by ramesete1** [Stream4me/addon#120]
Non riesco ad installare l’addon, dopo la configurazione dei provider si blocca al 90% e non va oltre. Questo succede su due dispositivi, per uno era la prima installazione, l’altro aveva kod già installato, ho dovuto fare il reset di fabbrica e adesso non riesco più a installarlo

**Comment by mac12m99** [comment]
Ciao,
riesci a ripetere la procedura ed a mandare il log?
Così possiamo sapere cosa è successo e fixare il problema.

**Comment by ramesete1** [comment]
Non so come fare a prendere il log, ripetere la procedura non è un problema se mi insegnate a prendere il log faccio in un attimo. Comunque non da nessun messaggio di errore, però non porta a termine l’installazione, si ferma al 90%. E’ come se fosse in attesa di qualcosa che però non arriva

**Comment by mac12m99** [comment]
Per prendere il log estrai il file kodi.log dal dispositivo, ti lascio la lista dei percorsi di dove puoi trovarlo a seconda del sistema operativo:

-Windows Desktop: %APPDATA%\Kodi\kodi.log 
-Windows Store: %LOCALAPPDATA%\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\kodi.log
-Linux:$home/ nome_utente/ .kodi/temp/ kodi.log
-mac OS: /Users/user_name/Library/Application Support/Kodi/kodi.log
-Android: data | sdcard | storage/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
-iOS: /private/var/mobile/Library/Preferences/Kodi/kodi.log
-OpenELEC: /storage/.kodi/kodi.log
-OSMC: /home/osmc/.kodi/temp/kodi.log
-XBian: /home/xbian/.kodi/temp/kodi.log
-LibreELEC/OpenELEC: Enable debug logging: Settings > System > Logging > Enable debug logging
Riavvia LibreELEC
Invia il log: Settings > LibreELEC > System > Submit Log > Upload latest Kodi log
Posta l' indirizzo che ti appare.

Una volta preso allegalo qui (prima devi rifare la procedura ovviamente, così quello che succede viene registrato)

**Comment by Jorel7983** [comment]
Anche io ho lo stesso problema. Credo che ce l'abbiano TUTTI. Perché fino ad oggi a me funzionava benissimo. Da oggi non funziona più....  È un problema che riguarda proprio la repository da parte vostra, perché ho provato a disinstallare e reinstallare KODI ma solo l'addons KOD (Kodi On Demand) non funziona. Tutte gli altri miei addons funzionano perfettamente. Da oggi appena uno lo apre CONTINUA A CHIEDERE LA CONFIGURAZIONE DELLA VIDEOTECA E RIMANE A 90%. Quindi anche se installato, quando lo apri ti dice "attendere che l'installazione finisca" ma rimane l'indicatore senza avanzare mai. E si blocca persino KODI.

**Comment by ramesete1** [comment]
È esattamente quello che succede a me, comunque domattina provo a tirare giù il log e a postarlo

**Comment by Jorel7983** [comment]
Inoltre se guardo la versione, risulta:
 - 0.0.0 da KOD Team

Si vede l'addon, ma risulta come se non fosse installato. 

Spero che troviate presto la soluzione al problema della vostra repository.

GRAZIE RAGAZZI DEL TEAM KOD. 
COMUNQUE MI PIACE MOLTO QUESTO ADDON E SPERO CHE TORNI PRESTO A FUNZIONARE. PERCHÉ FINORA HO SEMPRE TROVATO IL FILM O LA SERIE TV CHE CERCAVO. GRAZIE PER IL LAVORO CHE C'È DIETRO. 👍👏🏻👏🏻👏🏻

**Comment by Jorel7983** [comment]
Ho appena trovato una soluzione temporanea.

Adesso mi indica versione 0.0.0 da KOD Team ma mi si apre e funziona.

Ho preso la vostra "zip di installazione" dal gruppo Android Aba e mi funziona.

**Comment by Jorel7983** [comment]
Quindi è un problema di KOD Repository.

La zip d'installazione nella Repository di "Android ABA" funziona. 👍
Anche se indica versione 0.0.0 KOD Team.

Lo dico solo perché stasera volevo proprio vedermi la mia serie tv preferita.
È comunque sempre la Vostra Addon 👍

**Comment by ramesete1** [comment]
Risolto anche io dalla repo di Android aba, adesso funziona anche se l’installazione sembra non terminare lo stesso. E la versione è 0.0.0

**Comment by mac12m99** [comment]
> Anche io ho lo stesso problema. Credo che ce l'abbiano TUTTI. 

Ne io ne gli altri riusciamo a riprodurlo (nel senso che non abbiamo problemi), per questo ho chiesto il log (altrimenti lo prendevo da solo)
> Perché fino ad oggi a me funzionava benissimo. Da oggi non funziona più.... 

Con "da oggi non funziona più" intendi che lo hai dovuto reinstallare per altri motivi (reinstallazione di kodi ecc..) e non riuscivi più ad installarlo, o ti dava proprio problemi ed hai deciso di reinstallarlo?

> Quindi è un problema di KOD Repository.
> 
> La zip d'installazione nella Repository di "Android ABA" funziona. 
> Anche se indica versione 0.0.0 KOD Team.

Intendi il KoD-installer presente su aba? Quello è vecchio, il "problema" della versione 0.0.0 è stato risolto (anche se a dire il vero problema non era, semplicemente kodi che non si accorgeva del cambio di versione fino al riavvio successivo)

> Risolto anche io dalla repo di Android aba, adesso funziona anche se l’installazione sembra non terminare lo stesso. E la versione è 0.0.0

Va bene, con la versione vecchia funziona, ma senza log non riusciremo a capire cosa non va.
Inoltre, sarei curioso di sapere anche su che device (e in particolare sistema operativo) avete problemi.

PS
quanto avete aspettato? DI norma dal 90% ci vogliono 2-3 secondi, ma se utilizzate un dispositivo "scarso" (passatemi il termine) potrebbe volerci di più, comunque se schiacciate su annulla la finestra dovrebbe chiudersi e permettervi di usare kodi mentre aspettate.

**Comment by Jorel7983** [comment]
Decoder: 
 - Formuler Z8  

Il dispositivo è un decoder Android di ultima generazione.

Ho reinstallato la ZIP della vostra Repository per aiutarvi con il LOG.

Da KODI non riesco a inviarvi il LOG, 
lo storage (Temp) dei Log risulta vuoto,

Così ho fotografato il LOG usando il LOG VIEWER 
ottimo della famosa App di manutenzione di Stefano.

Come ORARIO inizia a guardare da questo punto, in cui avviene la decompressione e l'estrazione della VOSTRA ZIP:
 - 2019-10-20  14:03:20.363

Dice: 
- "non sono riuscito ad estrarre il file zip"
- "file is not a zip file"

E subito dopo alle ore 14:03:20.481:
 - l'errore in rosso

Qui non riesco ad aggiungere file immagini,
 così ho salvato TUTTO il LOG dalle ore (14:03 di oggi) in cui apro la Zip,
 in rete.

Dovrebbero essere in ordine,


ECCO I LINK DELLE IMMAGINI LOG:

https://ibb.co/d54h94F
https://ibb.co/5Bxf9PD
https://ibb.co/HHR2wkq
https://ibb.co/x3YW44C


Spero che possa aiutarvi a capire il problema e così risolverlo al più presto.


P.s.:
Comunque la .zip di Android Aba è comunque aggiornata, 
o per lo meno il Codice Interno Dove L'Addon Va A Prendere I Contenuti Online, 
perché se scelgo NOVITÀ/FILM (ricerca in peliculas) mi spuntano le novità che c'erano anche prima.

**Comment by Jorel7983** [comment]
GRAZIE PER IL VOSTRO SUPPORTO.

E BUONA DOMENICA A TUTTI. 👍

**Comment by Jorel7983** [comment]
![24BA4874-AAC1-46B6-8EC6-85AE11FB63C9](https://user-images.githubusercontent.com/56774585/67159941-83bfe980-f34b-11e9-9b1f-6b5df6076959.jpeg)



Ok. 
Adesso ho capito come aggiungere files al post. 😁

Ho messo l'immagine che più serve a farvi capire il problema legato al file .ZIP
della vostra repository.

**Comment by mac12m99** [comment]
> Decoder:
> 
> * Formuler Z8
> 
> Il dispositivo è un decoder Android di ultima generazione.
> 
> Ho reinstallato la ZIP della vostra Repository per aiutarvi con il LOG.
> 
> Da KODI non riesco a inviarvi il LOG,
> lo storage (Temp) dei Log risulta vuoto,
> 
> Così ho fotografato il LOG usando il LOG VIEWER
> ottimo della famosa App di manutenzione di Stefano.
> 
> Come ORARIO inizia a guardare da questo punto, in cui avviene la decompressione e l'estrazione della VOSTRA ZIP:
> 
> * 2019-10-20  14:03:20.363
> 
> Dice:
> 
> * "non sono riuscito ad estrarre il file zip"
> * "file is not a zip file"
> 
> E subito dopo alle ore 14:03:20.481:
> 
> * l'errore in rosso
> 
> Qui non riesco ad aggiungere file immagini,
> così ho salvato TUTTO il LOG dalle ore (14:03 di oggi) in cui apro la Zip,
> in rete.
> 
> Dovrebbero essere in ordine,
> 
> ECCO I LINK DELLE IMMAGINI LOG:
> 
> https://ibb.co/d54h94F
> https://ibb.co/5Bxf9PD
> https://ibb.co/HHR2wkq
> https://ibb.co/x3YW44C
> 
> Spero che possa aiutarvi a capire il problema e così risolverlo al più presto.

Grazie! credo di aver capito il problema, ho pubblicato una versione di test sul "repo", riuscite a testarla entrambi?
Semplicemente selezionate KoD-installer-TEST.zip, il link è sempre lo stesso:
https://kodiondemand.github.io/repo/

> P.s.:
> Comunque la .zip di Android Aba è comunque aggiornata,
> o per lo meno il Codice Interno Dove L'Addon Va A Prendere I Contenuti Online,
> perché se scelgo NOVITÀ/FILM (ricerca in peliculas) mi spuntano le novità che c'erano anche prima.

L'installer si auto distrugge a lavoro finito, lasciando solo l'addon in se, che è sempre aggiornato perchè scaricato direttamente da github, è l'installer in se che non è aggiornato su aba, ma se funziona (quella versione dava problemi su windows) avete comunque l'addon aggiornato.

Edit: vi installerà la versione beta, comunque non è un problema, evito di ricaricare per modificare una riga.

**Comment by Jorel7983** [comment]
Grazie Mac,

la zip "TEST" da me si apre e funziona.

NOTA BENE:
Bisogna però RIAVVIARE KODI, 
altrimenti se cerco un contenuto nei canali risulta SENZA Link al video.
(VEDI IMMAGINE)

E ora risultano 32 Canali di ricerca (prima 29).

Ottimo lavoro. 👍

![A792617A-EE92-4055-8F32-FA24D4FE61EC](https://user-images.githubusercontent.com/56774585/67160086-6429c080-f34d-11e9-8e56-a09944deb0d1.jpeg)

**Comment by Jorel7983** [comment]
![5FC6553B-0A3C-41EA-9B3F-6E956457A4E2](https://user-images.githubusercontent.com/56774585/67160152-19f50f00-f34e-11e9-9ed9-ef37ded79dda.jpeg)

Ecco l'immagine DOPO:
 - aver installato la zip TEST
 - e RIAVVIATO Kodi.

IL RIAVVIO DI KODI È NECESSARIO. 👍

**Comment by mac12m99** [comment]
Ottimo, li ho aggiornati entrambi :+1: 
Per il riavvio e i canali "aumentati" credo sia per via della versione beta, ti sconsiglio di tenerla in quanto da considerarsi instabile perchè "in sviluppo" (va bene se vuoi sbirciare le nuove feature ma nulla più)

**Comment by Jorel7983** [comment]
Ottimo, è proprio come dici tu.

Ho rimesso la versione normale dell'installer
e NON bisogna riavviare KODI 

E quindi KOD ritorna a FUNZIONARE. 👍

GRAZIE 1000 per l'ottimo supporto ragazzi.

AMO questo addons che uso ormai da diversi mesi 
(praticamente dopo la chiusura di "streamondemand").

È UNA VIDEOTECA COME DIO COMANDA.
BRAVI DAVVERO. 👏🏻👏🏻👏🏻

Un saluto dalla Svizzera italiana.

**Comment by mac12m99** [comment]
Grazie, di nulla :)
