### ISSUE TITLE
Richiesta aggiunta AnimeSaturn.com

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#13]
Volevo richiedere, se possibile, l'aggiunta di questo canale nella sezione anime, perché é l'unico sito che permette la visione di alcuni anime tolti per copyright su altri siti di anime.

**Comment by cttynul** [comment]
Non è una priorità immediata del team di sviluppo, se qualche sviluppatore vuole cimentarsi ben venga, finiti i task principali ci dedicheremo ad ampliare la lista dei canali disponibili.
Grazie per la segnalazione e buon proseguimento con l'utilizzo di KOD!

**Comment by hypno99** [comment]
ok grazie

**Comment by hypno99** [comment]
Ho provato a farlo ma mi dice che il sito non è raggiungibile, eppure è la stessa base di animeworld.

**Comment by 4l3x87** [comment]
Ho fatto una pull request con questo canale appena gli admin la testano verrà attivato

**Comment by hypno99** [comment]
Ciao, grazie mille per il canale lo stavo testando e funziona tutto, la ricerca, le novità, la videoteca, l'autoplay, e finalmente ho ritrovato degli anime che non si trovavano da nessuna parte, io ci avevo provato ma non ci sono riuscito, devo ancora studiarmi per bene il python.

**Comment by hypno99** [comment]
Provata l'ultima versione, non funziona la sezione novità, è normale ?

**Comment by mac12m99** [comment]
Ci siamo già accorti della cosa e l'abbiamo segnalata all'autore della pull request, sistemerà quando avrà tempo, comunque mi pare di capire che tu abbia scaricato lo zip direttamente da github giusto?
In tal caso sappi che non essendo ancora rilasciata ufficialmente una nuova versione avrai si, gli ultimi fix, ma potresti incappare in problemi del genere, essendo ancora in sviluppo.

PS
Ho visto che molti giorni fa hai creato un pull request su alfa, potresti chiuderlo trattandosi di un altro add-on?

**Comment by hypno99** [comment]
ok fatto, non mi ricordavo nemmeno di averlo aperto.

**Comment by 4l3x87** [comment]
Dovrei aver sistemato i problemi segnalati, ho già effettuato la pull #36 attendo un check dagli admin.

**Comment by mac12m99** [comment]
Merge, effettuato, chiudo l'issue
