### ISSUE TITLE
CB01

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#138]
Dopo l'aggiornamento alla versione (v0.5 aea652c) e la relativa riscrittura dei canali ho notato che nel canale CB01 è comparso il menu ultimi aggiunti ma è stato rimosso il menu Ultimi Film aggiornati/Ultimi 100 Film aggiornati, è possibile ripristinarlo grazie ?

**Comment by YoNoQuise** [comment]
Ciao Timmy,
la sezione di cui parli, non è stata rimossa, ma soltanto rinominata!
All'interno del canale Cb01, l'ex 'Ultimi 100 film aggiornati', ora si chiama 'Ultimi aggiunti'!!

**Comment by xXTimmy89Xx** [comment]
sono 2 sezioni distinte purtroppo ultimi film aggiunti sono i film nuovi aggiunti sul sito mentre aggiornati comprende anche un upgrade di qualità del film ovvero magari vecchi film che prima erano cam o md come qualità ora aggiornati in hd https://cb01.life/lista-film-ultimi-100-film-aggiunti/ notare nel link le due differenti sezioni a desta e a sinistra con film completamente differenti tra di loro pertanto sarebbe comodo averle entrambe, attualmente la sezione Film e Ultimi aggiunti fanno la stessa funzione su KOD.

**Comment by YoNoQuise** [comment]
film = [
        ('HD', ['', 'menu', 'Film HD Streaming']),
        ('Generi', ['', 'menu', 'Film per Genere']),
        ('Anni', ['', 'menu', 'Film per Anno']),
        ('Ultimi aggiunti', ['/lista-film-ultimi-100-film-aggiunti/', 'newest'])
    ]
    tvshow = ['/serietv/',
        ('Per Lettera', ['/serietv/', 'menu', 'Serie-Tv per Lettera']),
        ('Per Genere', ['/serietv/', 'menu', 'Serie-Tv per Genere']),
        ('Per anno', ['/serietv/', 'menu', 'Serie-Tv per Anno']),
        ('Aggiornamento quotidiano', ['/serietv/aggiornamento-quotidiano-serie-tv/', 'newest'])

**Comment by xXTimmy89Xx** [comment]
![asd](https://user-images.githubusercontent.com/53865707/68432798-701eda80-01b5-11ea-9e3e-a96524a5e7f7.png)

**Comment by hypno99** [comment]
Aggiornamento Quotidiano Serie TV non funziona, dice Nessun Elemento disponibile.

**Comment by YoNoQuise** [comment]
Si phede, lo sappiamo!!
Timmy, si...abbiamo controllato!!

**Comment by greko17** [comment]
> Aggiornamento Quotidiano Serie TV non funziona, dice Nessun Elemento disponibile.

Phede86, 
Gentilmente, se esponi un problema diverso da quello del topic, apri un nuovo issue.
Altrimenti si accavallano i problemi e potrebbero sfuggire.

Grazie
