### ISSUE TITLE
Problema server Onlystream

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#142]
Non c'è nessun elemento, non esiste il server Onlystream che usa popcorn.

**Comment by Alhaziel01** [comment]
Sii più preciso, ho porovato un paio di film e partono.

- Indica in quale sezione e/o contenuto riscontri problemi

**Comment by hypno99** [comment]
Per esempio aprendo Watchmen.

**Comment by mac12m99** [comment]
Onlystream è stato aggiunto sulla beta da qualche giorno, tuttavia ci stiamo interrogando sull'includerlo o no, in quanto a tutti noi risulta talmente lento che spesso non riesce neanche a partire la riproduzione (da web e di conseguenza anche da kod).
Tu come ti trovi con onlystream?

**Comment by hypno99** [comment]
Non vedo il problema, è stato aggiunto GoUnlimited che è anche peggio.

**Comment by mac12m99** [comment]
Chiudo perchè alla fine è stato aggiunto
