### ISSUE TITLE
SerieTVU

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#144]
Su serieTVU qualsiasi serie tv venga aperta in qualsiasi episodio viene visualizzato il link del sito di hosting in questo caso speedvideo duplicato 4 volte, in più speedvideo sembrerebbe non funzionare su KOD,  la sezione novità non funziona ed è stata rinominata su https://www.serietvu.club/ in Aggiornamenti Settimanali

**Comment by greko17** [comment]
Ciao Timmy,
Il problema del server, speedvideo, è stato risolto.
E' stata modificata la voce in un generico "Aggiornamenti serie", per rendere i canali standardizzati con le stesse voci, + o -, non prese dai menu dei siti, in quanto ognuno dice una cosa diversa per indicare la stessa cosa...

grazie per le segnalazioni.

Se ti risulta tutto ok, puoi chiudere l'issue.

**Comment by xXTimmy89Xx** [comment]
Ho notato un problema di numerazione delle serie tv su KOD nel canale 
SerieTVU , se sul sito https://www.serietvu.club/ sono disponibili solo determinate stagioni di una serie prendiamo come esempio la se tv X-File, disponibile solo la stagione 9, 10 ,11 su KOD vengo rinumerate come stagione 1, 2, 3 
![Immagine](https://user-images.githubusercontent.com/53865707/68651371-82877400-0527-11ea-8366-2fd5c520b10c.jpg)
![screenshot003](https://user-images.githubusercontent.com/53865707/68651382-8adfaf00-0527-11ea-9746-a857df1cf231.png)
![screenshot004](https://user-images.githubusercontent.com/53865707/68651383-8adfaf00-0527-11ea-932a-bc54b092eaed.png)

**Comment by hypno99** [comment]
Io noto una velocità bassa rispetto al sito web di speedvideo.

**Comment by xXTimmy89Xx** [comment]
Fixato da @Alhaziel01 nella versione beta 7398200, grazie!
