### ISSUE TITLE
Filmpertutti

### ISSUE THREAD

**Issue by axlt2002** [Stream4me/addon#146]
Ciao,

Segnalo che l'aggiunta in libreria dei soli episodi in italiano della stagione 10 di The Walking Dead non funziona (nonostante selezioni ITA nel nuovo menu che compare quando si aggiunge alla libreria). Nota che i nomi degli episodi di questa stagione non riportano ne il tag ITA e ne il tag Sub-ITA come invece avviene per tutti gli altri e quindi vengono forse saltati.

Grazie.

**Comment by Alhaziel01** [comment]
Ciao,

Grazie per la segnalazione, il canale è stato fixato sulla beta.
Hai la possibilità di provarlo?

**Comment by axlt2002** [comment]
Ciao, grazie per il fix.

Ho scaricato la master e fatto installazione pulita, ma quando entro nel menu Channels/TV Shows mi compaiono solo "Most Popular", "Top Rated", "In progress" e "Genre" e nessun canale...dove sbaglio?

**Comment by Alhaziel01** [comment]
Se hai Kodi non in Italiano, imposta la lingua in ita o, dalle impostazioni di KoD, il filtro della lingua su ita o all

**Comment by axlt2002** [comment]
Ok, fatto!

Allora, sul sito filmpertutti, The Walking Dead ha la seguente "struttura" (le tag relative alle lingue cambiano per la stagione 10, ma non so se siano queste ad essere utilizzate per stabilire la lingua degli episodi):

Prima Stagione - ITA
Prima Stagione - SUB ITA
Seconda Stagione - ITA
Seconda Stagione - SUB ITA
...
...
Decima Stagione - Sub-ITA
Decima Stagione - ITA In HD

Questa ultima versione del canale fornisce la lista degli episodi delle prime 9 stagioni solo in italiano (tag [ITA]), mentre per la stagione 10 solo in inglese (tag [Sub-ITA]).
Mi aspetterei che venissero elencati tutti gli episodi, sia in italiano che in inglese, per poi scegliere all'aggiunta in videoteca se avere ITA, Sub-ITA o entrambe. Corretto? O comuqnue, per la stagione 10, che vengano elencati gli episodi in italiano e non in inglese.
Forse bisogna verificare nel codice dove si "battezza" un episodio in italiano oppure in inglese.

**Comment by Alhaziel01** [comment]
Ok, grazie deve essermi sfuggito qualcosa, fixo appena possibile

**Comment by Alhaziel01** [comment]
Ora dovrebbe funzionare, fammi sapere se ci sono altri problemi.

Grazie!

**Comment by axlt2002** [comment]
Confermo, tutto ok! Grazie a te!
