### ISSUE TITLE
Sezione Documentari da sistemare

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#148]
Salve, stavo vedendo che nella sezione Documentari mancano molti Canali che hanno al loro interno dei documentari, c'è per esempio MondoSerieTV o SerieTVOnline cercherò di segnalarvi i canali che hanno una categoria per i Documentari a cominciare da CB01.
 In Aggiornamento..

**Comment by mac12m99** [comment]
Ciao, per la sezione documentari intendi le novità? Perchè dalla sezione canali mondoserietv e serietvonline ci sono.
Cb01 in effetti non ha proprio la sezione su kod, anche se la si può raggiungere da "generi", provvedo ad inserire il menu.

**Comment by mac12m99** [comment]
sezione cb01 fatta: d33fdfd4bab56c019bc23ce790d5f7860b34187e e 57077045c361b1aa6cdbf40672d3855dd9a9cdca
fammi sapere se intendevi le novità, perchè tutti quelli da te elencati non mostrano novità ma solo una lista.

**Comment by hypno99** [comment]
> sezione cb01 fatta: [d33fdfd](https://github.com/kodiondemand/addon/commit/d33fdfd4bab56c019bc23ce790d5f7860b34187e) e [5707704](https://github.com/kodiondemand/addon/commit/57077045c361b1aa6cdbf40672d3855dd9a9cdca)
> fammi sapere se intendevi le novità, perchè tutti quelli da te elencati non mostrano novità ma solo una lista.

ciao, solo il genere "Documentari", le novità non servono nemmeno, poi vedo se c'è qualche altro canale.

**Comment by mac12m99** [comment]
Con genere documentari intendi il menu canali -> documentari?
![image](https://user-images.githubusercontent.com/10120390/69482395-f58fc500-0e1a-11ea-9cd4-781c3ea794b0.png)

**Comment by hypno99** [comment]
Esatto

**Comment by hypno99** [comment]
Ho individuato anche altri canali, Altadefinizione01, casacinema, cinemalibero, la casa del cinema, filmpertutti, ilgeniodellostreaming, popcornstream.
