### ISSUE TITLE
Problema con tutti i canali

### ISSUE THREAD

**Issue by LucaSilva-r** [Stream4me/addon#151]
Ho un grosso problema che sto riscontrando da qualche settimana. Quando installo KOD e cerco qualcosa la prima volta tutto funziona senza problemi. Appena riavvio kodi non funziona più nulla.
E' come se tutti i canali venissero cancellati, infatti provando una ricerca globale appare il messaggio ricerca 0/0 non dando alcun risultato. La lista dei canali appare completamente vuota e l'unico modo per ripristinarla sembra essere reinstalla KOD da zero. 

![Cattura](https://user-images.githubusercontent.com/12925730/69175818-c7ea0980-0b04-11ea-8674-e1c011262c95.PNG)

Questo comportamento sta capitando anche a miei amici e familiari. Ho provato KOD beta ma succede la stessa cosa :( 
Quale potrebbe essere il motivo?
Grazie per il vostro tempo

**Comment by YoNoQuise** [comment]
Ciao,
per risolvere questo problema, entra nell'add on 'Kod', vai su
Impostazioni > Preferenze > Generale ed imposta il filtro della lingua su 'All' dove ora hai 'Auto'!!
(Il 'Problema', è che hai Kodi impostato in inglese e, con il filtro della lingua impostato su 'Auto', l'add on Kod, effettua la ricerca dei contenuti nella stessa lingua del tuo Kodi! Impostando il filtro della lingua su 'All', Kod effettua la ricerca dei contenuti in tutte le lingue, quindi torni a vedere i risultati ITA e SUB ITA!)

**Comment by LucaSilva-r** [comment]
OH era l'unica cosa che non avevo provato. Ora funziona tutto (a parte i download). Grazie mille!

**Comment by YoNoQuise** [comment]
OH sono contenta che tu abbia risolto! Con il Download, che problemi hai?
Per attivarlo devi entrare nell'add on Kod, poi, Impostazioni > Preferenze > Download e lo attivi!
Torni indietro, Kod > Downloads > Configurazione downloads > Scelta del server/Qualità preferita ed imposti 'Qualità più alta', premi 'Ok' e dovrebbe essere tutto a posto!
I file scaricati li trovi nella cartella dell'add on:

Da Pc:
C:\Users\TUO NOME\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.kod\downloads 

Da Android:
data | sdcard | storage/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.kod/downloads

In entrambi i casi, devi abilitare l'opzione 'Visualizza i file nascosti' sui tuoi dispositivi, per poter visualizzare la cartella!
T'informo, però, che per quanto riguarda il download, su alcune versioni di Android, potresti riscontrare problemi a causa di un bug di Kodi che è presente dalla versione 18 in poi e che non è ancora stato sistemato! 

Se può aiutarti, ne parlavano qui:
https://github.com/kodiondemand/addon/issues/33
