### ISSUE TITLE
Ricerca globale

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#154]
Dopo le ultime modifiche effettuate alla ricerca globale nella versione Beta alcune ricerche non vengono portate a termine e viene visualizzato il seguente errore 
![screenshot000](https://user-images.githubusercontent.com/53865707/69540007-f4c77200-0f85-11ea-9f09-7135af74c5b1.png)
Allego:
[kodi.log](https://github.com/kodiondemand/addon/files/3886533/kodi.log)

**Comment by mac12m99** [comment]
@Timmy89ITA Ciao, grazie delle segnalazione!
Potresti indicare anche che cosa hai cercato?

**Comment by xXTimmy89Xx** [comment]
Ho effettuato la ricerca sia da ricerca globale che dalla sezione ora in tv dei film Scarface, Resident evil, Pirati dei Caraibi ai confini del modo e tutti è 3 mi hanno generato un errore a fine ricerca.

Allego file log aggiornato:
[kodi.log](https://github.com/kodiondemand/addon/files/3886585/kodi.log)

**Comment by mac12m99** [comment]
dovrebbe essere risolto con effafdbf2c84d446d147b8bac5a6386d02da0e53
Riavvia e fammi sapere :)

**Comment by xXTimmy89Xx** [comment]
> dovrebbe essere risolto con [effafdb](https://github.com/kodiondemand/addon/commit/effafdbf2c84d446d147b8bac5a6386d02da0e53)
> Riavvia e fammi sapere :)

Confermo, ora funziona correttamente grazie!
