### ISSUE TITLE
Problema Ricerca Globale

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#155]
Facendo una ricerca globale, ci mette tantissimo tempo tanto da renderla inutilizzabile, ho provato su Android ma credo che il problema si presenta anche su Windows, allego foto e vedo se riesco a inserire il log.
![Screenshot_2019-12-01-10-47-21-035_org xbmc kodi](https://user-images.githubusercontent.com/24419707/69912350-7c9af980-1428-11ea-8442-1dc325c7e709.jpg)

**Comment by mac12m99** [comment]
Ciao, il problema dovrebbe essere risolto con la 0.5.2
Se così non fosse, riapri l'issue :)
