### ISSUE TITLE
Vista predefinita

### ISSUE THREAD

**Issue by Reddiiiee** [Stream4me/addon#156]
Innanzitutto grazie per questo fantastico addon. Volevo chiedere se è possibile impostare la vista "scorrimento" come predefinita nella videoteca, altrimenti va fatto manualmente per ogni stagione e ogni episodio.
Continuate cosi! Grazie in anticipo

**Comment by mac12m99** [comment]
Ciao! Forzare la vista è possibile attraverso questa opzione:
![image](https://user-images.githubusercontent.com/10120390/70655303-4c3d3180-1c58-11ea-8438-d8c0ecfcf03d.png)

Ma purtroppo la cosa non è configurabile (e dipende anche dalla skin che usi), in futuro vedremo di migliorarla, ma al momento questo è il massimo che si può fare.
Ricordo che modificando i file della skin era possibile forzare un tipo di vista, ma adesso non saprei dove andare a pescare una guida (ne ricordo bene come si faceva).

**Comment by Reddiiiee** [comment]
Grazie, ho provato ma con quell'opzione abilitata forza la modalità lista... 
Per cambiarla c'è un file in /usr/share/kodi/add-ons/skin.estuary/xml/ chiamato MyVideoNav.xml ma neanche modificando quello cambia qualcosa purtroppo. Su Windows non so dove si trovi, credo a partire dalla cartella "appdata"!
Grazie lo stesso per la risposta ;)
