### ISSUE TITLE
altadefinizioneclick

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#158]
Dopo l'ultimo aggiornamento della versione beta di kod build 6a22678 altadefinizioneclick e altri canali generano il seguente errore quando si prova a cercare un film nel canale stesso 
 
![screenshot000](https://user-images.githubusercontent.com/53865707/71490019-f906d980-2828-11ea-8c2e-ee6508edda72.png)

Allego file log 

[kodi.log](https://github.com/kodiondemand/addon/files/4003432/kodi.log)

**Comment by Alhaziel01** [comment]
Siamo consapevoli di questi problemi, stiamo riscrivendo la parte riguardante i dns.

**Comment by xXTimmy89Xx** [comment]
Il problema sembra essere stato risolto, Chiudo.
