### ISSUE TITLE
Implementazione server goUnlimited.to

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#16]
Anche questo server, come verystrem, è sempre più diffuso

**Comment by mac12m99** [comment]
Potresti indicare quali canali ne fanno uso?
Così valutiamo se e con quale priorità lo implementeremo.

**Comment by hypno99** [comment]
fastsubita, serietvsubita per ora

**Comment by 4l3x87** [comment]
Il server era già presente è stato fixato la regex per il recupero dei link, dovrebbe funzionare adesso

**Comment by hypno99** [comment]
Si ho provato e funziona, è lento il buffering ma dipende da loro, si può chiudere.
