### ISSUE TITLE
Ricerca nella sezione Adesso in Onda

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#161]
Nella versione Beta di KOD quando si prova a selezionare un qualsiasi film nella sezione oggi in tv o adesso in onda appena parte la ricerca del relativo film selezionato si riceve il seguente errore e la ricerca non viene portata a termine, in più a volte le locandine dei film non vengono caricate nella sezione oggi in tv.

![screenshot000](https://user-images.githubusercontent.com/53865707/71553935-07ffae80-2a18-11ea-975c-d3ab1497118b.png)
![screenshot001](https://user-images.githubusercontent.com/53865707/71553943-35e4f300-2a18-11ea-8ad0-be5a5f66c51b.png)

Allego file log

[kodi.log](https://github.com/kodiondemand/addon/files/4007877/kodi.log)

il problema della ricerca sembra non presentarsi sulla versione stabile mentre quello delle locandine dei film si.

**Comment by mac12m99** [comment]
Ciao, grazie del report!
Ora dovrebbe essere risolto, se così non fosse, riapri l'issue.
