### ISSUE TITLE
Altadefinizione.click, Guardaserie.click, LaCasaDelCinema e Tantifilm

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#163]
Nella versione beta di kod su android qualsiasi sezione nei canali Altadefinizione.click, Guardaserie.click, LaCasaDelCinema e Tantifilm restituiscono l'errore nessun elemento da visualizare.

**Comment by guanoapes77** [comment]
@Timmy89ITA Guardaserie è down

**Comment by mac12m99** [comment]
con gli ultimi commit Altadefinizione.click e Tantifilm dovrebbero essere ok, LaCasaDelCinema e Guardaserie.click non sono visibili su android causa [cloudflare](https://www.cloudflare.com/it-it/ddos/) (su altri OS è possibile aggirare la protezione, non mi addentro nei dettagli).

Grazie della segnalazione!
