### ISSUE TITLE
Domanda: KOD funziona con Kodi 19 (Python 3)?

### ISSUE THREAD

**Issue by iz8mbw** [Stream4me/addon#164]
Ciao!
Eseguo KOD su Android su Kodi 19 nightly del 12 ottobre 2019 che è l'ultima Kodi 19 nightly che supporta Python 2.
A partire dalle nightly successive, Kodi 19 supporta solo Python 3 (https://github.com/xbmc/xbmc/pull/16116).
Domanda, se aggiorno Kodi 19 ad una più recente nightly che supporta Python 3, KOD funziona ancora?
Grazie!

**Comment by Alhaziel01** [comment]
No, py3 non è ancora supportato

**Comment by iz8mbw** [comment]
Grazie.
Avete in programma di supportare anche py3?
Se puoi, magari specifica nel "README.md" che al momento KOD è supportato solo fino alla versione Kodi 18.
Grazie.

**Comment by Alhaziel01** [comment]
Si, ma il lavoro non è poco.

**Comment by iz8mbw** [comment]
Immagino....
Per il momento chiudo la Issue. Ciao!
