### ISSUE TITLE
Problemi DreamSub e Animepertutti

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#168]
Il canale DreamSub non funziona in ogni sua parte, mentre AnimePerTutti non ha nessun server funzionante.
![Screenshot_2020-01-12-10-32-35-036_org xbmc kodi](https://user-images.githubusercontent.com/24419707/72216904-7e77d280-3527-11ea-8a4e-4d773691ebee.jpg)
![Screenshot_2020-01-12-10-31-52-518_org xbmc kodi](https://user-images.githubusercontent.com/24419707/72216905-7e77d280-3527-11ea-856d-5187f785837f.jpg)

[kodi.log](https://github.com/kodiondemand/addon/files/4050468/kodi.log)

**Comment by Alhaziel01** [comment]
Ne siamo al corrente, appena possibile aggiorneremo i canali

**Comment by hypno99** [comment]
Lo sapevo l'ho aperto per facilitarvi con la mole di lavoro.

**Comment by Alhaziel01** [comment]
Puoi controllare sulla beta se è tutto ok?

**Comment by hypno99** [comment]
Provati, non va nessuno dei due.☹️

**Comment by hypno99** [comment]
Anche il nuovo Animeunity non va..

**Comment by hypno99** [comment]
Com l'ultimo aggiornamento Animeunity funziona mentre DreamSub non ancora. 
[kodi.log](https://github.com/kodiondemand/addon/files/4082490/kodi.log)

**Comment by Alhaziel01** [comment]
@phede86 Nel commit c'è scritto:

Fix Animeunity e Dreamsub:
N.B. se Dreamsub non funziona cancellare le 2 righe:
quality e servers relative a dreamsub nel file
addon_data/plugin.video.kod/settings_channels/autoplay_data.json

Hai fatto quanto indicato?

**Comment by hypno99** [comment]
Non ho kodi su PC.

**Comment by Alhaziel01** [comment]
@phede86 cancella il file autoplay_data.json

**Comment by hypno99** [comment]
Ok ora nella versione stabile, DreamSub funziona, mentre AnimePerTutti dice nessun elemento da visualizzare.
