### ISSUE TITLE
Problema Episodio Successivo nella Beta

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#169]
Ho provato questa funzione ma non va, ho installato Kod beta attivato la funzione e aggiunto la serie in questo caso Viking da CB01, ho aperto la prima puntata della prima stagione, scegliendo Wstream a 480p, verso la fine é comparsa la notifica, terminato l'episodio si é bloccato.

**Comment by Alhaziel01** [comment]
Riprova, dovrebbe funzionare

**Comment by hypno99** [comment]
Provato ma non dovrebbe essere automatico?

**Comment by Alhaziel01** [comment]
@phede86 devi attivare autoplay per far partire gli episodi in automatico

**Comment by hypno99** [comment]
Perfetto✌️
