### ISSUE TITLE
problemi su tvOS con jailbreak 13.3

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Stream4me/addon#170]
se vi da problemi qui -->
```
ICE: Risultato nel try: <Response [200]>
18:32:38.350 T:6196981760  NOTICE: check_Dns risultato: [{'url': 'https://casacinema.space', 'isRedirect': False, 'code': 503, 'rdrcturl': 'https://casacinema.space', 'history': []}, {'url': 'https://documentari-streaming-da.com', 'isRedirect': False, 'code': 200, 'rdrcturl': 'https://documentari-streaming-da.com', 'history': []}]
18:32:38.350 T:6196981760  NOTICE: check_Dns rslt: 503
18:32:38.350 T:6196981760  NOTICE: check_Dns rslt: 200
18:32:38.436 T:6174552064    INFO: Python script stopped
18:32:38.437 T:6174552064   DEBUG: Thread LanguageInvoker 6174552064 terminating
18:32:39.178 T:6168817664   DEBUG: GetImageHash - unable to stat url /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/fanart1.jpg
18:32:39.606 T:6171111424   DEBUG: RunScriptWithParams - calling plugin Kodi on Demand('plugin://plugin.video.kod/','-1','?ewogICAgImFjdGlvbiI6ICJzZXR0aW5ncyIsIAogICAgImNhdGVnb3J5IjogIkltcG9zdGF6aW9uaSIsIAogICAgImNoYW5uZWwiOiAic2V0dGluZyIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJmb2xkZXIiOiBmYWxzZSwgCiAgICAiaW5mb0xhYmVscyI6IHt9LCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvdGhlbWVzL2RlZmF1bHQvdGh1bWJfc2V0dGluZ18wLnBuZyIsIAogICAgInRpdGxlIjogIlByZWZlcmVuemUiLCAKICAgICJ0b3RhbEl0ZW1zIjogMAp9')
18:32:39.608 T:6172831744   DEBUG: Thread LanguageInvoker start, auto delete: false
18:32:39.608 T:6172831744    INFO: initializing python engine.
18:32:39.608 T:6172831744   DEBUG: CPythonInvoker(10, /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/default.py): start processing
18:32:39.650 T:6172831744   DEBUG: -->Python Interpreter Initialized<--
18:32:39.651 T:6172831744   DEBUG: CPythonInvoker(10, /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/default.py): the source file to load is "/var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/default.py"
18:32:39.651 T:6172831744   DEBUG: CPythonInvoker(10, /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/default.py): setting the Python path to /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod:/Applications/Kodi.app/Frameworks/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg:/Applications/Kodi.app/Frameworks/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-macosx-10.4-x86_64.egg:/Applications/Kodi.app/Frameworks:/Applications/Kodi.app/Frameworks/lib/python27.zip:/Applications/Kodi.app/Frameworks/lib/python2.7:/Applications/Kodi.app/Frameworks/lib/python2.7/plat-darwin:/Applications/Kodi.app/Frameworks/lib/python2.7/plat-mac:/Applications/Kodi.app/Frameworks/lib/python2.7/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Frameworks/lib/python2.7/lib-tk:/Applications/Kodi.app/Frameworks/lib/python2.7/lib-old:/Applications/Kodi.app/Frameworks/lib/python2.7/lib-dynload:/Applications/Kodi.app/Frameworks/lib/python2.7/site-packages
18:32:39.651 T:6172831744   DEBUG: CPythonInvoker(10, /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/default.py): entering source directory /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod
18:32:39.651 T:6172831744   DEBUG: CPythonInvoker(10, /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/default.py): instantiating addon using automatically obtained id of "plugin.video.kod" dependent on version 2.1.0 of the xbmc.python api
18:32:40.007 T:6172831744   ERROR: ######## ERROR #########
```

io ho risolto disabilitando l'override DNS che su tvos non lo bypassa nemmeno con jailbreak... al momento funziona

**Comment by SiNaPsEr0x** [comment]
per il resto rimane il problema qui  nell'apertura delle preferenze-- >

`:6166589440   ERROR: ######## ERROR #########
18:43:53.056 T:6166589440   ERROR:     [kod.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/platformcode/launcher.py", line 295, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/specials/setting.py", line 296, in settings
                                                config.open_settings()
                                              File "/var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/platformcode/config.py", line 170, in open_settings
                                                settings_pre = get_all_settings_addon()
                                              File "/var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/platformcode/config.py", line 156, in get_all_settings_addon
                                                infile = open(os.path.join(get_data_path(), "settings.xml"), "r")
                                            IOError: [Errno 2] No such file or directory: '/var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/userdata/addon_data/plugin.video.kod/settings.xml'
18:43:53.061 T:6171176960   DEBUG: ------ Window Init (DialogConfirm.xml) ------
18:43:53.061 T:6171176960    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
18:43:53.071 T:6171176960   DEBUG: Load DialogConfirm.xml: 10.28ms
18:43:53.073 T:6171176960   DEBUG: Alloc resources: 11.72ms  (10.53 ms skin load)
18:43:53.284 T:6175764480   DEBUG: [script.logviewer] Starting http server runner
18:43:53.289 T:6193377280   DEBUG: [script.logviewer] Server started at port 8080
18:43:53.289 T:6193377280   DEBUG: [script.logviewer] Local IP: 192.168.1.8
18:43:54.798 T:6171176960   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
18:43:54.809 T:6166589440    INFO: CPythonInvoker(6, /var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/addons/plugin.video.kod/default.py): script successfully run
18:43:54.862 T:6166589440    INFO: Python script stopped
18:43:54.862 T:6166589440   DEBUG: Thread LanguageInvoker 6166589440 terminating
`

**Comment by mac12m99** [comment]
Ciao, per quanto riguarda le impostazioni, pare che non trovi il relativo file, puoi controllare se questo percorso è corretto?
/var/mobile/Containers/Data/Application/B0E9CA67-1EEA-4018-8B99-45542174AA0C/Library/Caches/home/userdata/addon_data/plugin.video.kod/settings.xml

Per il resto, non hai specificato che problemi ti dà e non hai postato il log per intero (o la parte "interessante"), quindi non so aiutarti.
Specifica meglio e posta il log completo, così possiamo capire che cosa succede

**Comment by SiNaPsEr0x** [comment]
Allora il plugin funziona perfetto dopo aver disabilitato l override che su tvOS crea problemi... per il resto nn apre semplicemente le impostazioni da dentro il menu.... poi verifico il file e ti saprò dire... giusto se può servirvi un feedback da tvOS vi posso mandare il log completo

**Comment by mac12m99** [comment]
Si grazie, avere il log completo con l'override abilitato può aiutarci a capire perché su tvos non funziona, e magari sistemare.
Per le impostazioni, credo sia dovuto al percorso sbagliato o a qualche limitazione sui permessi di scrittura.

**Comment by SiNaPsEr0x** [comment]
[kodi.log](https://github.com/kodiondemand/addon/files/4066374/kodi.log)
se posso essere utile in altro fammi sapere

**Comment by mac12m99** [comment]
Ciao,
il problema sussiste ancora?
