### ISSUE TITLE
Autoplay CB01

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#177]
Nella versione Beta di Kod nel canale CB01 con autoplay attivo spesso e volentieri con vari film si riceve il seguente errore.

![screenshot000](https://user-images.githubusercontent.com/53865707/72979769-57e45200-3dd9-11ea-9b72-a2f2e57d8aad.png)

Allego file log

[kodi.log](https://github.com/kodiondemand/addon/files/4102753/kodi.log)

**Comment by mac12m99** [comment]
Ciao, potresti abilitare il logging di debug dalle impostazioni di KoD, riprovare e rimandare il log? (da molte più info)

Controlla anche se i seguenti percorsi portino effettivamente a dei file, per favore:
C:\Users\Timmy89\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.kod\settings_channels\autoplay_data.json e cineblog01_data.json

**Comment by xXTimmy89Xx** [comment]
https://paste.kodi.tv/zijesaliwa

![screenshot000](https://user-images.githubusercontent.com/53865707/73051808-deee0480-3e83-11ea-913f-031308247cb1.png)

**Comment by xXTimmy89Xx** [comment]
Chiedo scusa e chiudo, il problema era dovuto dal sito di hosting akvideo che da come errore:

![Cattura](https://user-images.githubusercontent.com/53865707/73054266-4909a800-3e8a-11ea-81e0-0d72c5307c54.JPG)
 Video encoding error.
