### ISSUE TITLE
altadefinizione.click

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#178]
@mac12m99 Qualsiasi sezione di altadefinizione.click da come risultato nessun elemento da visualizzare il problema persiste nonostante il commit 01545db.

**Comment by xXTimmy89Xx** [comment]
https://paste.kodi.tv/afonodavip

**Comment by mac12m99** [comment]
Il problema consiste nel fatto che https://altadefinizione-nuovo.link, dal quale viene prelevato l'url aggiornato, è sotto la protezione di [Cloudflare anti-Dos](https://www.cloudflare.com/it-it/ddos/)
Per arrivare al sito è necessario fingere di essere un utente reale che ci accede via browser, per far ciò utilizziamo una libreria apposita, tuttavia, in alcuni casi cloudflare mostra dei recaptcha o impedisce proprio l'accesso, e per questo non possiamo farci molto.

Nel tuo caso in particolare ciò che blocca KoD è un re-captcha 
Response code: Cloudflare reCaptcha detected

Siccome non sappiamo i parametri per i quali CF diventa "sospettoso" è difficile debuggare, ti posso solo dire che se usi proxy/vpn è alquanto probabile che escano (tante richieste dal medesimo indirizzo IP potrebbero essere viste come un attacco).
Come soluzione temporanea puoi inserire manualmente il link: recati in .kodi/userdata/addon_data/plugin.video.kod/settings_channels/altadefinizioneclick_data.json
e inserisci la chiave URL

{
    "settings": {
        "checklinks": false, 
        "checklinks_number": 2, 
        "include_in_global_search": true, 
        "include_in_newest_peliculas": true
    }, 
    "url": "https://altadefinizione.style/"
}

Dovrebbe funzionare finchè non cambieranno nuovamente il dominio.

**Comment by xXTimmy89Xx** [comment]
@mac12m99 Prima di tutto volevo ringraziarti per il supporto, ho effettuato dei test sia su pc che su android, premetto che non uso alcun tipo di vpn o proxy, la cosa strana però è che su pc ho risolto disabilitando la funzione override dns e usando i dns di google mentre su android purtroppo il problema persiste nonostante io abbia fatto le medesime procedure e ho dovuto modificare il file come da te consigliatomi.
