### ISSUE TITLE
Animepertutti, la casa del cinema, Mondoserietv,Piratestreaming, seriehd, streamtime, vedoHD

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#188]
Tutti i canali elencati sopra danno l'errore nessun elemento da visualizzare nella versione stabile di kod all'apertura del canale stesso o dopo aver selezionato la serie interessata.

Allego file log.

[kodi.log](https://github.com/kodiondemand/addon/files/4174576/kodi.log)

**Comment by mac12m99** [comment]
Ciao, ho verificato i problemi segnalati:
- animepertutti: non trovo niente nel log ma credo dipenda dal fatto che utilizzano quali solo netutv come server (che effettivamente non funziona, sistemeremo)
- la casa del cinema: cambio di struttura, provvederemo
- mondoserietv / piratestreaming: verificato, a volte va e a volte no, ho problemi di timeout anche da browser, credo abbiano problemi loro.. 
- streamtime: https://t.me/StreamTime/1310 alcuni vanno, altri no, problemi loro
- vedoHD: accedendo da browser tutti i link puntano a cb01, il che significa che hanno deciso di dismetterlo, lo elimineremo

**Comment by xXTimmy89Xx** [comment]
Dimenticavo VVVVID nella sezione film o serie tv una volta selezionato il film o episodio della serie da l'errore: Errore inaspettato sul canale 

https://paste.kodi.tv/pumuyimola

**Comment by mac12m99** [comment]
ok, grazie della segnalazione

Con l'ultimo aggiornamento della beta la casa del cinema dovrebbe essere ok (e vedohd è stato tolto)

**Comment by xXTimmy89Xx** [comment]
@mac12m99 Il fix di Altadefinizione.click funziona perfettamente su pc mentre nella versione android purtroppo una volta selezionato il film desiderato ci mette davvero tantissimo tempo a caricare la schermata con la selezione dei siti di hosting video

**Comment by xXTimmy89Xx** [comment]
Fixato con ec0aaf7 il problema di android
