### ISSUE TITLE
Opzione Autoplay solo per la Videoteca

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#189]
Salve, sarebbe molto comodo avere un'opzione di Autoplay solo per le Serie aggiunte nella Videoteca, io la propongo con la speranza che sia fattibile.

**Comment by mac12m99** [comment]
Ciao,
mi spiace ma alla fine non l'abbiamo reputata un'opzione che potrebbe interessare a molti, grazie comunque del consiglio.
