### ISSUE TITLE
Guardaserie.click (cloudflare su android)

### ISSUE THREAD

**Issue by ghost** [Stream4me/addon#193]
Se provo a eseguire qualsiasi azione nel canale esce "errore di kod. Controllare il log". Già elle version precedenti il canale non compariva nella ricerca globale sebbene il sito (guardaserie.movie) funzioni
[kodi.log](https://github.com/kodiondemand/addon/files/4255240/kodi.log)

**Comment by mac12m99** [comment]
Ciao,
il log non contiene nessuna info (non hai abilitato il debug dalle impostazioni), comunque dalla 0.8 è possibile estrarlo più facilmente andando in aiuto -> segnala un problema

**Comment by ghost** [comment]
http://dpaste.com/115RZQT.txt

**Comment by mac12m99** [comment]
Trattasi di un problema legato alla versione di openssl inserita su kodi per android, che è vecchia e non più supportata da cloudflare (e quindi tutti i siti che ne fanno uso, tra cui guardaserie).
Siamo a conoscenza di ciò da un po' ma non abbiamo ancora trovato soluzioni fattibili...
Ti aggiorniamo appena sappiamo qualcosa, lascio aperto l'issue così rimane in bella vista

**Comment by ghost** [comment]
Grazie per la risposta. È un problema di kodi per android o di kodi in generale? Ricevo lo stesso errore anche da pc

**Comment by mac12m99** [comment]
Guardaserie non sembra usare più cloudflare anti DOS, pertanto sembra funzionare pure su android, non so se è una cosa temporanea...
Fammi sapere se ora va
