### ISSUE TITLE
TantiFilm

### ISSUE THREAD

**Issue by 32Dexter** [Stream4me/addon#194]
Buongiorno a tutti,
Il canale tantiFilm non funziona, qualaisi funzione non ha alcun esito se non riportare il problema nel log. Bisognerebbe controllarlo. Purtroppo al momento non riesco ad allegare il file di Log...
Grazie Mille

**Comment by mac12m99** [comment]
Ciao,
io riscontro problemi solo con la sezione anime, tutte le altre vanno senza problemi.
Per favore prova le sezioni film/serie e nel caso non vadano manda il log

**Comment by mac12m99** [comment]
Sono stati fatti alcuni fix, se il problema persiste riapri pure e descrivi in quali contenuti.
