### ISSUE TITLE
Server mancanti e problema Canale 

### ISSUE THREAD

**Issue by Plut09** [Stream4me/addon#195]
Ciao ragazzi, ho notato che alcuni server non sono presenti in Altadefinizione su kod mentre da broswer si, nello specifico è presente solo supervideo per l'addon mentre da sito mixdrop, supervideo, vidoload, vidoza, gounlimited

Altro caso sull'altro canale Altadefinizione, supervideo carica ma dopo un po crasha.
Buon lavoro 👍

**Comment by mac12m99** [comment]
Ciao, ti riferisci ad altadefinizione01 (https://altadefinizione01.photo), altadefinizioneclick (https://altadefinizione.style) o  altadefinizione01L (https://altadefinizione01.kim -> offline nel momento in cui scrivo) ?

Io banalmente ho provato il primo risultato dei primi 2 ed i server ci sono tutti (i supportati), per favore indica anche quali film.

**Comment by mac12m99** [comment]
nessuna risposta, chiudo.
