### ISSUE TITLE
Wstream ReCaptcha

### ISSUE THREAD

**Issue by matteoVolante95** [Stream4me/addon#200]
Ogni volta che si prova a vedere un video su WStream appare un messaggio di errore di Verifica ReCAPTCHA fallita e invita ad aprire una finestra browser che dice che sto usando un VPN e che devo chiudere la pagina (Premetto: non uso un VPN) . 
Potete risolvere?
Grazie in anticipo

**Comment by Alhaziel01** [comment]
@matteoVolante95

Sei un po' troppo generico, su che canale capita?

**Comment by matteoVolante95** [comment]
Capita un po' su tutti i canali, WStream da sempre errore  CAPTCHA! In particolare sto provando a collegarmi dal canale Toonitalia

**Comment by mac12m99** [comment]
Vai in aiuto - segnala un problema e segui le istruzioni

Comunque se neanche dal browser va, su kod non ci possiamo fare molto..

**Comment by mac12m99** [comment]
Chiuso per mancata risposta
