### ISSUE TITLE
Rimozione dalla vostra piattaforma di due miei siti web.

### ISSUE THREAD

**Issue by AnimeWorldtv** [Stream4me/addon#201]
Buongiorno, mi sono accorto che sulla vostra piattaforma ci sono due dei miei siti web di streaming, ovvero AnimeWorld e AnimeSaturn, potreste gentilmente rimuovere il supporto a questi due siti web? Onestamente non mi piace l'idea di averli in questa piattaforma, visto che ci perdo solamente. 
Con kodi tutta la pubblicità viene bloccata e quindi ci rimetto io. Spero mi rispondiate in modo positivo.

**Comment by phede86** [comment]
Ma stai zitto che fai lo stesso con gli anime e i manga.

**Comment by Alhaziel01** [comment]
Buongiorno, riteniamo alquanto ipocrita una richiesta di questo genere da parte di un gestore di un sito che causa un mancato guadagno sia ai produttori di anime che ai traduttori (citiamo ad esempio OPF italia)
(e che, oltre alla pubblicità chiede pure donazioni)

Non so quanto ti costi tenerli aperti, tuttavia vediamo siti con molta meno pubblicità o che si basano solo e soltanto sulle donazioni, mi viene quindi difficile pensare che dietro non ci sia scopo di lucro.

Mi spiace ma respingiamo la richiesta.
