### ISSUE TITLE
problems with ADSL alert

### ISSUE THREAD

**Issue by Githeo** [Stream4me/addon#202]
Ciao,

a partire da ieri, quando apro KOD, un pop up di alert parla di un problema di ADSL:
Dear use, you seem to have problems with ADSL, [...] check the modem is connected [...]
DNS = [127.0.0.1]

Il risultato è che KoD non riesce a trovare alcunché, né nei recenti, né nella ricerca globale.
Da notare che la connessione funziona e non ho cambiato niente a livello di rete.

Come configurazione, ho la versione di KoD 0.8.1 su OSMC 2020.03-1 su rpi 3.

Grazie e ottimo lavoro con KoD!

**Comment by mac12m99** [comment]
Ciao, per favore assicurati che ci sia connessione sul dispositivo stesso, se sei certo che il device possa navigare allora vai in aiuto - segnala un problema e segui le istruzioni.

**Comment by Githeo** [comment]
Ciao @mac12m99,
tutto risolto. Anche se la Wi-Fi funzionava perfettamente, c'era un problema con la connessione ethernet. Banalmente riavviando il router adesso è tt ok.

Grazie mille e ottimo lavaoro!
