### ISSUE TITLE
Cancellare i Download

### ISSUE THREAD

**Issue by babyphone1** [Stream4me/addon#203]
Ciao a tutti, volevo sapere se qualcuno sa come si possono cancellare le serie tv scaricate e presenti nella cartella download.
Se tengo premuto sulla serie che voglio cancellare non mi da l’opzione “cancella”.
Grazie

**Comment by mac12m99** [comment]
Ciao,
Al momento l'unico modo per eliminare i file (senza farlo a mano) è andare in download->visualizza i file scaricati -> menu contestuale -> elimina file

In futuro prevediamo di mettere la possibilità di eliminare anche i file dal tasto "elimina tutto".

**Comment by babyphone1** [comment]
Molto gentile, grazie della risposta.

**Comment by mac12m99** [comment]
Possibilità nel tasto "elimina tutto" aggiunta, chiudo.
