### ISSUE TITLE
Download: voce di menu "elimina tutto"

### ISSUE THREAD

**Issue by fatshotty** [Stream4me/addon#205]
ciao
mi sono accorto di avere una lista lunghissima di file scaricati (ho scaricato 2 serietv con tutti gli episodi).
Ora vorrei cancellarla. Entro nella sezione Download. Clicco su "elimina tutto". Kod inizia a fare qualcosa (loading)... dopo qualche minuto ritorna alla schermata precedente con la lista sempre piena esattamente come prima.

ce' un modo per pulire tutta la lista?

**Comment by mac12m99** [comment]
Prova per curiosità ad uscire e rientrare (doppi puntini e poi di nuovo download), spesso capita non si aggiorni di conseguenza e ci sia bisogno di un refresh.
Se ci fosse ancora tutti vai in aiuto - segnala un problema e segui le istruzioni (che ti faranno ripetere la procedura)

**Comment by fatshotty** [comment]
confermo:
uscendo dalla lista e rientrando la vedo vuota. chiudo issue.
grazie mille ;)
