### ISSUE TITLE
Download: cartella videoteca errata

### ISSUE THREAD

**Issue by fatshotty** [Stream4me/addon#206]
Ciao,
ho scaricato la serietv iGriffin da Toonitaly (server Wstream).
L'ho lasciato scaricare per tutta la notte e quando sono tornato al pc mi aspettavo avesse finito e di ritrovarmi la serietv nella libreria di kodi (opzione abilitata nelle impostazioni di kod).
In realta' cosi' non e' stato. Aveva finito di scaricare tutto ma la serietv non e' comparsa in libreria.

ho controllato nella cartella della videoteca di kodi e infatti non c'era nulla.
Sono entrato via ssh sul mio pc e ho spulciato le cartelle. La seretv e' stata scaricata (o spostata) nella cartella sbagliata.

- cartella serietv in KOD:                        /data/samba/KOD/serie
- cartella download in KOD:                   /data/downloads
- cartella in cui ha spostato la serietv:  /data/samba/KOD/I Griffin
come si vede, mi aspettavo di trovare la cartella "iGriffin" dentro la cartella KOD/serie

E' un errore conosciuto?

Grazie in anticipo

**Comment by mac12m99** [comment]
Ciao,
è passato parecchio tempo, il problema potrebbe essere già stato risolto nel frattempo, se dovessi riaverlo riapri l'issue.
