### ISSUE TITLE
CB01: non visualizza server

### ISSUE THREAD

**Issue by RobsIp** [Stream4me/addon#207]
Salve, andando su CB01 non vengono visualizzati i server, visualizza i titoli dei film o serie TV ma non i server.
Dopo "miglioria findhost (fix cineblog)" andava ora un'altra volta no.

**Comment by mac12m99** [comment]
Per favore manda il log: aiuto - segnala un problema

**Comment by RobsIp** [comment]
https://ufile.io/fr132tqp

Il problema persiste su SERIE TV ---> ULTIME AGGIORNATE (non mostra i server)

Altre sezioni escono i server ma cliccando esce scritto niente da riprodurre.

**Comment by mac12m99** [comment]
Credo tu non abbia rifatto la procedura prima di creare il file di log, non trovo niente relativo a cb01.

Comunque effettivamente quella sezione non va più neanche a me, grazie della segnalazione!

**Comment by RobsIp** [comment]
L'ho fatta ma KOD non la dava come errore forse per questo.

Grazie 😊

**Comment by mac12m99** [comment]
Abbiamo fixato la riproduzione dai server (solito cambiamento di struttura), per quanto riguarda SERIE TV ---> ULTIME AGGIORNATE la cosa richiederà un po' perchè pare che stiano iniziando a caricare le serie in questo modo:
![image](https://user-images.githubusercontent.com/10120390/80394545-4ae06e80-88b2-11ea-9739-a22188d7f679.png)
Dobbiamo quindi scrivere un nuovo scraper da 0 per questo caso.

Per quanto riguarda la segnalazione tu non hai riprodotto il problema una volta mandato nel menu principale, sei ritornato in aiuto e quindi non ha loggato niente (devi prima ripetere la stessa cosa che ha causato l'errore, poi ritornare in aiuto).
Te lo dico così non ti sbagli per eventuali nuove segnalazioni.

**Comment by RobsIp** [comment]
Ok grazie, la prossima volta starò più attento :)

**Comment by mac12m99** [comment]
Lo scraper è stato scritto
