### ISSUE TITLE
Piratestreaming: nessun elemento da visualizzare

### ISSUE THREAD

**Issue by RobsIp** [Stream4me/addon#208]
Andando nelle sezioni riporta NESSUN ELEMENTO DA VISUALIZZARE

Sono andato sul canale --> Film --> Nessun elemento da visualizzare --> Aiuto --> Segnala un problema --> passaggi 1, 2, 3 --> log:

https://ufile.io/ixfewdmf

**Comment by mac12m99** [comment]
la versione beta di cloudcraper (7d32bde60d9bb25d5faa903798bb4b71a4f9ac32) dovrebbe aver fixato, con le solite limitazioni dovute sempre a cloudflare (android < 10 = nada, VPN = nada ecc..)

Riapri l'issue se così non fosse, grazie della segnalazione!
