### ISSUE TITLE
Netfreex: nessun elemento da visualizzare

### ISSUE THREAD

**Issue by RobsIp** [Stream4me/addon#209]
Andando nelle sezioni riporta NESSUN ELEMENTO DA VISUALIZZARE

Sono andato sul canale --> Film --> Nessun elemento da visualizzare --> Aiuto --> Segnala un problema --> passaggi 1, 2, 3 --> log:

https://ufile.io/obxe41ir

**Comment by mac12m99** [comment]
Grazie della segnalazione, tuttavia non sono in grado di riprodurre l'errore, vedo solo che dopo aver scaricato la pagina non trova niente, mi chiedo se il sito non fosse down proprio in quel momento.
Potresti riprovare?

**Comment by RobsIp** [comment]
Provato ad 16 e andava su KOD, dopo controllo.

**Comment by RobsIp** [comment]
Funziona.
