### ISSUE TITLE
Aggiornamenti serie tv su cb01

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#21]
Salve, stavo notando che su cb01 ci sono solo le novità per le serie tv ma non gli aggiornamenti, i film già ci sono, se si poteva implementare anche qui sarebbe perfetto.

**Comment by mac12m99** [comment]
Ciao,
intendi gli aggiornamenti che ci sono qui: https://cb01.date/serietv/aggiornamento-quotidiano-serie-tv/?

**Comment by hypno99** [comment]
> Ciao,
> intendi gli aggiornamenti che ci sono qui: https://cb01.date/serietv/aggiornamento-quotidiano-serie-tv/?

Esatto

**Comment by mac12m99** [comment]
Avevo aggiunto questa sezione qualche giorno fa, ma adesso mi sorge un dubbio, io ho preferito accorpare le serie per evitare di rendere troppo lunga la ricerca, di fatto eliminando il numero puntata, è un problema?
Considera anche che cb01 non inserisce il link diretto alla puntata ma alla serie, quindi andare direttamente alla puntata aggiunta in un solo passaggio richiederebbe ulteriori sforzi (e sarebbe necessario dividere la lista in più pagine per alleggerire)

**Comment by hypno99** [comment]
ah ok, se è un problema per la ricerca meglio toglierlo, era da preferire in questo modo ma pazienza.
