### ISSUE TITLE
Guardaserie: nessun elemento da visualizzare

### ISSUE THREAD

**Issue by RobsIp** [Stream4me/addon#210]
Andando nelle sezioni riporta NESSUN ELEMENTO DA VISUALIZZARE

Sono andato sul canale --> Film --> Nessun elemento da visualizzare --> Aiuto --> Segnala un problema --> passaggi 1, 2, 3 --> log:

https://ufile.io/5c4tcea8

**Comment by mac12m99** [comment]
Apparentemente guardaserie sta usando la nuova challenge di cloudflare che ancora non è supportata dalla libreria che usa kod
https://github.com/VeNoMouS/cloudscraper/issues/185
Quando lo sarà implementeremo la nuova versione.

**Comment by mac12m99** [comment]
Abbiamo cambiato il metodo che utilizziamo per i siti cloudflare, non dovresti aver più problemi.
Se così non fosse, riapri pure l'issue
