### ISSUE TITLE
Impossibile installare KOD (raspberry P2)

### ISSUE THREAD

**Issue by haziel-ang** [Stream4me/addon#212]
Ho tentato di installare KOD su Raspberry P2  e LibreElec v9.2 (Kodi 18.6 - Leia) senza successo. Ho utilizzato il Repository di github, mi fa completare tutte le operazioni, ma al momento dell’avvio mi richiede che versione vorrei installare (stable or beta) e finisce lì.

**Comment by mac12m99** [comment]
Strano, potresti inviare il file kodi.log? (naturalmente dopo aver riprovato l'operazione, cosicchè registri i possibili errori)
info su come estrarlo: https://telegra.ph/LOG-10-04

**Comment by haziel-ang** [comment]
http://ix.io/2khe

Qui troverai i log del Kodi. Ho eliminato il KOD, abilitato il log ed effettuato nuovamente l’installazione.

**Comment by mac12m99** [comment]
Sembrerebbe che il dispositivo non abbia più spazio

2020-05-01 10:56:55.572 T:1612878720  NOTICE: kod [updateFromZip] Non sono riuscito ad estrarre il file zip
2020-05-01 10:56:55.573 T:1612878720   ERROR: ######## ERROR #########
2020-05-01 10:56:55.573 T:1612878720   ERROR:     [kod.updateFromZip] [Errno 28] No space left on device

Puoi controllare se è vero?

**Comment by haziel-ang** [comment]
![C049478D-81B1-4895-A723-6DB2B47ED81E](https://user-images.githubusercontent.com/64601827/80800238-43b6aa80-8ba9-11ea-881c-327c2025dc6b.jpeg)

Ci sono 371MB di spazio libero.

**Comment by haziel-ang** [comment]
Allora il problema persiste, nonostante io abbia eseguito la procedura più volte, azzerando completamente tutti i valori. Attualmente ho testato l'altro sistema operativo per Kodi su Raspberry - OSMC, con successo. Il Kod funziona egregiamente e va tutto alla perfezione.

**Comment by mac12m99** [comment]
Domanda: la cartella .kodi si trova sulla sdcard o sulla memoria interna?

**Comment by haziel-ang** [comment]
Si trovava tutto su una SD da 32GB, così come con OSMC

**Comment by mac12m99** [comment]
Chiudo per mancanza di idee e impossibilita di riprodurre l'errore, se dovessi ancora riscontrarlo riapri l'issue.
