### ISSUE TITLE
improvvisamente Link Puntate Videoteca Vuoti e impossibile aggiungere nuovi link

### ISSUE THREAD

**Issue by Crilor** [Stream4me/addon#215]
Dopo l'aggiornamento di ieri sera ho trovato i link di tutte le serie inserite nella libreria vuoti e in più se ne aggiungo altri nuovi mi dice "Aggiunti alla libreria" ma alla fine tutte le punte rimangono presenti ma vuote all'interno. Help!
https://uploadfiles.io/ugw7zmiq

**Comment by mac12m99** [comment]
Ciao, dal log sembra trovare i server.. ti esce "nessun elemento da visualizzare" oppure una lista  vuota?

**Comment by Crilor** [comment]
Mi viene nessun elementi da visualizzare. Oggi ho fatto qualche altra 
prova, ho disinstallato kodi ripulito, reinstallato e importata la libreria 
di Kod. Fino a qui tutto a posto, tutti i link presenti, tutto perfetto! 
Poi ho riattivato la riproduzione automatica e dopo il primo tentativo di 
riproduzione automatica mi ha dato un errore di sorgenti non trovate e da 
li di nuovo tutte le puntate di tutta la videoteca si sono svuotare.
Disinstallato e reinstallato tutto e ora funziona di nuovo tranne che non 
ho ancora riattivato la riproduzione automatica... Ho paura a farlo!

In data 24 maggio 2020 10:55:53 mac12m99 <notifications@github.com> ha scritto:

**Comment by mac12m99** [comment]
E' passato parecchio tempo, il problema potrebbe essere già stato risolto nel frattempo, se dovessi riaverlo riapri l'issue.
