### ISSUE TITLE
Problema server mega post aggiornamento v1.0.1

### ISSUE THREAD

**Issue by Cirillone** [Stream4me/addon#216]
Ciao,

ho notato che l'aggiornamento alla versione 1.0.1 sui miei device (Win10 e Android) ha causato un problema allo streaming sui server MEGA utilizzati da HD4ME. Casualmente sono riuscito a far partire lo streaming di un film sul pc (versione 1.0.0 se ricordo bene), proprio prima dell'aggiornamento alla nuova versione. L'errore consiste nella mancata apertura dei link MEGA dopo un'attesa di una trentina di secondi, oppure il film si avvia ma si blocca la visione dopo pochi secondi. Potete verificare di cosa si tratta? 

Grazie per il supporto e saluti.

**Comment by mac12m99** [comment]
Ciao, sembrerebbe trattarsi più di un problema di lentezza, comunque potresti allegare il file di log col debug abilitato?
https://telegra.ph/LOG-10-04

**Comment by Cirillone** [comment]
Ecco qui, spero di aver fatto tutto correttamente.

http://dpaste.com/1SR65BX.txt

Se può essere utile, usando Megasync (l'app ufficiale di Mega) lo streaming non presenta problemi. Provando a fare il download del film tramite Megasync raggiungo i 6 MB/s circa, pertanto escluderei problemi di lentezza.
Grazie 1000 per l'aiuto!!!

Ciao

**Comment by mac12m99** [comment]
Ciao, puoi controllare se sulla versione beta funziona di nuovo?
Stessa procedura di installazione, senza disinstallare così non perdi niente, selezioni il ramo di sviluppo quando te lo chiede.
