### ISSUE TITLE
ricerca come da percorso non funziona

### ISSUE THREAD

**Issue by albo25869** [Stream4me/addon#217]
buonasera posso segnalare un problema:per verificare se a voi funziona? allora se dal percorso Canali - film - genere - esempio famiglia elenca i vari film...nel momento che ne selezioni uno il plugin restituisce nessun elemento da visualizzare invece se vai alla ricerca globale li trova il film scelto spero di essere stato chiaro
[log176674647.log](https://github.com/kodiondemand/addon/files/4684827/log176674647.log)

**Comment by mac12m99** [comment]
Ciao,
confermo il bug e aggiungo che accade non appena si va nella pagina successiva, ti informerò quando sarà risolto, grazie della segnalazione!

**Comment by mac12m99** [comment]
Ok, era più semplice del previsto, ti arriverà un aggiornamento che fixa la cosa.
