### ISSUE TITLE
IGDS: server Wstream non compare tra le scelte

### ISSUE THREAD

**Issue by RobsIp** [Stream4me/addon#218]
Sul sito tra le scelte Wstream compare mentre su KOD no, provato in aggiornamenti in serie TV sia in film, esce solo Mixdrop.

Log: https://ufile.io/yud0c2ip

**Comment by mac12m99** [comment]
Trattasi di un nuovo tipo di link wstream, grazie della segnalazione.

**Comment by mac12m99** [comment]
Risolto con f4a60081c37203ecf0d744624ee103d7bbca4288
