### ISSUE TITLE
Eurostreaming & Italia Serie

### ISSUE THREAD

**Issue by 32Dexter** [Stream4me/addon#219]
### Problemi riscontrati:
In tutti i siti di seguito sto cercando la Serie TV: Scorpion
Ma rilevo dei problemi nella visualizzazione dell'elenco stagioni/puntate.

### Canali:
- Eurostreaming
- Italia Serie

### Dettagli
In Eurostreaming  e Italia Serie non si riesce a visualizzare le stagioni/puntate, in allegato errore in nel log file (Errore di Eurostreaming ma è identico a Italia Serie).

![eurostreaming](https://user-images.githubusercontent.com/9434916/83850245-f0d49380-a710-11ea-9937-a650cc736c3e.jpg)

**Comment by Alhaziel01** [comment]
Ora dovrebbe essere stato Fixato
