### ISSUE TITLE
Errore durante il backup della videoteca

### ISSUE THREAD

**Issue by Crilor** [Stream4me/addon#220]
Come già accennato sul canale telegram il mio problema è che così mi da un errore non definito ogni qualvolta cerco di fare un backup della videoteca. 
Lo strumento è un Timbox Android TV
Ho provato a salvare il backup a memoria interna in una nuova cartella oppure dentro alla cartella Download ma il risultato è sempre lo stesso. 
Gli ultimi 2 aggiornamenti di ieri non hanno risolto il problema.
Invio log come richiesto sul canale. 
Grazie mille! 
https://ufile.io/X8qz99pg

**Comment by mac12m99** [comment]
Ciao,
sulla beta è stato mandato un fix che probabilmente fa al caso tuo, riesci a controllare?

**Comment by mac12m99** [comment]
Probabilmente risolto con ebe3d3df7bc68521fb053cdc02f106659a48f416
