### ISSUE TITLE
CB01 Android KoD stabile

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#221]
Quando si prova ad aprire qualsiasi film con il canale CB01 su android al posto dei vari siti di hosting viene visualizzato il seguente messaggio :Nessun elemento da visualizzare l'unico errore presente nei file log è il seguente 

2020-07-04 19:22:15.061 T:32248   ERROR: GetDirectory - Error getting
2020-07-04 19:22:51.957 T:32197   ERROR: Previous line repeats 31 times.

**Comment by mac12m99** [comment]
Ciao, non riesco a riprodurre l'errore, potresti mandare il log completo con tanto di logging di debug (KoD) attivo?

**Comment by xXTimmy89Xx** [comment]
> Ciao, non riesco a riprodurre l'errore, potresti mandare il log completo con tanto di logging di debug (KoD) attivo?

[log282530447.log](https://github.com/kodiondemand/addon/files/4873605/log282530447.log)

**Comment by mac12m99** [comment]
Forse ho capito, puoi inviarmi il file:
/.kodi/userdata/addon_data/plugin.video.kod/CF_Domains.txt

E poi provare a cancellarlo? (dopo averlo inviato, vorrei vederlo)

**Comment by xXTimmy89Xx** [comment]
> Forse ho capito, puoi inviarmi il file:
> /.kodi/userdata/addon_data/plugin.video.kod/CF_Domains.txt
> 
> E poi provare a cancellarlo? (dopo averlo inviato, vorrei vederlo)

[CF_Domains.txt](https://github.com/kodiondemand/addon/files/4873761/CF_Domains.txt)

Eliminato e riaperto KoD ma il problema sembra persistere

**Comment by mac12m99** [comment]
Ok, per favore rimanda il log e anche questo file:
/.kodi/userdata/addon_data/plugin.video.kod/settings_channels/cineblog01_data.json

**Comment by xXTimmy89Xx** [comment]
> Ok, per favore rimanda il log e anche questo file:
> /.kodi/userdata/addon_data/plugin.video.kod/settings_channels/cineblog01_data.json



[log397120840.log](https://github.com/kodiondemand/addon/files/4873971/log397120840.log)

{
    "settings": {
        "checklinks": false, 
        "checklinks_number": 2, 
        "include_in_global_search": true, 
        "include_in_newest_peliculas": true, 
        "include_in_newest_series": true
    }, 
    "url": "https://web.archive.org/save/https://cb01.trade/"
}

**Comment by mac12m99** [comment]
prova a cancellare anche cineblog01_data.json

**Comment by xXTimmy89Xx** [comment]
> prova a cancellare anche cineblog01_data.json

Confermo che dopo aver eliminato il file cineblog01_data.json il problema sembra essersi risolto, ho notato però un altro problema sempre su CB01 con l'autoplay , nonostante io abbia impostato come qualità preferita alta lui tende sempre a scegliere e a far partire la qualità SD, il problema sembra presentarsi solo su CB01

**Comment by mac12m99** [comment]
Il problema iniziale dovrebbe essere risolto per tutti con https://github.com/kodiondemand/addon/commit/2b6c8b0d9af5f1d6ec9dbb743b86eaccab984867
grazie della segnalazione!
Per quanto riguarda l'autoplay ho riprodotto il problema, sistemo appena riesco.

**Comment by xXTimmy89Xx** [comment]
Perfetto e grazie a voi per il lavoro svolto, e aiutare segnalando un problema mi sembra il minimo!
