### ISSUE TITLE
Problemi ricerca film e serie TV 

### ISSUE THREAD

**Issue by galass1** [Stream4me/addon#223]
Condivido il log del problema :https://ufile.io/84ogxs1r 
In sintesi su kodi non funziona la ricerca globale non analizza più tutti i canali e non trova più niente

**Comment by mac12m99** [comment]
Ciao, 
grazie della segnalazione, puoi riprovare ora? Dovresti ricevere un aggiornamento

**Comment by galass1** [comment]
Buonasera, ho ricevuto aggiornamenti ho riprovato ma non funziona, prima ricercava il film o la serie su tutti i canali e poi ti forniva elenco adesso no ...Sandra Galassi-------- Messaggio originale --------Oggetto: Re: [kodiondemand/addon] Problemi ricerca film e serie TV  (#223)Da: mac12m99 A: kodiondemand/addon CC: galass1 ,Author 
Ciao,
grazie della segnalazione, puoi riprovare ora? Dovresti ricevere un aggiornamento

**Comment by mac12m99** [comment]
Vai in ricerca globale -> "Scegli i canali da includere nella ricerca" e seleziona i canali in cui vuoi che cerchi
probabilmente la lista sarà vuota o quasi, di default quasi tutti sono in questa lista, ma il bug da te indicato ha fatto in modo che la lista di default venisse alterata (cosa che ora non dovrebbe più accadere per le nuove installazioni).
