### ISSUE TITLE
Nuova versione adesso in onda (sezione serie tv in onda oggi)

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#224]
Quando si clicca su una serie tv nella sezione serie tv in onda oggi viene incluso nella ricerca anche la stagione e l'episodio esempio Nome serie - XxX , questo tende a dare nessun risultato o in rari casi un riscontro se non addirittura risultati errati.

![screenshot001](https://user-images.githubusercontent.com/53865707/87872368-25966480-c9b8-11ea-9e10-04779b4b24dc.png)

![screenshot002](https://user-images.githubusercontent.com/53865707/87872369-2af3af00-c9b8-11ea-8cc2-b88244c6cc3f.png)

**Comment by mac12m99** [comment]
Grazie, dovrebbe essere risolto con a90190e869bb19d9008e8f2022a174c3bf9edd29, fammi sapere!

**Comment by xXTimmy89Xx** [comment]
> Grazie, dovrebbe essere risolto con [a90190e](https://github.com/kodiondemand/addon/commit/a90190e869bb19d9008e8f2022a174c3bf9edd29), fammi sapere!

Confermo il corretto funzionamento!
