### ISSUE TITLE
Nuovo canale Mediaset play

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#225]
Quando si prova ad aprire un qualsiasi programma si riceve errore

![screenshot000](https://user-images.githubusercontent.com/53865707/87877228-6654a480-c9dd-11ea-9a36-03c4a768ade5.png)

[LOG67082955.log](https://github.com/kodiondemand/addon/files/4943833/LOG67082955.log)

**Comment by Alhaziel01** [comment]
Ti ha chiesto di attivare inputstreamadaptive? 

Se non te lo ha chiesto, manda il log e dicci su quale os sei e quale versione di Kodi usi

**Comment by xXTimmy89Xx** [comment]
> Ti ha chiesto di attivare inputstreamadaptive?
> 
> Se non te lo ha chiesto, manda il log e dicci su quale os sei e quale versione di Kodi usi

Il problema sembra presentarsi solo nella sezione programmi TV e ha inziato a presentarsi dopo il commit  a079da9 nella beta e di conseguenza è stato importato nella stabile, non mi ha chiesto di attivare inputstream adaptive perchè non nego di utilizzare già una latra versione dell'addon di Mediaste Play.

![screenshot000](https://user-images.githubusercontent.com/53865707/87887463-bfe0c180-ca25-11ea-9ca5-94fdc78c7d01.png)

![screenshot001](https://user-images.githubusercontent.com/53865707/87887464-c66f3900-ca25-11ea-9527-d8d75ea2077d.png)

![screenshot002](https://user-images.githubusercontent.com/53865707/87887466-ca02c000-ca25-11ea-905c-bb4506000a05.png)

Essendo precedentemente in fase di sviluppo non ho segnalato subito il problema, in più ho notato che mancavano degli episodi in alcuni programmi tv

Allego nuovamente file log

[LOG67082955.log](https://github.com/kodiondemand/addon/files/4944826/LOG67082955.log)

**Comment by Alhaziel01** [comment]
Ora sulla beta dovrebbe essere tutto Ok, sono stati aggiunti clip e speciali per i programmi che lo prevedono.
Se mi dai conferma passo su stable.

**Comment by xXTimmy89Xx** [comment]
> Ora sulla beta dovrebbe essere tutto Ok, sono stati aggiunti clip e speciali per i programmi che lo prevedono.
> Se mi dai conferma passo su stable.

Confermo il corretto funzionamento! a parte un piccolo errore di numerazione visto che vengono numerate come se fossero serie tv con stagione e episodio.

![screenshot000](https://user-images.githubusercontent.com/53865707/87912184-348b1e80-ca6d-11ea-8e12-f3934383e8f2.png)

**Comment by Alhaziel01** [comment]
Non è un errore, quelle informazioni sono presenti.

**Comment by xXTimmy89Xx** [comment]
> Non è un errore, quelle informazioni sono presenti.
Colpa mia, abituato ad usare l'altro effettivamente fa strano, visto che il problema è stato risolto ti ringrazioe e chiudo.

![screenshot000](https://user-images.githubusercontent.com/53865707/87913722-d90e6000-ca6f-11ea-864c-b56b905f376f.png)
