### ISSUE TITLE
Richiesta reinserimento canali Sky e Mediaset Premium in adesso in onda

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#226]
Epg della vecchia versione di adesso in onda conteneva sia i canali di Sky che di Mediaset premium, canali che purtroppo non sono più presenti nella nuova versione , c'è un modo per reintegrarli o la possibilità di farli aggiungerli creando un epg personalizzato ? ho notato che in questa versione sono presenti http://epg-guide.com/it.gz

**Comment by Alhaziel01** [comment]
Su questa versione, però, mancano loghi e Copertine film

**Comment by Timmy89ITA** [comment]
> Su questa versione, però, mancano loghi e Copertine film

Si scusa errore mio, apparentemente a a breve verranno ripristinati 

![image](https://user-images.githubusercontent.com/53865707/87918176-5a68f100-ca76-11ea-827d-3fb9fe8ab015.png)

**Comment by xXTimmy89Xx** [comment]
> Su questa versione, però, mancano loghi e Copertine film

Si purtroppo ho aperto i file con notepad++ e ho notato le differenze , purtroppo però i canali in questione erano davvero comodi e da una parte non nascondo che il vecchio epg basato su Super Guida TV rimane il mio preferito al momento, spero ci sia un modo per implementarli nuovamente.

**Comment by xXTimmy89Xx** [comment]
Ripristinata la vecchia versione commit d153ac5
