### ISSUE TITLE
icona "ingranaggio" sempre in primo piano e impossibile fare backup videoteca

### ISSUE THREAD

**Issue by sperime** [Stream4me/addon#227]
Ciao, premetto che sono su un box android (T95, cinese con android 9. Ho disinstallato la versione di Kodi preinstallata e messo l'ultima versione da google play) e con l'ultima versione stabile di KOD, la 1.3 (ma avevo gli stessi problemi anche sulle precedenti release, e nonostante abbia reinstallato tutto dalla 1.2). 
Ho cercato la serie che mi interessa su alcuni canali (Breaking bad nello specifico, da Netfreex. serie TVU, serieHD e altri) e salvata nella videoteca. Però quando faccio partire un nuovo episodio mi rimane in primo piano l'ingranaggio di Kod (l'ingranaggio KOD che indica che sta lavorando) e rimane in primo piano per tutta la durata, proprio non scompare (non è un problema di buffering, il video procede senza nessun intoppo). Inoltre se clicco sul video, per qualsiasi motivo il tutto si blocca (non compare nemmeno l'interfaccia del player ma torna immediatamente alla schermata di selezione precedente). 
Altro problema è che mi è impossibile fare backup della videoteca (come un altro utente, https://github.com/kodiondemand/addon/issues/220)

[ho cercato di allegare il log ma non sono riuscito...]

**Comment by Alhaziel01** [comment]
per mandare il log basta trascinare il file sulla finestra dove scrivi il messaggio o cliccare qui:
![image](https://user-images.githubusercontent.com/46533140/87913222-fdb60800-ca6e-11ea-92a8-748c720ecc09.png)

**Comment by sperime** [comment]
ufile.io/b92nnh1y

qui il log

**Comment by sperime** [comment]
ho dato solo ora un'occhiata al log, come avrete sicuramente già capito meglio di me, la parte che interessante per noi è la parte finale, dalle 22:30 circa...

**Comment by mac12m99** [comment]
Il problema del backup dovrebbe essere risolto con ebe3d3df7bc68521fb053cdc02f106659a48f416
L'altro a meno di non riuscire a riprodurlo dubito capiremo mai a cosa è dovuto (non sono neanche sicuro sia dovuto a KoD).
