### ISSUE TITLE
Problema impostazioni/ricerca/Canali inclusi nella ricerca 

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#228]
Quando si clicca sulla voce interessata si riceve errore

![screenshot001](https://user-images.githubusercontent.com/53865707/87914124-7e293880-ca70-11ea-8014-7d562da34ad9.png)

![image](https://user-images.githubusercontent.com/53865707/87914152-871a0a00-ca70-11ea-80ca-8c8a30f349ca.png)

Allego file Log

[HBMH5NMUT.txt](https://github.com/kodiondemand/addon/files/4946386/HBMH5NMUT.txt)

**Comment by Alhaziel01** [comment]
Fixato
