### ISSUE TITLE
Ordinare sezione "Novità" per data di aggiunta / caricamento

### ISSUE THREAD

**Issue by iz8mbw** [Stream4me/addon#229]
Ciao.
La lista di contenuti generata in 'KoD -> Novità -> Film' è ordinata in ordine alfabetico anziché ordinata per data di caricamento.
Trattandosi di "Novità" e quindi lo scopo è vedere quali sono le novità disponibili sui vari canali avrebbe più senso se la lista generata e quindi visualizzata sia ordinata per data di caricamento/aggiunta (più recente in cima).

Per esempio, così (giustamente) funziona la sezione Torrent ('Kod -> Canali -> Torrents -> ilCorSaRoNeRo -> BDRiP'). Qui l'ordine di default è data di caricamento (più recente in cima).

Grazie mille!

**Comment by iz8mbw** [comment]
Ciao, c'è qualche possibilità in merito a questo?
Grazie.

**Comment by mac12m99** [comment]
Ciao,
ci sono un paio di problemi "tecnici" a questa richiesta, innanzitutto non è detto che il sito ordini per data di caricamento, inoltre se non è indicata la data come si fa a capire quale contenuto è stato pubblicato prima di un altro? Ricordo che in quella sezione non c'è un solo canale ma tanti

Personalmente una modifica che farei per rendere più fruibile la lista è raggruppare per contenuto, in modo che lo stesso film/serie non si ripeta.

**Comment by iz8mbw** [comment]
Ciao,
visto che l'addon da quello che so funziona con "scraping" dell'HTML delle pagine dei canali, mi aspetto che la richiesta può essere evasa perché il canale "x" mostrerà in alto le nuove uscite (aggiunti più di recente) e quelle successive a seguito in ordine appunto di caricamento cronologico.

Per farti una similitudine, la sezione Torrent ('Kod -> Canali -> Torrents -> ilCorSaRoNeRo -> BDRiP') ha l'ordine con il più recente aggiunto in cima perché così è la pagina HTML del sito. Lo stesso può essere fatto per i vari canali streaming.

**Comment by mac12m99** [comment]
Si certo, quello che intendevo è che, essendoci più siti web, non puoi sapere chi ha pubblicato prima se non lo indicano, devi per forza mostrare i risultati canale per canale.
Se il canale A ha 10 risultati in ordine di pubblicazione e il canale B altrettanti, e nessuno mostra la data, non puoi unirli e riordinarli nell'ordine corretto di pubblicazione, l'unica soluzione è inserire prima tutti quelli del canale A (in ordine come mostrato sul sito) e poi tutti quelli del canale B (sempre in ordine)
Che è più o meno ciò che abbiamo fatto sulla beta e che verrà rilasciato a breve.

**Comment by iz8mbw** [comment]
Ok capisco.
Ma sicuramente meglio così che andare su "Novità" e ridarci dopo 10 giorni e vedere la stessa lista che vedevi 10 giorni prima.
Com'era prima se dei canali avevano aggiunto dei contenuti con per esempio un film che inizia con la lettera "V" non l'avresti mai visto se non scorrervi fino alla lettera "V"....  :-)

Grazie mille!
