### ISSUE TITLE
Problema con animesaturn 

### ISSUE THREAD

**Issue by DarkSkull91** [Stream4me/addon#230]
Ciao, volevo segnalare che da qualche giorno non riesco più a vedere gli episodi di Naruto Shippuden dal sito animesaturn. Non compare più nella ricerca e nella mia videoteca. Ho controllato il sito ed è up così come tutti gli episodi.

È solo un problema mio?

**Comment by mac12m99** [comment]
Ciao, purtroppo siamo stati presi di mira dai gestori del sito
https://github.com/kodiondemand/addon/issues/201
https://github.com/kodiondemand/addon/commit/865ff915c4cc6f1795c463548eba97abc3aa99e5
Pertanto è assai probabile che ci saranno continui cambi di struttura, ti consiglio di evitare questi canali quando possibile (o, in alternativa, attendi i fix).
edit: ora dovrebbe essere ok, ma sicuramente il sito cambierà nel giro di poco.
