### ISSUE TITLE
Segnalazione siti vari 

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#231]
https://cinestreaming.uno/
http://cinecity.club/
https://streamingcommunity.to/
https://ddlstreamitaly.co/forum/150-%C2%BB-film-4k/

Se servono potete inserirli e sempre meglio avere più fonti disponibili.

**Comment by mac12m99** [comment]
Richiesta spostata qua: https://github.com/kodiondemand/addon/issues/240
