### ISSUE TITLE
Nuovi "potenziali canali da inserire" in KOD

### ISSUE THREAD

**Issue by Dance68** [Stream4me/addon#232]
Salve, in rete ho trovato questi altri "potenziali" canali, magari alcuni saranno cloni di quelli gia' presenti, altri mancanti. 
Sono questi :                                                  
- https://cinecity.club/  
- https://dvdita.site/ 
- https://www.sitostreaming.club/ 
- https://www.altadefinizione4k.stream/ 
- https://eurostreaming.run/ 
- https://vedohd.uno/ 
- https://cinestreaming.uno/ 
- https://www.filmstreamhd.it/ 
- https://www.cb01.global/ 
- https://openmovies.netlify.app/ 
- https://www.guardaserie01.com/ 
- https://cinefun.co/serietv-1/
Grazie della Vs. attenzione.

**Comment by mac12m99** [comment]
Lista spostata qua: https://github.com/kodiondemand/addon/issues/240
