### ISSUE TITLE
Problema importazione della videolibreria

### ISSUE THREAD

**Issue by Dance68** [Stream4me/addon#233]
Salve.
Ho disinstallato e reinstallato KOD e, dopo aver configurato tutto, ho cercato di importare la videolibreria precedentemente salvata, mi compare un avviso "Si e' verificato un errore in KoD" - Controlla il log per avere maggiori dettagli sull'errore. Percorso ....... 
Come posso risolvere ?
Grazie
Allego il log.
[kodi.log](https://github.com/kodiondemand/addon/files/5104015/kodi.log)

**Comment by mac12m99** [comment]
Probabilmente risolto con ebe3d3df7bc68521fb053cdc02f106659a48f416
