### ISSUE TITLE
AnimeSaturn disallineamento numero episodi naruto

### ISSUE THREAD

**Issue by DarkSkull91** [Stream4me/addon#236]
Ciao,

innanzitutto grazie per questo fantastico addon. Volevo segnalarvi un problemino riguardo il canale Anime Saturn. Ho aggiunto alla videoteca l'anime Naruto Shippuuden (ITA) e nella tredicesima stagione mi sono accorto che una volta cliccato su un episodio il numero è diverso. In pratica, è corretto quello che poi apre il link del video.

Non allego nessun log in quanto, l'episodio si vede, ma trae in inganno chi come me cerca di saltare gli epidodi filler.

A presto.

**Comment by Alhaziel01** [comment]
Ciao, scusami ma non sono sicuro di aver capito bene il problema.

Da quello che ho capito su anime saturn sono presenti episodi speciali e quando aggiungi alla videoteca te li segna come episodi normali e fa slittare la numerazione, corretto?

Se il problema è questo posso dirti che KoD può fare ben poco in automatico, dato che sul sito non ci sono riferimenti, l'unica cosa che si può fare è selezionare manualmente gli episodi speciali quando ti viene chiesto (click col destro sul titolo della serie > rinumera ) e alla richiesta "sono presenti episodi speciali?" rispondere si e seguire la procedura.

**Comment by DarkSkull91** [comment]
Ciao @Alhaziel01,

no non intendevo quello, mi sono spiegato male io.
Ho salvato gli episodi di Naruto Shippuuden presi da animesaturn nella videoteca. Faccio un esempio:

- seleziono la stagione 13 e compare la lista degli episodi di quella stagione
- seleziono l'episodio 123 e si apre la vista con i link degli episodi
- quando si apre la vista con i link l'episodio 123 è diventata 150

E' più chiaro con l'esempio?
C'è un mismatch dei numeri degli episodi tra la vista con l'elenco di tutti gli episodi e la vista dei link.

**Comment by Alhaziel01** [comment]
@DarkSkull91
:astonished: sicuro che sul sito siano corretti?

**Comment by DarkSkull91** [comment]
Sì sì guarda https://www.animesaturn.com/watch?file=HOuHDs1UiNSS8, su kod viene mostrato col numero 292 nella lista degli episodi, quando vieni reindirizzato nella vista link appare io numero corretto 277. Tra l'altro da stamattina neanche funzionano più i link, sia quello diretto sia quello di streamtape, devono aver ricambiato la struttura.

**Comment by DarkSkull91** [comment]
Segnalo il cambio di struttura del sito... Da stamattina non viene mostrato nessun link

**Comment by mac12m99** [comment]
Dovrebbe essere risolto, se così non fosse riapri l'issue.
