### ISSUE TITLE
SerieHD vuoto

### ISSUE THREAD

**Issue by luX0r-reload** [Stream4me/addon#238]
Ciao. Volevo segnalare che da qualche giorno i contenuti del canale SerieHD non sono "raggiungibili".
Per ogni categoria, lista che viene selezionata l'addon restituisce "No items to display"-

**Comment by mac12m99** [comment]
Ciao, grazie della segnalazione.
Il fix è già sulla beta e arriverà nella stabile insieme alla nuova versione 1.4, questione di poco.
