### ISSUE TITLE
Problemi sul canale Dreamsub

### ISSUE THREAD

**Issue by luX0r-reload** [Stream4me/addon#239]
Ciao. Volevo segnalare un problema per i contenuti del canale Dreamsub (Anime). Pur riuscendo a navigare tra le categorie, a fare ricerche e a vedere la lista degli anime, fallisce la riproduzione di qualsiasi contenuto.

**Comment by Alhaziel01** [comment]
Ora dovrebbe Funzionare.

**Comment by luX0r-reload** [comment]
It works!
