### ISSUE TITLE
Errata visualizzazione "Torrents" nelle liste delle pagine Successive a quella iniziale

### ISSUE THREAD

**Issue by iz8mbw** [Stream4me/addon#241]
Ciao.
Le pagine "Successive" di Torrents non mostrano i dettagli dei contenuti (Film) nella visualizzazione standard "Lista".
In dettaglio le locandine dei Film (e quindi anche le valutazioni/ratings) non sono disponibili.
Per visualizzare il problema andare su: KOD -> Canali -> Torrents -> ilCorSaRoNeRo -> BDRiP -> scorri in basso fino a "Successivo >", clicca su "Successivo >" (quindi l'addon mostrerà i successivi Torrents) e si vede che i film in questa lista non mostrano né le locandine né le valutazioni (quelle di TMDB o IMDB).

Spero possiate risolvere il problema.
Grazie!

**Comment by mac12m99** [comment]
Ciao,
grazie della segnalazione, dovrebbe essere stato risolto: 81c03436bbc962399ed18760781085382a28599e

**Comment by iz8mbw** [comment]
Grazie mille, confermo, adesso OK. Grazie
