### ISSUE TITLE
Errata visualizzazione delle locandine in "Torrents" con Kodi 19

### ISSUE THREAD

**Issue by iz8mbw** [Stream4me/addon#243]
Ciao!
Ho di recente aggiornato Kodi 18 con Kodi 19. Utilizzo Android.
Con Kodi 19 non tutte le locandine nella sezione Torrent vengono visualizzate (vai su: KOD -> Canali -> Torrents -> ilCorSaRoNeRo -> BDRiP).
Nel dettaglio le uniche locandine che compaiono sono quelle quando sul nome del torrent c'è l'icona del puntino prima del nome (come se fosse un file) invece quelle che non vengono visualizzate (sono la maggioranza purtroppo) accade quando sul nome del torrent c'è l'icona della cartella prima del nome (come se fosse una cartella).

Spero possiate risolvere il problema.
Grazie!

**Comment by iz8mbw** [comment]
Aggiungo inoltre che una volta entrati in KOD -> Canali -> Torrents -> ilCorSaRoNeRo -> BDRiP in alto a sinistra dell'interfaccia è scritto "Serie TV / Kodi on Demand" come se questa sezione di Film venga riconosciuta come Serie TV.

**Comment by mac12m99** [comment]
Ciao,
grazie della segnalazione, sulla versione beta dovrebbe essere già a posto con a4ba6542c9823d799941ece19b2d257cfe9f8b1d
Il fix verrà incluso nella stabile con la prossima major.

Per quanto riguarda il tipo di contenuto, DBRIP contiene sia film che serie (nonostante i film siano la stragrande maggioranza), pertanto a seconda dei casi potrebbe capitare..

**Comment by iz8mbw** [comment]
Grazie mille. Inoltre volevo segnalarti che, sempre usando Kodi 19, ogni qualvolta va in play un Torrent compare il classico messaggio di errore e di controllare il file di log di Kodi anche se in realtà non c'è alcun problema e il Torrent va in play correttamente.

**Comment by mac12m99** [comment]
Grazie della segnalazione, l'ultimo commit della beta forse risolve (non ho testato la cosa, potresti farlo tu?)

**Comment by iz8mbw** [comment]
Come switcho da stable a beta?

**Comment by mac12m99** [comment]
Procedi come la normale installazione (senza disinstallare), e alla scelta del branch seleziona master (versione beta)

**Comment by iz8mbw** [comment]
Ma per fare prima non è che posso editare qualche file? Preferisco connettermi via SMB ed editare il/i file di config.

**Comment by mac12m99** [comment]
Si tratta proprio di un'altro ramo di sviluppo, il codice sorgente è diverso (infatti, la beta viene usata per i test)
Comunque, trattandosi di una modifica banale, puoi rifarla a mano via SMB se ti è più comodo:
https://github.com/kodiondemand/addon/commit/5363031f4ef75255636092d144a463fe34be9e93 (solo default.py)
Assicurati di rispettare l'indentazione (gli spazi), python da errore se non sono corretti.

**Comment by iz8mbw** [comment]
Ok, chiaro. Quando posso testo e ti scrivo qui.

**Comment by mac12m99** [comment]
Grazie,
effettua anche questa modifica, a dire il vero è assai probabile che sia questa in realtà a fixare:
20c9509104d671980daf5d62bc60ffe860ad89f1

(Sono tutti piccoli cambiamenti legati alle modifiche che hanno fatto di recente in kodi 19)

**Comment by iz8mbw** [comment]
Ciao, applicati entrambi i fix e funziona alla grande! Grazie.
Per me li puoi mergiare nella stable. 
Grazie!!
