### ISSUE TITLE
Errore di installazione su Kodi 17.6 con LibreELEC

### ISSUE THREAD

**Issue by Gr33nR10t** [Stream4me/addon#244]
Ciao sto usando Kodi 17.6 con LibreELEC 8.2.5.

Durante la fase di installazione mi viene richiesto di configurare i due addons aggiuntivi per film e serie TV; purtroppo però non è possibile modificare la lingua predefinita in IT e dopo aver accettato le impostazioni di default ricevo un errore che mi dice di controllare i logs.. al termine dell'installazione trovo Kodi on Demand BETA installato con la versione 1.4.1 e974ab7.

[kodi.log](https://github.com/kodiondemand/addon/files/5541657/kodi.log)

**Comment by mac12m99** [comment]
Ciao,
mi spiace ma KoD non viene più testato su kodi 17, che è quindi da considerarsi non supportato, ti consiglio di aggiornare la versione di libreelec in modo da avere kodi 18.
