### ISSUE TITLE
STREAMTAPE E HDMARIO

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#245]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

STREAMTAPE rimanda sempre un errore e dà l'opzione di aprire nel browser
HDMARIO Non accetta le credenziali anche se si è registrati sul sito (ho provato 2 diversi telefoni uno con root e l'altro senza però con vpn ADAWAY. Nel non root con vpn la registrazione è andata a buon fine
Nel root con ADAWAY che scrive nel file hosts di android, anche se si è registrati riporta la schermata errore con apertura browser e tasto ok.
PS: Potete fare una prova con la serie TV "**Dark**" e scegliere il sito **seriehd**
**AGGIORNAMENTO:** 
Provato a resettare il file hosts con quello di default ma l'errore riportato è lo stesso.
Samsung Galaxy s6 con Evolution X custom ROM.
L'altro cellulare dove funziona HDMARIO (ma streamtape da sempre errore ugualmente) è Samsung Galaxy A51 con Stock Rom

- 

- [x] Sono da computer ora e ho il log nel cellulare, se riesco a trovarlo e passarlo su pc lo allego.
EDIT: Logs allegati
[Kodi_Logs.zip](https://github.com/kodiondemand/addon/files/5561477/Kodi_Logs.zip)

**Comment by mac12m99** [comment]
Ciao, grazie della segnalazione, questi commit dovrebbero fixare:
133f220674cf4a1e6e24c38f06b436cd17941bb2
7c323c309b82385b372d6b2db4ff30bb7dedf043

Comunque per HDmario noto che il problema è in fase di registrazione automatica, in caso tu abbia già le credenziali non avrebbe dovuto dare problemi.
Comunque fammi sapere.

**Comment by omgfrost** [comment]
> Ciao, grazie della segnalazione, questi commit dovrebbero fixare:
> [133f220](https://github.com/kodiondemand/addon/commit/133f220674cf4a1e6e24c38f06b436cd17941bb2)
> [7c323c3](https://github.com/kodiondemand/addon/commit/7c323c309b82385b372d6b2db4ff30bb7dedf043)
> 
> Comunque per HDmario noto che il problema è in fase di registrazione automatica, in caso tu abbia già le credenziali non avrebbe dovuto dare problemi.
> Comunque fammi sapere.

Non capisco i commits, cioè devo fare qualcosa io o basta che apro KOD e si auto aggiorna?
Per quanto riguarda l'autenticazione a HDMARIO mi da ancora problemi sullo smartphone rooted. Nonostante mi sia registrato direttamente dal sito e ho inserito le credenziali in KOD -> Server -> HDMario...
Rimango in attesa di risposta,
ringrazio.

**Comment by omgfrost** [comment]
UPDATE: Per STREAMTAPE tutto ok ora dovevo soltanto avviare codi e ho letto che ha aggiornato i 2 commits.
Per quanto riguarda HDMARIO ho questo screen:
![dS06dIZ 1](https://user-images.githubusercontent.com/14861120/99710003-4ecb1c80-2aa0-11eb-9a6c-a06a406e6f7a.png)
Credo che la finestra di errore dovrebbe essere piu' larga perchè nel titolo non si legge il motivo del blocco: NON E' POSSIBILE VEDERE QUESTO VIDEO PERCHE'.... credo crei un po' di suspance mischiato ad ansia xD
PS: Come si mette lo spoiler qui su Github? Credo che l'immagine troppo grande dovrebbe esser messa sotto spoiler 👍

**Comment by mac12m99** [comment]
> Non capisco i commits, cioè devo fare qualcosa io o basta che apro KOD e si auto aggiorna?

Si scusa non ho specificato, KoD si auto-aggiorna tramite i commit (modifiche) che vengono inserite su github

> Per quanto riguarda l'autenticazione a HDMARIO mi da ancora problemi sullo smartphone rooted. Nonostante mi sia registrato direttamente dal sito e ho inserito le credenziali in KOD -> Server -> HDMario...

Sicuro che l'account sia attivo? Se apri il link di uno streaming riesci a vederlo da browser? (puoi cliccare su apri nel browser per fare prima)
Te lo chiedo perchè HDmario richiede di confermare la mail cliccando su un link inviato per posta, se non lo fai l'account non è attivo e non può visualizzare gli stream.


> Credo che la finestra di errore dovrebbe essere piu' larga perchè nel titolo non si legge il motivo del blocco: NON E' POSSIBILE VEDERE QUESTO VIDEO PERCHE'.... credo crei un po' di suspance mischiato ad ansia xD

:D a dire il vero è proprio così, la continuazione della frase è il messaggio stesso che vedi sotto ("si è verificato un errore")
Questi messaggi li cambieremo a breve comunque..

> PS: Come si mette lo spoiler qui su Github? Credo che l'immagine troppo grande dovrebbe esser messa sotto spoiler

In effetti non c'è niente di facilmente utilizzabile, ma da una rapida ricerca ho trovato questo (prova a rispondere per vedere):
<details>
  <summary>blabla</summary>
dsadwdqw
</details>

**Comment by omgfrost** [comment]
> > Non capisco i commits, cioè devo fare qualcosa io o basta che apro KOD e si auto aggiorna?
> 
> Si scusa non ho specificato, KoD si auto-aggiorna tramite i commit (modifiche) che vengono inserite su github
> 
> > Per quanto riguarda l'autenticazione a HDMARIO mi da ancora problemi sullo smartphone rooted. Nonostante mi sia registrato direttamente dal sito e ho inserito le credenziali in KOD -> Server -> HDMario...
> 
> Sicuro che l'account sia attivo? Se apri il link di uno streaming riesci a vederlo da browser? (puoi cliccare su apri nel browser per fare prima)
> Te lo chiedo perchè HDmario richiede di confermare la mail cliccando su un link inviato per posta, se non lo fai l'account non è attivo e non può visualizzare gli stream.
> 
> > Credo che la finestra di errore dovrebbe essere piu' larga perchè nel titolo non si legge il motivo del blocco: NON E' POSSIBILE VEDERE QUESTO VIDEO PERCHE'.... credo crei un po' di suspance mischiato ad ansia xD
> 
> :D a dire il vero è proprio così, la continuazione della frase è il messaggio stesso che vedi sotto ("si è verificato un errore")
> Questi messaggi li cambieremo a breve comunque..
> 
> > PS: Come si mette lo spoiler qui su Github? Credo che l'immagine troppo grande dovrebbe esser messa sotto spoiler
> 
> In effetti non c'è niente di facilmente utilizzabile, ma da una rapida ricerca ho trovato questo (prova a rispondere per vedere):
> 
> blabla
<details>
<summary>prova spoiler</summary>
non credo si veda nel quote\risposta. 
UPDATE: Ho dovuto cercare anche io il blockcode per farlo 🤣 
</details>

Comunque si, se faccio apri da browser, il mio Brave ha già i cookies memorizzati per il mio account infatti vedo direttamente esempio: `hdmario.live/embed/mioid/filmato`
quindi non capisco proprio perchè non prenda le credenziali per riprodursi direttamente nel player di kodi e io lo vorrei li perchè averlo nel browser di un galaxy s6 fa un pochino schifo 🤣 
Cosa suggerisci di fare altro?
Magari c'è qualche file nelle dir di android per vedere se ha memorizzato le credenziali giuste?
ripeto il mio è rooted e ha ADAWAY che blocca gli ads via file hosts di android. Ma ho provato a resettarlo e non va uguale.
ripeto, mentre in quello di mia madre con la stock rom galaxy A51 con il suo account hdmario funziona.
e si, ho provato ad usare il suo account nel mio ma niente....sempre quella finestra di errore....
Help meeeee! 😕 
UPDATE: Appena provato e se faccio apri nel browser si logga direttamente col mio account: `https://hdmario.live/embed/****`
gli asterischi sono ovviamente il mio ID utente...
ho provato a cancellare i cookies del sito ma nelle impostazioni del browser non c'è traccia di HDMARIO....
Ora provo a cercare di farmi rimandare la password via email ma siccome l'url è "complicata" bisogna cercare la pagina esatta da google o duckduckgo....

Sono riuscito a resettare la password:
<details>
<summary>Screenshot reset password</summary>
https://i.imgur.com/XkiZazW.png (non so perchè non prende direttamente l'immagine usando lo spoiler. Ho provato anche a drag-dropparla e riporta tutto il link lungo ma non embedda l'immagine.
PS: il sito per resettarla è a questo link: https://hdmario.live/forgotPassword
</details>
Ora provo da Kodi
Niente..sono tornato indietro e ho visto il changelog dei fix anche per HDMARIO e ora dopo il reset password ho questa:

![NAPvA9R 1](https://user-images.githubusercontent.com/14861120/99723051-ec7b1780-2ab1-11eb-9835-a35163b43397.png)

**Comment by omgfrost** [comment]
omg omg omg ho resettato la password pensando che fosse un problema di lunghezza o di numero o di lettera...
rimodificata in piu' lunga ora và! 🤣 
Credo che accetti soltanto password da 6 o 8 caratteri...vabbè potete chiudere qui.
Grazie di cuore ai devs! ❤️ 
EDIT UPDATE: OMMAMMAMIA! Da PC tutto ok con password nuova, da cellulare ridà sempre lo stesso errore...forse non memorizza le credenziali fino a che non  lo riavvii..ora provo... 💤 
EDIT UPDATE 2: Niente da android non và...mi dice controlla i log..ho provato a tener premuto e fare sia riproduci che riproduci da qui, sembra che carica un po' e poi schermata di errore..
Vi uploado i logs?
Per avere i logs devo attivarli dal debug o si creano automaticamente? No perchè l'ultima volta senza debug non li ho trovati...
Attendo imposizioni dall'alto 🤣

**Comment by omgfrost** [comment]
Credo che sia questo il problema che ho trovato nei log:
```
 </div>
                                                    <i class="fa fa-user-secret" style="font-size: 32pt; display:block;"></i>
                                                    <strong>Attenzione</strong> potresti riscontrare problemi utilizzando il browser da navigazione in incognito.
                                                    <br/><a class="btn btn-primary btn-sm" href="https://hdmario.live/user/not-active/2763" target="_blank">Premi qui</a>
                                                    in caso tu stia riscontrando problemi durante il login.
                                                </div>
                                            </div>
                                            
                                            <div id="disabledCookiesMessage" class="full-screen-error"  style="display:none" >
                                                <div>
                                                    <div class="col-md-12 text-center">
                                                        <img class="img-responsive main-logo" src="/alta-logo-black.png" />
                                                    </div>
                                                    <strong>Attenzione</strong> il tuo browser ha bloccato i nostri cookie tecnici di autenticazione.
                                            
                                                    <div class="mt-3">
                                                        <a class="btn btn-primary btn-lg" href="https://hdmario.live/user/not-active/2763?relogin=" target="_blank">
                                                            <i class="fa fa-caret-right"></i> RIPRODUCI IL VIDEO
```
href="https://hdmario.live/user/not-active/2763?relogin  <--- questo link è rimasto nelle impostazioni e non va via..ho spento, riacceso e pulita pure la cache di KOD...nulla da fare...quel link non si modifica.
Allego il log
[kodi.log](https://github.com/kodiondemand/addon/files/5569812/kodi.log)

**Comment by mac12m99** [comment]
Se assicuri che username e password sono validi (se ti logghi da browser, puoi riprodurre i video) e li hai scritti giusti, allora è un bug di KoD, quindi per sapere cosa c'è che non va dobbiamo avere i log (vedi https://telegra.ph/LOG-10-04).
Per quanto riguarda Adway non ci metto la mano sul fuoco ma non dovrebbe essere un problema.

PS
l'asterisco in https://hdmario.live/embed/*  è l'id del video


Stavo scrivendo questo messaggio e mi hai già mandato il log, vedo che la pagina ritornata da HDmario dice "Clicca sul link d'attivazione che ti abbiamo inviato al tuo indirizzo email." ergo è come sospettavo, non hai cliccato sul link di conferma.
Questo messaggio, se davvero hai provato a riprodurre qualcosa, dovresti averlo visto..
Fatti re-inviare la mail aprendo il link che hai postato (dovrebbe permetterlo in teoria.. non ho mai provato)

**Comment by omgfrost** [comment]
> Se assicuri che username e password sono validi (se ti logghi da browser, puoi riprodurre i video) e li hai scritti giusti, allora è un bug di KoD, quindi per sapere cosa c'è che non va dobbiamo avere i log (vedi https://telegra.ph/LOG-10-04).
> Per quanto riguarda Adway non ci metto la mano sul fuoco ma non dovrebbe essere un problema.
> 
> PS
> l'asterisco in https://hdmario.live/embed/* è l'id del video
> 
> Stavo scrivendo questo messaggio e mi hai già mandato il log, vedo che la pagina ritornata da HDmario dice "Clicca sul link d'attivazione che ti abbiamo inviato al tuo indirizzo email." ergo è come sospettavo, non hai cliccato sul link di conferma.
> Questo messaggio, se davvero hai provato a riprodurre qualcosa, dovresti averlo visto..
> Fatti re-inviare la mail aprendo il link che hai postato (dovrebbe permetterlo in teoria.. non ho mai provato)

Guarda, ho fatto il reset della password da pc e da Kodi windows HDMARIO funziona.
Non funziona sul cell e quella dicitura del clicca sul link di attivazione non la ho piu' è solo nel log, per ora....
Per quanto riguarda tutto ciò che  hai scritto sopra è come ho già scritto sopra 😄 ossia che l'username e password sono autentici e funzionano benissimo su kodi pc. Come ripeto ho messo username e password su kodi android ma il problema è quello sopra...
Cioè alla fine tu dici che devo farmi mandare il link di attivazione sul cellulare così KOD lo memorizza?
ma io non credo...me lo sono fatto mandare su pc....e credo che le credenziali ormai siano già attive dato che sul pc parte...
boh..ora provo sul cell a vedere se mi ridà questo link di attivazione ma non garantisco...

**Comment by omgfrost** [comment]
Guarda, ora ho fatto la registrazione random automatica e ha trovato una email generata non utilizzata e ha detto attivazione con successo...subito dopo instantaneamente la solita schermata di errore con apri browser e ok....quindi credo sia un bug di KOD su android (forse questa specifica versione non so)
Allego nuovo log.
[kodi.log](https://github.com/kodiondemand/addon/files/5569949/kodi.log)
EDIT: Vedo sempre quel link del user-not-active nonostante si sia autenticato con credenziali auto generate e andate a buon fine...

**Comment by omgfrost** [comment]
Niente da fare...ho fatto apri nel browser e c'era accedi, ho inserito le mie credenziali ed è subito partito il video NEL BROWSER.
Da Kodi niente da fare...non le accetta per colpa di quel link che non va via dal log..
[kodi.log](https://github.com/kodiondemand/addon/files/5570021/kodi.log)

**Comment by omgfrost** [comment]
Ok, nuovo aggiornamento....
se faccio tenuto premuto su HDMARIO --> riproduci ---> errore -->ok ---> riproduci (ancora) ---> errore -->ok ---> **riproduci da qui** ---> il video parte sul player di kodi 🤷 
[kodi.log](https://github.com/kodiondemand/addon/files/5570110/kodi.log)
PS: Bene, ho riprovato e con questo workaround bypassa l'autenticazione...bel metodo di sicurezza 🤣 
scherzi a parte..rimango così finchè non troviate la soluzione ortodossa
Grazie e saluti, per ora

**Comment by omgfrost** [comment]
Ragazzi ci sono riuscito!
Ho disinstallato completamente kodi con revo uninstaller mobile reistallato sia kodi che kod addon, messo le mie vere credenziali e ora funziona
Ora va pure con la skin aeon nox: SILVO
Ho risolto da solo.
Praticamente era un file che generava il link di hdmario user not active
Usato revo uninstaller per togliere tutto
Reinstallato tutto e con mie credenziali hdmario va che è una bellezzza
Grazie a me. Chiudete pure.grazie
