### ISSUE TITLE
Riproduzione non funzionante su Android TV

### ISSUE THREAD

**Issue by EffeF** [Stream4me/addon#246]
Se, su Android TV, nelle opzioni di Kodi (18.9) è attiva l’opzione “Regola la frequenza di aggiornamento del display” (impostata su “All’avvio / arresto”) i contenuti aggiunti alla libreria di Kodi non partono, sia con l’AutoPlay che senza, e l’app si blocca, costringendomi a forzare l’interruzione. Ho provato anche una installazione pulita, con tutte le impostazioni di default tranne la sopracitata, ed il problema persiste. 

Direttamente dalla videoteca interna all’AddOn invece funziona, il problema è solo con la libreria nativa di Kodi.

**Comment by mac12m99** [comment]
Ciao,
purtroppo questo è un problema legato a kodi e al dispositivo, non possiamo farci molto.
Credo che l'unica cosa che tu possa fare sia tenerla disattivata..
