### ISSUE TITLE
Errata visualizzazione "Torrents" nelle liste delle pagine Successive a quella iniziale

### ISSUE THREAD

**Issue by iz8mbw** [Stream4me/addon#248]
Ciao.
Come per questa issue già risolta https://github.com/kodiondemand/addon/issues/241 le locandine delle pagine "Successive" dei Film per "DVD" e "Screener" (e quindi anche le valutazioni/ratings) non sono disponibili.
Per visualizzare il problema andare su: KOD -> Canali -> Torrents -> ilCorSaRoNeRo -> DVD -> scorri in basso fino a "Successivo >", clicca su "Successivo >" (quindi l'addon mostrerà i successivi Torrents) e si vede che i film in questa lista non mostrano né le locandine né le valutazioni (quelle di TMDB o IMDB).
Lo stesso accade per le pagine successive di KOD -> Canali -> Torrents -> ilCorSaRoNeRo -> Screener

Utilizzo Kodi 19 su Android TV.

Grazie!

**Comment by iz8mbw** [comment]
Ciao @mac12m99 
hai news circa questo problema?
Grazie.

**Comment by mac12m99** [comment]
No ancora niente, ma l'issue rimane quindi non ce ne dimentichiamo.

**Comment by mac12m99** [comment]
Corretto con 7b1ba2d4f2a6a6bdb17fe97ec7fad336fcaba958

**Comment by iz8mbw** [comment]
Ciao @mac12m99
Grazie per la commit. 
Volevo segnalarti però che a seguito di questa commit non è più possibile accedere alla pagina "Serie TV" de Il CorsaroNero. 
Prova anche tu, vai: KOD -> Canali -> Torrents -> ilCorSaRoNeRo -> Serie TV.
Vedrai che la "clessidra" di Kodi gira senza mai restituire alcun risultato. 
Grazie.

**Comment by mac12m99** [comment]
Ciao,
si hai ragione, ora dovrebbe andare.

**Comment by iz8mbw** [comment]
Ciao @mac12m99 
Grazie, adesso "Serie TV" funziona di nuovo ma purtroppo le locandine non vengono mostrate.
Alla selezione delle righe (contenuti) si vedono solo le immagini si sfondo (fanart) e non le locandine.
Spero riesci a risolvere anche questo. Grazie!

**Comment by mac12m99** [comment]
Ciao,
a me escono.. certo non su tutte perchè il riconoscimento del contenuto non è troppo preciso, ma anche scorrendo le pagine le vedo.

**Comment by mac12m99** [comment]
Ora che il corsaro è di nuovo online, riscontri lo stesso problema? Magari fai degli esempi con screenshot
