### ISSUE TITLE
Possibile che sia attivata qualche impostazione di debug nell'ultima stabile ???

### ISSUE THREAD

**Issue by DjDiabolik** [Stream4me/addon#249]
Ciao ragazzi.... ne discutevo un pò poco fa nel gruppo telegram di kodi perchè, vista l'ora, il gruppo di kod è in pausa notturna.

Stavo dando una vista al log di kodi, per altri motivi, e ho notato un bel pò di informazioni riportate nel log che non avevo mai notato prima.
La prima stranezza che ho notato è la grandezza stessa del file kodi.log...... come dicevo li io oggi ho acceso il mio Pi2 poco dopo pranzo (13:28 riporta il log) e stavo guardando ora il kodi.log è di quasi 2MB.

Strano...... mi son detto subito anche in passato ho tenuto acceso il mio Pi2 per giorni e giorni consecutivi e mai ho ottenuto sia lo stesso kodi.log che il suo kodi.old.log cosi grandi.

Incuriosito sono andato a dare una vista scoprendo che..... il log di debug di kodi è ovviamente disattivato (altrimenti me ne sarei accorto a TV che anche li compaiono le informazioni di debug di kodi giusto) ma che il log stesso contiene il 95% delle righe relative al kod stesso....... tipo guardate ne posto uno stralcio come esempio dalle 21 di stasera:

*EDIT*
Cavoli il copia e incolla qua è improponibile... ho messo lo spezzato del log qua.. dateci una vista se possibile.... (thanks):
https://pastebin.com/dgxYgg9M

Oppure qua perchè Pastebin on collabora e da errore:
https://0bin.net/paste/yIw1nWnd#paZITvAP5JXbnoJwdkoxtW9uzxAwJLvwTQxxBD1IZlI

Cioè non ho mai visto tutte queste informazioni relative a kod..... come potete vedere mi sono un filmetto dalle 23 circa di stasera ma guardate quanta roba e quante informazioni vengono salvate nel kodi.log.
Ripeto mai visto niente di simile in passato....... è normale tutto ciò ?

Nelle impostazioni dello stesso addons c'è un'opzione per attivare il debug relativo a kod e io ho controllato è disattivato..... però non so è come se qualche informazione di debug filtri cmq.

**Comment by mac12m99** [comment]
Ciao,
come già detto sul gruppo il logging di debug attiva la registrazione di altri log ancora più specifici, ma aggiungo che prima non era così dato che salvava solo gli errori, abbiamo modificato il comportamento in quanto più consono all'idea del log (anche kodi fa così: poche info di default, tantissime se abiliti il debug).
Probabilmente abbiamo calibrato male la cosa, ma non è un problema propriamente detto.

Per quanto riguarda il tuo 0bin (il pastebin è scaduto) non riesco a caricarlo tutto perchè si impalla la pagina :D
Riesco comunque a vedere un pezzo: le righe più frequenti provengono da tmdb, e queste si forse sono un po' troppo specifiche, le righe che iniziano con SPLIT non ho dubbi che vanno messe solo nel debug, ma tutte le altre le lascerei.

Se vuoi mandare tutto il kodi.log prova a caricarlo qui come file di testo, o magari indicami degli esempi di righe che ripetono troppo/troppo lunghe

**Comment by mac12m99** [comment]
Il numero di informazioni salvate è stato drasticamente ridotto sulla beta: 4f498a05f8dc8df267912fc0965b0c11305992a9
Questi cambiamenti arriveranno sulla stabile insieme alla prossima versione.

**Comment by DjDiabolik** [comment]
Ok grazie......... viene fuori una cosa infinita ma ora vi spiego com'è che ho notato queste cose.
Allora di recente ho copiato nella mia pendrive attaccata al mio Pi2 alcune roms del nes e del gb. Ogni tanto usando gli emulatori integrati in kodi mi sono fatto qualche partitina in retroemulazione per ritornare ai fasti dei miei anni 90.
Bene... collegando un joypad gamestop della xbox 360 iniziavo a notare che molto spesso il mio pi2 freezava completamente durante l'emulazione!! 
Ebbene si potevo guardare streaming video per ore e ore usando lo stesso kod oppure l'addons di youtube ma come aprivo una roms .nes il tutto freezava.
Come detto sul mio Pi2 delle 4 porte usb 3 sono occupate........ la pendrive... l'adattore bluethoot per una tastiera e appunto il joypad ho pensato che quest'ultimo potesse mandare in crisi l'alimentazione del pi2 e quindi ho comprato, da amazon, un nuovo alimentatore da 3Ampere dato per adatto e perfetto per lavorare su un Pi3B (un 3.5A).
Appena ho cambiato e sono passato a questo nuovo alimentatore tutti i freeze che causava l'emulazione sono scomparsi......

Quando io notavo questi freeze e andavo a staccare e riattaccare fisicamente il mio Pi2 dalla spina di corrente al riavvio andavo appunto a controllare il kodi.old.log per vedere se quest'ultimo presentasse qualche suggerimento del crash senza trovare nulla.
Scorrendo appunto il log ho notato tutte queste informazioni di kod che non avevo mai notato prima e da li ho pensato che magari qualche dettaglio di debug sul mio Pi2 si fosse attivato per sbaglio e che la cosa aggiunta all'emulazione mandasse in crisi la CPU creando i freeze ancora prima di effettuare il cambio dell'alimentatore.

Ora col nuovo alimentatore come detto i freeze mentre sono in retrogaming sono scomparsi anche se l'altra sera mi si è frizzato tutto mentre stavo guardando un film........... li per li ci sono rimasto di merda perchè appunto pensavo di aver risolto con l'alimentatore nuovo ma cavoli stavolta il mio caro (e vecchio di anni ormai addirittura) Pi2 s'è frizzato dopo quasi una settimana di utilizzo continuo e non mi sono preoccupato. Anche in questo caso al riavvio sono andato a vedere il kodi.old.log che era di svariati mega (e cavoli dopo una settimana continua ci può anche stare) e anche li tutte quelle informazioni relative al kod..... e appunto la cosa che qualcosa di debug mi fosse attivato...... ho anche pensato che la configurazione di kod stessa si fosse in qualche modo corrotta sul mio pi2 che ne so :)

Non so se mi sono spiegato............. se avete qualche suggerimento da darmi addirittura in merito a questa mia esperienza sono aperto a tutto.
Oh per assurdo ho anche pensato che la mia SD e la mia installazione vecchia di anni magari è iniziata a corrompersi.... ci sta pure questo per assurdo. Potrebbe anche essere il recente update di osmc basato sul nuovo kernel buster che ogni tanto va fuori di melone però che dire col vecchio alimentatore da 2A freezava appena andavo ad utilizzare il gamepad... col nuovo ora almeno gioco per ore (e bestemmio maledetto solomon key per esempio) e se ogni tanto freeza magari ci sta pure (per assurdo mi dicevano sul forum stesso di osmc che qualche emulatore è maledettamente rotto e col tempo possono creare freeze e bug di ogni tipo.... mi suggeriscono di fare un setup col retropie ma dovrei appunto prendere una seconda sd e cambiare la stessa mentre quando ho voglia di retrogame ora attaco il gamepad apro e via.... bestemmie... maledetto super mario). Lol.
