### ISSUE TITLE
Canale ilcorsaronero irraggiungibile

### ISSUE THREAD

**Issue by an2791ch** [Stream4me/addon#250]
Salve

Quando eseguo una ricerca su questo canale:

ilcorsaronero

ricevo questo errore:

_Canale il corsaronero irraggiungibile, il sito sembra non essere disponibile......_

in realtà il sito è disponibile.

Grazie

**Comment by mac12m99** [comment]
Salve,
a me funziona, sei sicuro di non aver proprio beccato quei 2 minuti in cui non era raggiungibile? Riprova per favore, se non funziona assicurati di avere l'override DNS attivo dalle impostazioni di KoD

**Comment by an2791ch** [comment]
Salve
Ho provato diverse volte e continua a non funzionare sempre con lo stesso
messaggio di errore, ho inoltre verificato l'override DNS ed è attivo.
KODI è installato su 2 diversi dispositivi e da entrambi ho lo stesso
comportamento ( KODI 18.9 - KOD 1.5)

Saluti



Il giorno mar 8 dic 2020 alle ore 16:11 mac12m99 <notifications@github.com>
ha scritto:

**Comment by mac12m99** [comment]
Risolto con 1c623ad47a4af399742ea40354201a0567501ee1, abbiamo inserito direttamente il link senza passare per la gazzetta (che dovrebbe pubblicare il link sempre aggiornato ma è offline da parecchio)
