### ISSUE TITLE
Richiesta (?)

### ISSUE THREAD

**Issue by GoshiGoshiro** [Stream4me/addon#251]
Non si può aggiungere HentaiWorld nella sezione Anime?

**Comment by mac12m99** [comment]
Ciao,
purtroppo non siamo interessati a quel sito, anche perchè non basta "aggiungerlo"(creare uno [scraper](https://it.wikipedia.org/wiki/Web_scraping)) ma bisogna anche mantenerlo (aggiornarlo quando viene cambiata la sua struttura).
Nulla vieta però che qualche sviluppatore esterno lo aggiunga e lo tenga aggiornato..
