### ISSUE TITLE
La riproduzione non va dopo l'aggiornamento alla 1.5.1

### ISSUE THREAD

**Issue by luX0r-reload** [Stream4me/addon#252]
Ciao, come da oggetto, dopo l'aggiornamento non va più nessun playback.
Riesco a sfogliare server e canali ma al momento del playback si pianta tutto e devo spegnere il box.

LibreELEC, Kodi 18.6.

Ho provato a disinstallare tutto (tranne le impostazioni) e a reinstallare... stesso problema.
Devo cancellare ache le impostazioni quando disinstallo?

**Comment by mac12m99** [comment]
Ciao,
è stato appena rilasciato un fix che dovrebbe risolvere, per favore avvia kodi, assicurati di ricevere l'aggiornamento e riprova.

**Comment by luX0r-reload** [comment]
Ciao, grazie mille per il fix! Ora funziona.
