### ISSUE TITLE
Risultati ricerca invisibili con skin Xperience1080

### ISSUE THREAD

**Issue by andreacc81** [Stream4me/addon#253]
Utilizzando la skin in oggetto i risultati della ricerca presentano tutti i testi invisibili, pertanto è impossibile capire cosa viene trovato o cosa si sta selezionando. Come è visibile dall'immagine si vede a malapena un riquadro di selezione e niente altro
![IMG_20201219_170648](https://user-images.githubusercontent.com/60221763/102693680-a7ffaa80-421c-11eb-8b89-ea24a859a4ed.jpg)

**Comment by mac12m99** [comment]
Ciao,
il problema dovrebbe essere risolto, potresti riprovare?
