### ISSUE TITLE
Integrazione OpenMeta

### ISSUE THREAD

**Issue by iannuz92** [Stream4me/addon#254]
Ciao ragazzi, vi ringrazio in anticipo per l'ottimo lavoro svolto.
Volevo proporvi una richiesta, c'è modo di includere KOD come player in OpenMeta?
Vi lascio la documentazione per creare/modificare un player in OpenMeta da un addon

https://github.com/a4k-openproject/plugin.video.openmeta/wiki/Writing-an-OpenMeta-player

Grazie

**Comment by mac12m99** [comment]
Ciao,
non avevo mai sentito quest'addon, ho dato un'cchiata al suo github e sembra abbandonato, inoltre noto che non supporta il futuro kodi 19, confermi?

Se è un addon abbandonato non credo ne valga la pena, ma nulla ti vieta di provare a farlo tu, noi ti possiamo spiegare come richiamare le funzioni dell'addon.
