### ISSUE TITLE
domanda generale

### ISSUE THREAD

**Issue by aandroide** [Stream4me/addon#256]
ciao, esiste un metodo per effettuare la ricerca e la riproduzione tramite "http://IP-ADDRESS-OF-KODI:8080/jsonrpc", "username", "password"?

**Comment by aandroide** [comment]
pensavo di utilizzare un comando tipo questo ma non conosco i parametri giusti per concatenare il tutto:
kodi.Player.open(item={"file":"plugin://plugin.video.kod/?action=play_video&videoid=" + search_urlid})

**Comment by mac12m99** [comment]
Ciao, mi pare di capire che ti interessa sapere come vengono creati gli url che rimandano alle funzioni dell'addon, giusto?
Si tratta di json codificati in base64, se conosci un po' di programmazione leggendo [launcher.py](https://github.com/kodiondemand/addon/blob/master/platformcode/launcher.py) sarai in grado di craftare URL per ogni sezione o funzione dell'addon

Alcuni esempi (passali su https://www.base64decode.org per vedere il contenuto):
Cerca per Titolo: plugin://plugin.video.kod/?eyJhY3Rpb24iOiJTZWFyY2giLCJjaGFubmVsIjoiZ2xvYmFsc2VhcmNoIiwiZm9sZGVyIjpmYWxzZSwibW9kZSI6ImFsbCJ9
Cerca Film: plugin://plugin.video.kod/?eyJhY3Rpb24iOiJTZWFyY2giLCJjaGFubmVsIjoiZ2xvYmFsc2VhcmNoIiwiZm9sZGVyIjpmYWxzZSwibW9kZSI6ICJtb3ZpZSJ9
Cerca Serie TV: plugin://plugin.video.kod/?eyJhY3Rpb24iOiJTZWFyY2giLCJjaGFubmVsIjogImdsb2JhbHNlYXJjaCIsImZvbGRlciI6IGZhbHNlLCJtb2RlIjogInR2c2hvdyJ9
Cerca Attori/Attrici: plugin://plugin.video.kod/?eyJhY3Rpb24iOiAiU2VhcmNoIiwiY2hhbm5lbCI6Imdsb2JhbHNlYXJjaCIsImZvbGRlciI6IGZhbHNlLCJtb2RlIjogInBlcnNvbiIsInBhZ2UiOjF9

Per permettere una facile integrazione puoi aggiungere altri parametri in get nel formato classico, ad esempio aggiungendo alle stringhe di prima
&text=film
è come se avessi digitato "film"
Una volta craftata la stringa puoi usare jsonrpc per eseguirla in remoto.

**Comment by aandroide** [comment]
ciao, in realtà il mio scopo è questo:
utilizzo l'assistente google installato su un raspberry dove ho creato parecchie funzioni personalizzate tra le quali anche quella di cercare video da youtube e riprodurli su kodi che è installato sulla tv.
il mio obiettivo sarebbe di chiedere a google di cercare il film e riprodurlo su kodi e quindi avevo pensato di creare una variabile per la ricerca dei film . in realtà non voglio scoprire la url, ma fare in modo che il titolo che dico vocalmente venga ricercato dando quel comando get con json.
Spero di aver chiarito al meglio il concetto.
quindi da quello che ho capito, se sto cercando un film, non devo passare il comando get cosi: plugin://plugin.video.kod/?"titolo del film"
ma cosi'? : plugin://plugin.video.kod/?eyJhY3Rpb24iOiJTZWFyY2giLCJjaGFubmVsIjoiZ2xvYmFsc2VhcmNoIiwiZm9sZGVyIjpmYWxzZSwibW9kZSI6ICJtb3ZpZSJ9 "titolo del film"

**Comment by aandroide** [comment]
kodi.Player.open(item={"file":"plugin://plugin.video.kod/?action=Search+channel+globalsearch+folder=false+mode=movie&text=film"})
o dovrebbe essere cosi'? ho decodificato cerca film

**Comment by aandroide** [comment]
sembra esserci un'errore nell'esecuzione della ricerca. aprendo il mio server su localhost:8080 e aprendo l'addon kodi on demand, vedo le cartelle quindi apro l'addon, vado su cerca film e sulla tv vedo apparire la tastiera per comporre il testo da cercare, ma quando si preme invia la rotella gira all'infinito senza nessun risultato. funziona bene se do il comando dalla tv ma non da localhost di conseguenza non puo' funzionare nemmeno il richiamo via json.

**Comment by mac12m99** [comment]
Ho fatto qualche prova, in effetti la nuova ricerca globale non sembra funzionare in quanto kodi si aspetta che venga ritornata una lista standard, è comunque possibile forzare l'utilizzo di quella vecchia:
{
    "jsonrpc": "2.0",
    "method": "Addons.ExecuteAddon",
    "params": {
        "addonid": "plugin.video.kod",
        "params": "?ewogICJhY3Rpb24iOiAibmV3X3NlYXJjaCIsCiAgImNoYW5uZWwiOiAic2VhcmNoIiwKICAiZm9sZGVyIjogZmFsc2UsCiAgImluZm9MYWJlbHMiOiB7fSwKICAibW9kZSI6ICJtb3ZpZSIKfQ==&search_text=blabla"
    },
    "id": 1
}


Il JSON come puoi vedere è fatto in questo modo:
{
  "action": "new_search",
  "channel": "search",
  "folder": false,
  "infoLabels": {},
  "mode": "movie"
}

Naturalmente search_text dev'essere urlencoded, se stai programmando qualcosa te ti conviene semplicemente includerlo nel json e poi convertire il tutto in base64

**Comment by aandroide** [comment]
ok sto cercando di imparare porta pazienza,
ho provato cosi:
kodi.Player.open(item={"file":"plugin://plugin.video.kod/?ewoiYWN0aW9uIjogIm5ld19zZWFyY2giLAoiY2hhbm5lbCI6ICJzZWFyY2giLAoiZm9sZGVyIjogZmFsc2UsCiJpbmZvTGFiZWxzIjoge30sCiJtb2RlIjogIm1vdmllIgomc2VhcmNoX3RleHQ9Cn0=titolo,id=1"})
ma non funziona ancora.
anche il titolo e id1 devono essere convertiti in base 64?
ti ringrazio per la tua pazienza

**Comment by mac12m99** [comment]
Non ho idea di cosa sia la funzione "kodi.Player.open" se non mi spieghi che linguaggio/librerie hai intenzione di usare..
Ti posso solo dire che il json da passare a jsonrpc dev'essere fatto in quel modo.

Comunque sulla beta il problema è stato fixato, ora puoi usare anche la nuova ricerca :)

Questa è la richiesta che sto facendo per testare:
![image](https://user-images.githubusercontent.com/10120390/104818539-80eec580-5828-11eb-9f17-7fd8d537d910.png)
(solo il json che passi a KoD è in base64)

**Comment by aandroide** [comment]
sto programmando il tutto in python.
che programma usi per inviare i test json?

**Comment by aandroide** [comment]
sto usando questo progetto dove puoi vedere come viene richiamata la funzione per youtube https://github.com/shivasiddharth/GassistPi/blob/master/src/actions.py#L571

**Comment by aandroide** [comment]
credo che il mio errore sia proprio aver usato kodi.Player.open perchè quella funzione apre solo il player non crea la struttura json.
sto cercando qual'è la funzione corretta via python

**Comment by mac12m99** [comment]
Per fare le richieste uso https://www.postman.com
Con python basterebbe usare requests, comunque vedo che utilizza questo wrapper per semplificare le cose: https://github.com/jcsaaddupuy/python-kodijson
Ad occhio la chiamata giusta dovrebbe essere qualcosa tipo kodi.Addons.ExecuteAddon

**Comment by aandroide** [comment]
ho scoperto il problema non avevo letto bene che avevi corretto la beta, quindi adesso ho scaricato il file zip da github installato sulla tv ed il comando ha funzionato con : kodi.Player.open(item={"file":"plugin://plugin.video.kod/?eyJhY3Rpb24iOiJTZWFyY2giLCJjaGFubmVsIjoiZ2xvYmFsc2VhcmNoIiwiZm9sZGVyIjpmYWxzZSwibW9kZSI6ICJtb3ZpZSJ9&text=tenet"}) 
adesso mi rimane da capire:
 come far avviare la riproduzione di quel titolo automaticamente?

**Comment by mac12m99** [comment]
Ottimo, tuttavia riprodurre titoli automaticamente non è possibile al momento, la cosa che ci si avvicina di più è [l'autoplay](https://github.com/kodiondemand/addon/wiki/Riproduzione) che però funziona solo per i server e non per i canali.
Scegliere in automatico la fonte migliore senza andare a caso non è così semplice, inoltre far partire un contenuto direttamente senza interazione porta con se alcuni problemi:
- il server scelto può anche essere il migliore ma magari in quel momento non riesce a reggere e quindi sei costretto ad agire manualmente, cambiandolo
- il canale scelto potrebbe contenere una versione più scarsa di altri (CAM vs BDRIP) nonostante abbia una risoluzione migliore
- alcuni canali a volte mentono sulla qualità, e a volte inseriscono titoli non esistenti facendoli puntare a video che ti dicono "registrati per ricevere una notifica quando sarà disponibile!"
- In caso di più scelte, magari per omonimia, come fai? Dovresti sviluppare un sistema che ti chieda quale vuoi vedere

Per tutte queste ragioni, nonostante è da parecchio che ci pensiamo, non abbiamo mai fatto niente di simile perchè consapevoli che a meno di investire parecchio tempo al riguardo, sarebbe scarsamente efficace.

**Comment by aandroide** [comment]
ciao, grazie per la risposta.
Effettivamente ci avevo pensato anche io a questi passaggi un po' complicati da fare.
Una parte di possibile soluzione  per i problemi sopracitati, potrebbe essere di specificare in un file config.yaml, indirizzo ip, porta, user e password e a questo punto aggiungere anche una voce "canale di ricerca" che potrebbe essere per esempio "il genio dello streaming" o il canale che l'utente ritiene più affidabile, dove si ha già una certa certezza di non incorrere in problemi tipo il punto 3 che hai citato.
quindi se nel mio script che lavora già in yaml per quanto riguarda la configurazione, aggiungessi anche in quale canale deve effettuare la ricerca, è poi possibile inviarlo tramite json e poi richiamare l'autoplay ?

**Comment by aandroide** [comment]
per esempio non è chiaro se questo progetto: https://github.com/OmerTu/GoogleHomeKodi#what-it-can-do possa controllare anche i film da addon esterni o soltanto quelli che si hanno in libreria.

**Comment by mac12m99** [comment]
Utilizzare un solo canale riduce la quantità di contenuti cercabili ma si, è fattibile.
Dovresti chiamare la funzione di ricerca del singolo canale e poi fargli selezionare il primo risultato (o altri, ed è qui il difficile), ovviamente con l'autoplay abilitato.

La chiamata da fare è questa:
{"action": "search", "channel": "ilgeniodellostreaming"}
tuttavia non è previsto alcun parametro per specificare già il testo di ricerca (ma si può aggiungere, e comunque lo puoi far inserire te con jsonrpc)

**Comment by aandroide** [comment]
grazie per le tue pronte risposte, purtroppo và un po' oltre le mie capacità di programmazione.
Chiudo questo problema dal momento che non lo è mai stato, e spero che in futuro ci sarà la possibilità di poterlo fare.
Grazie per le dritte.
