### ISSUE TITLE
Rai Play

### ISSUE THREAD

**Issue by Gythion** [Stream4me/addon#259]
Non si aprono i Film nella sezione A-Z, neanche su "Apri browser". https://is.gd/PD1N4w

**Comment by mac12m99** [comment]
Ciao,
grazie della segnalazione, dovrebbe essere risolto con d2ca99c7fc9368c6f97cfb43ff9e56c1d7add7eb.
Ho fatto però altre modifiche, riusciresti a testare se tutto funziona come dovrebbe? Grazie

Il fix è per ora solo sulla beta (puoi provarla re-installando l'addon senza disinstallare e scegliendo il ramo master), se mi dai l'ok lo passo sulla stabile

**Comment by Gythion** [comment]
Apposto
