### ISSUE TITLE
Aggiungere Siti 

### ISSUE THREAD

**Issue by kakaizecson2003** [Stream4me/addon#26]
[Siti Streaming 2019-05-07_14-13-21.txt](https://github.com/kodiondemand/addon/files/3152587/Siti.Streaming.2019-05-07_14-13-21.txt)

**Comment by cttynul** [comment]
SerieTVOnline è già presente, per l'altro ci lavoreremo, grazie per la segnalazione.

**Comment by greko17** [comment]
oggi, ma non so da quanto...il sito: 
http://fattoneserialestreaming.net
non risulta esserci più...
