### ISSUE TITLE
Secondi prima della notifica non più funzionanti

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#262]
Salve,
Ho aspettato parecchio prima di aprire questo issue ma da circa poco meno di un mese non funziona più come da titolo nonostante io non abbia cambiato nessun impostazione sin dalla prima configurazione.
Appena mi accorsi di questa notifica,quando arrivato al termine di un filmato, sono rimasto piacevolmente sorpreso,alchè sono andato ad aumentare i secondi di essa per passare al successivo direttamente ai titoli di coda.
Funzionò tutto alla grande e anche per parecchi filmati, poi tutto d'uno tratto, nonostante le impostazioni sono rimasye tali, non notifica più...
uso la skin aeon silvo ed ha sempre funzionato con essa...
Ho provato a rientrare nel canale telegram, ma dice che non è più accessibile...
Mi sto perdendo qualcosa?
In attesa di un riscontro positivo porgo cordiali saluti

**Comment by mac12m99** [comment]
Salve,
trattasi della funzione [Episodio successivo](https://github.com/kodiondemand/addon/wiki/Episodio-successivo), può essere che l'hai disattivata per sbaglio? Controlla e assicurati di star usando la videoteca

Se comunque non funzionasse recati in aiuto -> segnala un problema, segui le istruzioni (riprovando quando richiesto a guardare una puntata, per poi spostarti alla fine e attendendo la notifica) e pubblica qui il link che ti genera

**Comment by omgfrost** [comment]
![Screenshot_20210129-211225_Kodi](https://user-images.githubusercontent.com/14861120/106322918-dbe7da00-6276-11eb-961e-c15891ec8b13.png)
È sempre stato così...sempre funzionante.
Se non basta e avete bisogno dei log, proverò domani..da cell è un pò difficile gestire tutto, anche perchè sono a letto ora a guardare la serie tv per poi dormire.
Fatemi sapere se nella schermata sopra cè qualcosa di anomalo,grazie
PS: siccome da quando mi hanno detto che i titoli degli episodi sono solo in libreria ho sempre usato quella poi.
Ma ora per scrupolo ho provato da videoteca e niente, la notifica per ep successivo non appare..

**Comment by omgfrost** [comment]
https://ufile.io/8mmoah80

**Comment by mac12m99** [comment]
Grazie,
ho identificato il punto in cui pare bloccarsi ma non mi è chiaro il motivo, potresti mandarmi il file kod_db.sqlite che trovi in .kodi/userdata/addon_data/plugin.video.kod/?
Magari prova anche a rinominarlo temporaneamente e riprovare (l'addon ne creerà uno nuovo), sospetto abbia qualcosa che non va.

**Comment by omgfrost** [comment]
Fatto, rinominato in .bak e rifatta subito la prova, il problema rimane , invio entrambi
https://file.io/i9JRwOMu84Kw nuovo
https://ufile.io/g7mpn0qs vecchio

**Comment by mac12m99** [comment]
Il link di quello nuovo è scaduto, ma comunque non è un problema.
Ho aggiunto Servant da guardaserieclick e utilizzato il tuo db vecchio, funziona anche sulla stabile..
A questo punto mi viene da pensare proprio alla videoteca, manda per favore anche /.kodi/userdata/addon_data/plugin.video.kod/videolibrary/Serie TV/Servant

**Comment by omgfrost** [comment]
Ma non è che ci fà solo con Servant, non appare in nessun filamato. Ho utilizzato Servant perchè era l ultimo ep. Che ho guardato.
https://ufile.io/6lmwa1sw

**Comment by omgfrost** [comment]
UPDATE: Ho appena provato sul cell di mia madre che ha solo dark come serie tv e anche dalla videolibrary la notifica funziona.
Ho riprovato sul mio sempre con dark e non appare neanche li.
Quindi non credo dipenda da una specifica serie tv.
Se volete qualche file dal cell di mia madre fatemelo sapere. Grazie
Saluti, per ora

**Comment by omgfrost** [comment]
Bump please

**Comment by mac12m99** [comment]
Qualcosa per rendere quel codice meno propenso ad errori è stato fatto, anche se non sono sicuro che risolva il tuo problema specifico, puoi provare ad installare la beta?
Reinstalla senza disinstallare e scegli il ramo master

**Comment by omgfrost** [comment]
> Qualcosa per rendere quel codice meno propenso ad errori è stato fatto, anche se non sono sicuro che risolva il tuo problema specifico, puoi provare ad installare la beta?
> Reinstalla senza disinstallare e scegli il ramo master

Scusa la mia ignoranza nonostante sia nell' IT, ma io ho installato tramite repo link inserito come source in kodi, parecchio tempo fà. Ora, dove trovo la beta? Riguardo nel repo link o qui su github? Sono andato qui in releases ma non ho trovato beta :| 
Un aiutino? :=

**Comment by omgfrost** [comment]
![Screenshot_20210131-135900_Kodi](https://user-images.githubusercontent.com/14861120/106384715-92a99e80-63cc-11eb-8d1c-fa74a05b7bdf.png)
Qui cè solo l installer...

**Comment by Alhaziel01** [comment]
@omgfrost usa l'installer, ti chiederà quale versione scegliere.

**Comment by omgfrost** [comment]
> @omgfrost usa l'installer, ti chiederà quale versione scegliere.
![Screenshot_20210131-141649_Kodi](https://user-images.githubusercontent.com/14861120/106385178-25e3d380-63cf-11eb-8232-183a9371437a.png)

GRAZIEEEEEEEE!SIETE MAGNIFICI!

**Comment by mac12m99** [comment]
Prego :)
verrà passato sulla stabile con la prossima versione, nel frattempo puoi usare la beta ma sappi che è da considerarsi instabile per definizione, consiglio di tornare alla stabile non appena verrà rilasciato.

**Comment by omgfrost** [comment]
> Prego :)
> verrà passato sulla stabile con la prossima versione, nel frattempo puoi usare la beta ma sappi che è da considerarsi instabile per definizione, consiglio di tornare alla stabile non appena verrà rilasciato.

Scusa la "riapertura" ma ho notato una cosa subito dopo aver installato la beta sul mio galaxy s6.
Quando sono andato a ruotare lo schermo da normale a landscape non ruotava piu'. Spento e riacceso, lo stesso.
Praticamente ora devo ricalibrare il sensore facendogli fare una rotazione a 8 in aria tenendolo con la mano e li' si ruota in landscape. Ma se premo il pulsante power (per mandarlo in stand-by) alla riapertura la rotazione, anche se sempre abilitata, non funziona ancora e mi ritocca fare tutta la procedura di sopra...potrebbe essere la beta di kodi?
Grazie ancora

**Comment by mac12m99** [comment]
Non credo proprio, dev'essere qualcosa del telefono...

**Comment by omgfrost** [comment]
> Non credo proprio, dev'essere qualcosa del telefono...

E invece questa volta credi male :p
Reinstallata sopra la stable rifunziona la notifica e ho appena provato la rotazione e ruotato subito, cosa che prima facevo i salti mortali per roteare.
Non si finisce mai d'imparare :=
