### ISSUE TITLE
VVVVID

### ISSUE THREAD

**Issue by luX0r-reload** [Stream4me/addon#265]
Ciao. Da qualche giorno i contenuti del canale VVVVID hanno smesso di funzionare sul mio box android con LibreElec. Quando vado in play non arriva alla fase di buffering... è come se lo scraper si "impalli" al punto tale da mandare Kodi in freeze. Per spegnere il box devo staccarlo dalla corrente.

Lo stesso canale sul PC funziona benissimo. Potrebbe dipendere dalla velocità del dispositivo... in passato sono stati applicati già dei fix per i dispositivi "lenti".

Grazie mille

**Comment by mac12m99** [comment]
Ciao,
mi spiace ma non abbiamo nessuna idea.. Se il problema persiste ancora riapri e manda [un log](https://telegra.ph/LOG-11-20)
