### ISSUE TITLE
Rai Play

### ISSUE THREAD

**Issue by Gythion** [Stream4me/addon#266]
Stesso problema dell'issue #259

**Comment by Alhaziel01** [comment]
@Gythion è appena stato fixato sulla beta...

**Comment by mac12m99** [comment]
Il fix è stato mandato sulla stabile più di 10 giorni fa..
Ancora non ti funziona?

**Comment by Gythion** [comment]
Non ci siamo capiti, ho avuto di nuovo lo stesso errore.
