### ISSUE TITLE
Informazioni errate e titolo errato di alcuni film TMDB

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#267]
Alcuni film vengono visualizzati con informazioni errate, di conseguenza una volta aggiunte alla videoteca titolo e trama vengono modificate e aggiunte in modo errato, per esempio se su altadefinizione.click cerchiamo e proviamo aggiungere 
Jurassic Park 3 le informazioni sono errate e il titolo come detto prima viene modificato, probabilmente questo è dovuto dal fatto che non vi è riscontro con il titolo su TMDB visto che il titolo corretto è Jurassic Park III, purtroppo non è la prima volta che questo problema si presenta e mi è capitato anche con altri film, spero ci sia la possibilità di correggere questo problema o la possibilità futura di inserire manualmente le informazioni corrette o poterle modificare.

![screenshot000](https://user-images.githubusercontent.com/53865707/107077709-8cad2680-67ed-11eb-83be-ac51c372fbb1.png)

![screenshot001](https://user-images.githubusercontent.com/53865707/107077897-cc740e00-67ed-11eb-9539-d5948b0da709.png)

**Comment by mac12m99** [comment]
Buonasera,
si siamo a conoscenza ciò, i siti sono fondamentalmente inaffidabili pertanto si cerca di fare quel che si può..
Ho però avuto un idea che forse riesce a gestire gli errori "semplici" come questo, riesci ad elencare tutti i casi che ricordi? (sia il titolo messo dal sito, sia quello che indica tmdb)

**Comment by mac12m99** [comment]
Risolto con a180136f8ccc9fc0fe373c7c3774aa18ade4688c, lo proviamo un po' e se funziona bene la modifica verrà inclusa nella prossima release.
Puoi testare sulla beta

**Comment by xXTimmy89Xx** [comment]
> Risolto con [a180136](https://github.com/kodiondemand/addon/commit/a180136f8ccc9fc0fe373c7c3774aa18ade4688c), lo proviamo un po' e se funziona bene la modifica verrà inclusa nella prossima release.
> Puoi testare sulla beta

Buon pomeriggio, stavo testando il fix in questione ma ho notato che purtroppo se provo ad aggiungere un film alla videoteca in questo caso Jurassic park sempre da altadefinizione.click l'azione viene interrotta istantaneamente non andando a buon fine e comparendo semplicemente l'errore allegato, stessa cosa con Jurassic park 3 e altri titoli.

![screenshot000](https://user-images.githubusercontent.com/53865707/107384148-f9783780-6af1-11eb-97d2-cdbf4c3ba3c8.png)

**Comment by mac12m99** [comment]
Buona sera,
purtroppo stavo testando su kodi 19 RC1 data l'imminente uscita, quel fix ha però causato problemi sul 18 :D
Ora dovrebbe essere a posto, riavvia kodi (sempre con la beta dell'addon) e dimmi se funziona :)

**Comment by xXTimmy89Xx** [comment]
> Buona sera,
> purtroppo stavo testando su kodi 19 RC1 data l'imminente uscita, quel fix ha però causato problemi sul 18 :D
> Ora dovrebbe essere a posto, riavvia kodi (sempre con la beta dell'addon) e dimmi se funziona :)

Dopo aver effettuato un istallazione pulita su Windows con la versione 18.9 ho riscontato i seguenti problemi, dopo l'installazione sia della stabile che della versione beta alla richiesta di configurazione della videoteca si riceve il seguente errore 

![screenshot000](https://user-images.githubusercontent.com/53865707/107419400-0c056780-6b18-11eb-835e-2ce4a3eafe9a.png)

![screenshot002](https://user-images.githubusercontent.com/53865707/107419426-1293df00-6b18-11eb-9552-31d16b2520b7.png)

Che fortunatamente può essere nuovamente configurato al primo avvio della versione stabile, nella beta ho notato che il fix sembra funzionare o meglio le informazioni nella videoteca sono corrette, purtroppo non posso verificare nella libreria di kodi perché ho notato che all'avvio di Kodi la videoteca di KoD non viene più sincronizzata con la libreria di Kodi e nei file log si presenta il seguente errore: 
2021-02-09 21:02:29.942 T:13632   ERROR: XFILE::CFile::Delete - Error deleting file C:\Users\Timmy89\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.kod\kod_db.sqlite
2021-02-09 21:02:29.942 T:13632   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such table: viewed
                                            Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\service.py", line 463, in <module>
                                                old_db.execute('select * from viewed')
                                            OperationalError: no such table: viewed
                                            -->End of Python script error report<--

Dopo test ho notato che problema della sincronizzazione videoteca e libreria non si presenta su Kodi 19 ma solo sulla 18.9 e il fix sulla 19 sembra funzionare la maggior parte delle volte, ho riscontrato un altro piccolo problemino però se io provo ad aggiungere il film l'incredibile hulk 2008 nonostante mi venga chiesto di scegliere le informazioni e io in entrambi i casi selezioni il film del 2008 nella videoteca le informazioni risultano corrette mentre nella libreria di kodi vengono visualizzate le informazioni del film della versione del 1997 nonostante abbia selezionato la versione corretta.

![screenshot00001](https://user-images.githubusercontent.com/53865707/107423456-9c45ab80-6b1c-11eb-9891-d405c30544c4.png)

![screenshot00002](https://user-images.githubusercontent.com/53865707/107423471-a071c900-6b1c-11eb-93c9-142412674498.png)

![screenshot00003](https://user-images.githubusercontent.com/53865707/107423552-bda69780-6b1c-11eb-8ada-e1b052c7a9f2.png)

![screenshot00004](https://user-images.githubusercontent.com/53865707/107423560-c13a1e80-6b1c-11eb-9198-8dcba4f4cc1a.png)

**Comment by mac12m99** [comment]
Grazie dei test approfonditi, purtroppo sei incappato in altre modifiche non testate a fondo (sulla beta è così d'altronde), ti faccio sapere non appena ho qualcosa.

**Comment by mac12m99** [comment]
Ciao,
I problemi che hai riportato nella prima parte dovrebbero essere risolti, per quanto riguarda Hulk sospettiamo sia lo scraper di kodi che sbagli perchè nella sezione videoteca di KoD viene riportato correttamente ed in tutti i file che vengono salvati l'id tmdb si riferisce al film del 2008...

**Comment by xXTimmy89Xx** [comment]
> Ciao,
> I problemi che hai riportato nella prima parte dovrebbero essere risolti, per quanto riguarda Hulk sospettiamo sia lo scraper di kodi che sbagli perchè nella sezione videoteca di KoD viene riportato correttamente ed in tutti i file che vengono salvati l'id tmdb si riferisce al film del 2008...

Buon pomeriggio, dopo aver effettuato i test sia sulla versione 18,9 che sulla 19 confermo che con la versione beta il problema è stato risolto, pertanto ti ringrazio per l'ottimo lavoro svolto anche se rimane presente l'errore della configurazione della videoteca al primo setup sia nella versione stabile che nella versione beta.
