### ISSUE TITLE
Raised by Wolves Ita schermo di ricerca grigio

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#268]
![Screenshot_20210209-205528_Kodi](https://user-images.githubusercontent.com/14861120/107420625-6226da80-6b19-11eb-87b8-e18fc476f4b6.png)
Salve,
Cosa faccio?
Con le altre tutto ok

**Comment by omgfrost** [comment]
Update. Forse non indicizza il titolo ita perchè la tastiera di kod non permette la à di umanità.
Ho fatto ricerca per titolo e scritto umanita e i risultati appaiono

**Comment by omgfrost** [comment]
Bump pls

**Comment by Alhaziel01** [comment]
@omgfrost

Ho provato, a me lo trova...

**Comment by omgfrost** [comment]
![Screenshot_20210211-210233_Kodi](https://user-images.githubusercontent.com/14861120/107692115-a3032880-6cac-11eb-98bb-534c6b66f1dc.png)
Fatto di nuovo anche dal cell di mia madre e la screen è il risultato.
Io scrivo "Raised by wolves" senza virgolette nella ricerca serie tv...
Qualche suggerimento?
Grazie

**Comment by Alhaziel01** [comment]
Cerca per titolo e non per serie...

La ricerca per serie è più precisa, ma può saltare qualche risultato.

**Comment by omgfrost** [comment]
> Cerca per titolo e non per serie...
> 
> La ricerca per serie è più precisa, ma può saltare qualche risultato.

Si infatti per titolo appaiono...ma io ho sempre usato la ricerca per serie tv e sono sempre apparsi...
Vabbè se fixerete questo commit in qualche modo sarebbe una svolta, altrimenti potete chiudere.
Grazie del supporto

**Comment by mac12m99** [comment]
Avviso che sulla beta sono state fatte delle modifiche che dovrebbero rendere la ricerca in grado di gestire casi come questi

**Comment by omgfrost** [comment]
> Avviso che sulla beta sono state fatte delle modifiche che dovrebbero rendere la ricerca in grado di gestire casi come questi

Ah ok grazie dell'heads up, ma per ora mi basta la stable con ricerca con titolo invece che come serie tv.
Con titolo sembra trovare di piu'.
Non installo la beta soltanto per questa serie che posso trovare come sopra, la beta mi ha dato altri problemi di ricerca e non apertura server e\o anche di crash quando l'avevo installata sopra la prima volta.
Quindi ok così.
Grazie.
