### ISSUE TITLE
KOD ON DEMAND

### ISSUE THREAD

**Issue by GregoraceGiuseppe** [Stream4me/addon#270]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Inserisci il nome del canale
KOD ON DEMAND

- Il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore

Es. non riesco ad aggiungere film nella videoteca, ne dal menu contestuale, ne dalla voce in fondo alla lista dei server.

Se faccio ricerca globale, non riesco ad aggiungere film/serie/anime nella videoteca o a scaricare il video.

- Allega il file di log nella sua completezza. Non cancellarne delle parti.
[plugin.video.elementum-0.1.62.windows_x64.zip](https://github.com/kodiondemand/addon/files/5977628/plugin.video.elementum-0.1.62.windows_x64.zip)

**Comment by mac12m99** [comment]
per canali si intende cb01, eurostreaming ecc.. non kodi on demand (che hai pure sbagliato a scrivere)
Perchè hai allegato l'addon elementum come fosse un file di log?
Cosa succede quando provi ad aggiungere in videoteca? Ti esce errore o non accade niente?

Per favore, cerca di fare di una segnalazione comprensibile, portando magari degli esempi.

Leggi anche qui per il log
https://telegra.ph/LOG-11-20

PS
ho chiuso l'altro issue perchè duplicato.

**Comment by GregoraceGiuseppe** [comment]
Chiedo scusa per la mia risposta non sono molto esperto in materia e
raramente uso i forum come github

Il Mer 17 Feb 2021, 21:08 mac12m99 <notifications@github.com> ha scritto:
