### ISSUE TITLE
Mediaset play problema numerazione di alcune serie tv

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#271]
Ho notato che su Mediaset play alcune serie tv hanno una numerazione errata, prendiamo per esempio il caso della serie Daydreamer una volta selezionata la serie in questione se andiamo su episodi possiamo notare che la numerazione e l'ordine degli episodi sono errati questo potrebbe essere dovuto anche dal fatto che alcuni episodi sono divisi in prima e seconda parte .

![screenshot001](https://user-images.githubusercontent.com/53865707/107893255-67759200-6f2a-11eb-8330-2a5f431d01b5.png)

![screenshot000](https://user-images.githubusercontent.com/53865707/107893259-6a708280-6f2a-11eb-90df-24abe9354bc6.png)

**Comment by xXTimmy89Xx** [comment]
Dopo l'aggiornamento "Fix Mediaset (Rimossa Numerazione)" il problema in parte sembra essere stato risolto ma ora mancano alcuni episodi, possiamo notare che ora gli episodi partono dall'episodio 40 e mancano tutti gli episodi da 1 a 39 mi sto sempre riferendo alla serie Daydreamer. 

![screenshot000](https://user-images.githubusercontent.com/53865707/108602381-ebec6880-73a1-11eb-990f-e36f45518f76.png)

**Comment by mac12m99** [comment]
Ciao,
il problema è stato corretto con 6ca8c34692a89c0e2c980354c30944d7c39ea88b, in pratica le API di mediaset mostravano di default 100 risultati alla volta, ho incrementato il limite manualmente a 10000 (il massimo consentito).
