### ISSUE TITLE
Vai all'episodio successivo, riprendi da e segna automaticamente come visto non funzionante videoteca

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#272]
Dopo l'aggiornamento di KoD alla versione 1.6 sia vai all'episodio successivo, riprendi da che segna automaticamente come visto sembrano aver smesso di funzionare, il problema si presenta sia su Kodi 18.9 che 19 rc immagino sia dovuto dalla rimozione della dipendenza di TMDB visto che si basava su quello il riprendi da.

**Comment by mac12m99** [comment]
Dovrebbe essere risolto con 4d1898cf042162a923b071af6282ec8d3e6e9273, era un effetto collaterale di una modifica introdotta nella 1.6.. grazie di averlo segnalato.

Potrebbe essere necessario riavviare kodi dopo averlo ricevuto affinchè venga "digerito".
