### ISSUE TITLE
Unable to install due to dep

### ISSUE THREAD

**Issue by danny88br** [Stream4me/addon#273]
non riesco ad a fare fresh install per via di una dependency mancante/non funzionante ( TVDB 0.0.0 ) 
non credo che il problema sia con il plugin in se ma credo sia dovuto al fatto che la dependency sia stata rimossa

**Comment by mac12m99** [comment]
Ciao,
ci siamo dimenticati di rimuoverla anche nell'installer, grazie della segnalazione!
Comunque nei repo ufficiali tvdb c'è, secondo me hai installato un fork
