### ISSUE TITLE
Non funziona "Salva link"

### ISSUE THREAD

**Issue by Gythion** [Stream4me/addon#277]
https://file.io/ax5hYeMUk5mx.log

**Comment by mac12m99** [comment]
Ciao,
il file risulta eliminato (probabilmente perchè l'hai aperto tu o qualcun'altro prima di noi), potresti rigenerarlo? (e magari spiegare di preciso cosa accade)

**Comment by Gythion** [comment]
https://is.gd/tznhQl

**Comment by mac12m99** [comment]
Grazie della segnalazione, risolto con 3df9077cac62542df7fea43c8ae31c87a59d558a.
