### ISSUE TITLE
Update a Kodi 19, nessun server trovato. Su ben 2 cellulari

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#278]
Salve,
Come scritto su telegram riporto la discussione già fatta:
Ho fatto la prova di aggiornare kodi al 19 sul cell di mia madre

Su google play da ancora la 18.9

Sono andato su kodi.tv e aggiornato a 19 da li

Intanto si blocca quando cerca di finire di allineare gli addons

Appena riavviato faccio subito il tocco sul film visto ieri sera e tadà: nessun elemento da visualizzare

Faccio ricerca su novità per prova  e dato che li i server ci sono per forza e

Nessun elemento da visualizzare lo stesso

Su novità nel cell di mia madre danno tutti errore di connessione ma dal browser si aprono

Stessa identica cosa sul mio
Vi scongiuro help! Ora ho 2 devices che non funzionano (ed è domenica :p )

**Comment by omgfrost** [comment]
Tutto ciò è iniziato perchè sul mio s6 con android 10 ha fatto l'update mentre dormivo.
Sul play store del samsung A51 di mia madre non dava neanche la 19. Ma 18.9 come ultima versione

**Comment by omgfrost** [comment]
Ragazzi segnalo anche che risulta impossibile copiare il link del log così l'ho trovato nel file manager
[kodi.log](https://github.com/kodiondemand/addon/files/6017585/kodi.log)

**Comment by omgfrost** [comment]
Log cell mia madre
[kodi.log](https://github.com/kodiondemand/addon/files/6017614/kodi.log)

**Comment by mac12m99** [comment]
Ciao, dal log sembra tutto causato da questa impostazione:
![image](https://user-images.githubusercontent.com/10120390/108630808-063c4a00-7467-11eb-8b93-0d9b593bbceb.png)

Di cui infatti ci eravamo dimenticati di testare sul 19, grazie della segnalazione!

**Comment by omgfrost** [comment]
grazieeeeeee! Appena posso lo provo subito e vi dico
Aspetta...li c'è scritto BETA...
devo installare la beta o va bene subito anche sulla stable?

**Comment by mac12m99** [comment]
Va bene anche sulla stabile, ho solo fatto lo screen da ambiente di sviluppo.
Appena posso vedo di correggere

**Comment by omgfrost** [comment]
Perfetto! disabilitato e ora trova tutto come prima. Mannacciaavvoialtri!! che ho dovuto disinstallare e perdere tutta la libreria\videoteca!
Ora pushate il commit per far in modo che anche quella funzione funzioni sul 19 e potete chiudere questo issue.
Grazie della pazienza di aver analizzato i logs e di aver trovato la soluzione

**Comment by mac12m99** [comment]
Ottimo, mi spiace per l'inconveniente :(
Risolto con 0d49a4e8dc728c8e8c343ab97f36dfe3d7086b02 (si, ho visto un'altro problema nel tuo log :D)

Grazie a te di aver fatto una segnalazione come si deve!
