### ISSUE TITLE
Errore Videoteca KOD (dir_util e RaspberryPi)

### ISSUE THREAD

**Issue by camilloartisti** [Stream4me/addon#282]
Salve,
riscontro un errore nell'accedere ed utilizzare la libreria di KOD su Kodi Matrix, avendo posto la libreria di quest'ultima su MariaDB 10.3 presso la stessa macchina.
Di seguito il link al report preparato dal vostro stesso addon:
http://dpaste.com/HG9MP2DQH.txt
Colgo l'occasione per ringraziarvi del vostro ottimo progetto, che seguo da alcuni anni.
Camillo

**Comment by mac12m99** [comment]
Salve,
il problema pare essere una dipendenza circolare di un modulo python, non ho ben capito il motivo (è un problema assai singolare) ma sospetto sia una qualche modifica legata alla versione alpha 20 di kodi che hai installato (consiglio di installare la v19 stabile)
Comunque, come workaround ho spostato l'import solo dove serve (503fe75d26434991aa14efec8d470246e46e512f), riesci ad installare la versione beta di KoD e darmi un feedback? (reinstalla senza disinstallare e scegli la versione beta)

> Colgo l'occasione per ringraziarvi del vostro ottimo progetto, che seguo da alcuni anni.
> Camillo

E' sempre bello sentirlo :)
Comunque è uscito da neanche 2 anni :D

**Comment by mac12m99** [comment]
Stesso identico problema:
https://github.com/kodiondemand/addon/issues/283
Stesso dispositivo ma stavolta kodi 19, quindi l'alpha di kodi 20 è da escludere, sospetto quindi qualcosa legato ad una installazione di python presente sulla distro che avete installato sul vostro raspberry, potreste indicarla?

**Comment by camilloartisti** [comment]
> Comunque, come workaround ho spostato l'import solo dove serve ([503fe75](https://github.com/kodiondemand/addon/commit/503fe75d26434991aa14efec8d470246e46e512f)), riesci ad installare la versione beta di KoD e darmi un feedback? (reinstalla senza disinstallare e scegli la versione beta)

Ho installato la versione beta di KOD, adesso la videolibrary(KOD) funziona correttamente , ma solo se disabilito l'integrazione automatica con la library(Kodi) e aggiungo manualmente la cartella della videolibrary(KOD) come fonte della libreria (Kodi); in quest'ultimo modo vedo la lista delle serietv aggiunte con KOD anche da client Kodi remoti, tuttavia (anche installando la stessa versione beta di KOD su quest'ultimi), vedo solo il titolo ma non la lista dei server da cui effettuare lo streaming.

**Comment by mac12m99** [comment]
> Ho installato la versione beta di KOD, adesso la videolibrary(KOD) funziona correttamente , ma solo se disabilito l'integrazione automatica con la library(Kodi) e aggiungo manualmente la cartella della videolibrary(KOD) come fonte della libreria (Kodi); in quest'ultimo modo vedo la lista delle serietv aggiunte con KOD anche da client Kodi remoti

Se non fai tutto ciò che succede? Da errore? Secondo me è un problema diverso..

>  tuttavia (anche installando la stessa versione beta di KOD su quest'ultimi), vedo solo il titolo ma non la lista dei server da cui effettuare lo streaming.

Qualsiasi serie aggiungi, anche se dal canale/ricerca i server ci sono? Ti esce solo "niente da visualizzare" oppure da errore?

**Comment by mac12m99** [comment]
Il workaround è stato incluso nell'ultima versione stabile, in assenza di risposta chiudo, nel caso abbiate ancora problemi riaprite pure.
