### ISSUE TITLE
Errore nell'aprire una serie dalla Videoteca

### ISSUE THREAD

**Issue by zaffo80** [Stream4me/addon#283]
Qui trovate il log: https://dpaste.com/H6UREAVBW.txt

Ho tentato di aprire una serie che avevo aggiunto alla Videoteca di Kodi con la 18.9 e KOD ha ritornato un errore.

**Comment by mac12m99** [comment]
Ciao,
è lo stesso problema segnalato qui:
https://github.com/kodiondemand/addon/issues/282
Per favore leggi la risposta che ho dato e dammi un feedback, chiudo l'issue per non generare confusione, rispondi in quello che ti ho linkato
