### ISSUE TITLE
Aggiunta di episodi ita senza tag nei canali dove hanno entrambi ma tag solo [sub-ita] + aggiunta di opzione per aggiungere singoli episodi dalla ricerca

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#285]
Riporto quanto scritto in TG:
![Screenshot_20210303-144605599](https://user-images.githubusercontent.com/14861120/109820814-a5b2c700-7c35-11eb-8f7b-e2fa34f20069.jpg)
Salve devs e chat, è possibile avere la possibilità di scegliere gli ita anche quando non c'è il tag nei canali che hanno entrambi ma tag solo sub-ita?

No perchè così aggiunge tutta la serie e non si sà dopo quali saranno gli ita. Questo è serietvu che ha server streamtape (il migliore per me) e poi addo cb01 che non ha mai i titoli ma ha sempre tutti i tag

Aggiungo inoltre la richiesta di avere la possibilità di aggiungere singoli episodi dalla ricerca (magari sotto dove già c'è download episodio)
![Screenshot_20210303-163750677 (1)](https://user-images.githubusercontent.com/14861120/109830667-fda1fb80-7c3e-11eb-8a9f-fa2f5166a2e2.jpg)

Grazie, saluti e buon lavoro

**Comment by omgfrost** [comment]
Bump.
UPDATE: Ragazzi, magari non vi scervellate a discernere tra ITA e SUB-ITA quando ci sono entrambi gli episodi ma non entrambe le tag, ho trovato altri canali che al 99% le mettono entrambe.
Quello che piu' mi preme sarebbe l'aggiunta di "Aggiungi alla videoteca" il singolo episodio, magari se serve la folder della serie, prima si adda tutta la serie, poi si cancellano gli episodi che non si vogliono e poi si va in ricerca ancora e si aggiunge l'episodio che si vuole.
Saluti e buon lavoro

**Comment by omgfrost** [comment]
Questa come và?

**Comment by mac12m99** [comment]
Piccolo aggiornamento: 
- aggiungere un singolo episodio alla videoteca secondo noi non ha molto senso, perchè vorresti farlo? Puoi spiegarti meglio?
- Inserire ITA in caso esistano anche episodi SUB-ITA lo faremo

**Comment by omgfrost** [comment]
> Piccolo aggiornamento:
> 
> * aggiungere un singolo episodio alla videoteca secondo noi non ha molto senso, perchè vorresti farlo? Puoi spiegarti meglio?
> * Inserire ITA in caso esistano anche episodi SUB-ITA lo faremo

Hmm..io non ho ben capito se i tag [ITA] e [SUB-ITA] le inserite voi in auto o le inseriscono i canali..perchè ad es. cb01 li ha SEMPRE entrambi.
Bè..se inserirete i tag per TUTTI i canali allora magari aggiungere il singolo episodio non avrebbe senso, ma nel caso ciò non riuscisse..sarebbe utile aggiungere un episodio (tipo l'ultimo di una sTV in corso) che in una lista con tag [ITA] mancanti ma facendo partire l'episodio risulti in ita.
Comunque, a mio avviso, sarebbe un surplus da aggiungere che magari tornerebbe sempre utile (al momento non mi vengono altre idee\motivi oltre i sopracitati) ma ho questa sensazione che sarebbe un "tocco di classe" ad avere quest'esclusiva opzione in piu' (just my thoughts...)

**Comment by mac12m99** [comment]
> Hmm..io non ho ben capito se i tag [ITA] e [SUB-ITA] le inserite voi in auto o le inseriscono i canali..perchè ad es. cb01 li ha SEMPRE entrambi.

Li inseriscono i canali, e KoD li riconosce e mostra
> Bè..se inserirete i tag per TUTTI i canali allora magari aggiungere il singolo episodio non avrebbe senso, ma nel caso ciò non riuscisse..sarebbe utile aggiungere un episodio (tipo l'ultimo di una sTV in corso) che in una lista con tag [ITA] mancanti ma facendo partire l'episodio risulti in ita.

L'idea attuale sarebbe flaggare come ITA se sono presenti puntate sub-ita (ovvero il sito dice che sono sub-ita), mettere ITA dappertutto non avrebbe senso, il vero problema è, come da te fatto notare, l'impossibilità di usare l'opzione ITA+SUB-iTA mentre si salva in videoteca.
Questa azione dovrebbe farla apparire.

**Comment by mac12m99** [comment]
Corretto con 5f786c3eb4d90a0a8f9a2ca5796bf262d08c1956, non viene scritto ITA nel titolo ma viene mostrata comunque la schermata di scelta
