### ISSUE TITLE
Errore con Dialog Box per riportare l'errore scegliendo sì o no, cliccando su configurazione aggiornamento videoteca

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#287]
Buongiorno,
come da video allegato (e come @mac12m99  mi aveva detto che si sarebbe aperta la procedura di segnalazione dell'errore premendo su sì) non si apre niente (forse skin: Aeon nox:Silvo?) su Kodi 19 - Windows 10 Pro.

https://user-images.githubusercontent.com/14861120/110306847-9600fd00-7ffe-11eb-8fc1-df271a233a1f.mp4

[Kod Log](https://dpaste.com/E7VQCXEL8.txt)
Nonostante ciò, vorrei segnalare che questo Dialog Box (premendo sì, non ha mai funzionato, anche in altre parti che ora non ricordo ma tipo funzioni di ricerca avanzata o altre rare cose che si fanno in Kod. Segnalo così se potete controllare, se mi ricapiterà (sempre che non abbiate fixato questa che magari sarebbe un "global"fix) allora continuerò a postare qui.
Grazie e buon lavoro.

**Comment by mac12m99** [comment]
Corretti entrambi i problemi sulla beta con 87694b51abe64a5276b1193101547a2ec2bc1c68.
Ora in teoria premere si dovrebbe funzionare ovunque (a meno che non ci sia un problema nei componenti base)

**Comment by omgfrost** [comment]
Scusa @mac12m99 ma ora fixiamo tutto sulla beta?
Prima andavano sulla stable.
Scusa se non capisco,ma lo fai per guadagnare tempo per un prossimo package per la stable?
È soltanto curiosità la mia, non ho problemi a installare la beta...è solo che l'ultima volta mi dava problemi in ricerca e qualche > crash...quindi che dici? Procedo o aspetto?
O meglio, procedo e riporto eventuali issues della beta?

**Comment by mac12m99** [comment]
> Scusa @mac12m99 ma ora fixiamo tutto sulla beta?
> Prima andavano sulla stable.

Sono sempre stati mandati prima sulla beta e poi sulla stabile, solo che prima lo facevo subito.
Ci siamo dati come regola di mandare su stabile solo se sicuri che non causi altri problemi (anche se in questo caso è diverso, leggi sotto)

> Scusa se non capisco,ma lo fai per guadagnare tempo per un prossimo package per la stable?

In questo caso si, rilasceremo a breve quindi non ha senso considerando che non impatta molto sull'usabilità (ho motivo di credere che ci sia da mesi, sei il primo che se ne è accorto)

> È soltanto curiosità la mia, non ho problemi a installare la beta...è solo che l'ultima volta mi dava problemi in ricerca e qualche > crash...quindi che dici? Procedo o aspetto?
> O meglio, procedo e riporto eventuali issues della beta?

La beta è per definizione da considerarsi instabile perchè piena di modifiche non testate o di codice bozza solo per scambiarsi opinioni, poi certamente ci sono momenti in cui è meglio.
Di solito mandiamo sulla beta, chiediamo conferma e poi mandiamo sulla stabile, ma se il problema è evidente / banale da risolvere lo mandiamo subito.

**Comment by omgfrost** [comment]
> > Scusa @mac12m99 ma ora fixiamo tutto sulla beta?
> > Prima andavano sulla stable.
> 
> Sono sempre stati mandati prima sulla beta e poi sulla stabile, solo che prima lo facevo subito.
> Ci siamo dati come regola di mandare su stabile solo se sicuri che non causi altri problemi (anche se in questo caso è diverso, leggi sotto)
> 
> > Scusa se non capisco,ma lo fai per guadagnare tempo per un prossimo package per la stable?
> 
> In questo caso si, rilasceremo a breve quindi non ha senso considerando che non impatta molto sull'usabilità (ho motivo di credere che ci sia da mesi, sei il primo che se ne è accorto)
> 
> > È soltanto curiosità la mia, non ho problemi a installare la beta...è solo che l'ultima volta mi dava problemi in ricerca e qualche > crash...quindi che dici? Procedo o aspetto?
> > O meglio, procedo e riporto eventuali issues della beta?
> 
> La beta è per definizione da considerarsi instabile perchè piena di modifiche non testate o di codice bozza solo per scambiarsi opinioni, poi certamente ci sono momenti in cui è meglio.
> Di solito mandiamo sulla beta, chiediamo conferma e poi mandiamo sulla stabile, ma se il problema è evidente / banale da risolvere lo mandiamo subito.

Mi piace quando persone colte mi dicono "sei il primo" :P
Passo e chiudo.
