### ISSUE TITLE
Kod una volta cambiata la view list da default(predefinita) ad altre scelte, non torna piu' la default.

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#288]
Salve,
come da titolo è appena successo sia nel mio galaxy s6 che in Windows 10, sia sulla stable che sulla beta.
Allego video
[VIDEO](https://drive.google.com/file/d/1eCDZYhTsVFA89BhrAxMvt18SxpI16LZd/view?usp=sharing)
Allego log (anche se non so come riprodure l'errore ora che la default non si seleziona più)

Raga scusate ma perchè ora mi è ritornato file.io che non si clicca\apre? potete rimettere sempre e soltanto dpaste per piacere che almeno si clicca? Grazie.
PS: Il log link ve lo screenshotto perchè impazzisco ad altabbare lettera per lettera
![qVMuYaR 1](https://user-images.githubusercontent.com/14861120/110477089-0aad6780-80e3-11eb-98df-83d1e6165a73.png)
UPDATE: aah forse è voluto che il link non sia cliccabile perchè il file viene cancellato una volta che si accede a quel link..ma allora come fare? **cough** dpaste **cough**
PS: Volevo inoltre aggiungere che sono andato a cercare il db.sqlite per rinominarlo ma nella 19 non c'è più..o l'avete tolto voi❌

**Comment by mac12m99** [comment]
Salve,
i tipi di vista si riferiscono a [episodio successivo](https://github.com/kodiondemand/addon/wiki/Episodio-successivo) (infatti, se lo disattivi, quel settaggio scompare), quello che mi sembra di capire è che tu voglia cambiare la visualizzazione, per quello basta aprire il menu laterale (una volta cambiata dovrebbe cambiare per tutte le sezioni "dello stesso tipo", ma abbiamo avuto alcune segnalazioni di mancato salvataggio della vista).

Per quanto riguarda file.io è corretto, se si apre il link viene eliminato. Magari possiamo pensare di copiarlo negli appunti se possibile.. vedremo.
Il file db.sqlite dovrebbe esserci.. stai guardando in addon_data giusto?

**Comment by omgfrost** [comment]
> Salve,
> i tipi di vista si riferiscono a [episodio successivo](https://github.com/kodiondemand/addon/wiki/Episodio-successivo) (infatti, se lo disattivi, quel settaggio scompare), quello che mi sembra di capire è che tu voglia cambiare la visualizzazione, per quello basta aprire il menu laterale (una volta cambiata dovrebbe cambiare per tutte le sezioni "dello stesso tipo", ma abbiamo avuto alcune segnalazioni di mancato salvataggio della vista).
> 
> Per quanto riguarda file.io è corretto, se si apre il link viene eliminato. Magari possiamo pensare di copiarlo negli appunti se possibile.. vedremo.
> Il file db.sqlite dovrebbe esserci.. stai guardando in addon_data giusto?

No @mac12m99 guarda forse ti sei sbagliato è la voce sotto, tipo vista. Sei riuscito a vedere il link al video sopra?
Il file db.sqlite l'ho cercato per tutto il telefono e per tutto windows, con la 19 è scomparso.
Se veramente è nella stessa posizione puoi controllare?e se c'è mi potresti indicare il path corretto?
Per file.io o trovate un modo di farlo mettere in clipboard su click oppure usate dpaste che per me è sempre stato ottimo.
Attendo aggiornamenti

**Comment by omgfrost** [comment]
Video https://drive.google.com/file/d/1eCDZYhTsVFA89BhrAxMvt18SxpI16LZd/view?usp=sharing

**Comment by mac12m99** [comment]
> No @mac12m99 guarda forse ti sei sbagliato è la voce sotto, tipo vista. Sei riuscito a vedere il link al video sopra?

Si l'ho visto e ti dico che la voce sotto, "tipo vista" si riferisce ad episodio successivo (il "tipo di vista" della finestra che ti chiede se vuoi passare all'episodio successivo), guarda il link che ti ho mandato.
Forse non è molto chiaro.. come lo chiameresti quel settaggio? :D

> Il file db.sqlite l'ho cercato per tutto il telefono e per tutto windows, con la 19 è scomparso.
> Se veramente è nella stessa posizione puoi controllare?e se c'è mi potresti indicare il path corretto?

Il percorso è /.kodi/userdata/addon_data/plugin.video.kod/
C'è di sicuro, se non esiste viene ricreato al primo avvio di KoD

**Comment by omgfrost** [comment]
> > No @mac12m99 guarda forse ti sei sbagliato è la voce sotto, tipo vista. Sei riuscito a vedere il link al video sopra?
> 
> Si l'ho visto e ti dico che la voce sotto, "tipo vista" si riferisce ad episodio successivo (il "tipo di vista" della finestra che ti chiede se vuoi passare all'episodio successivo), guarda il link che ti ho mandato.
> Forse non è molto chiaro.. come lo chiameresti quel settaggio? :D
> 
> > Il file db.sqlite l'ho cercato per tutto il telefono e per tutto windows, con la 19 è scomparso.
> > Se veramente è nella stessa posizione puoi controllare?e se c'è mi potresti indicare il path corretto?
> 
> Il percorso è /.kodi/userdata/addon_data/plugin.video.kod/
> C'è di sicuro, se non esiste viene ricreato al primo avvio di KoD

Trovata e fixata la vista episodi compresi di miniatura a sx; in pratica dovevo mettere list e poi entrare dentro la serie, così si e modificata, con altri tentativi di oggi no (ora sono in beta,ma cambio appena finito qui.

Il db.sqlite l'ho trovato e rinominato; ho dovuto wipeare le partizioni del cell tranne system così ho dovuto riconfigurare quasi tutto e pero il bookmark del path del suddetto file.

Ero talmente straziato dal tentare di aprire e chiudere il pannello a sx che mi ha instupidito da quanti tentativi ho fatto per tappare sulle iconcine microacopiche su sto cell.
Tutto questo mi ha portato a neanche più accorgermi che il "tipo vista" era nel box degli episodi.

MI RACCOMANDO DPASTE O SEND TO CLIPBOARD SE È FILE.IO!!
Grazie moltissime!
Chiudo
