### ISSUE TITLE
Paginazione Mediaset Play

### ISSUE THREAD

**Issue by Gythion** [Stream4me/addon#289]
Salve, ho riscontrato mancata apertura TG5 ed, in più, non  funzionano i link diretti su Android, su Windows sì: http://dpaste.com/A7W4XP5ZO

**Comment by mac12m99** [comment]
Ahime il link pare sia scaduto, potresti rimandarlo?

**Comment by Gythion** [comment]
Autoplay ovviamente fixato, permangono problemi su TG5: https://is.gd/wVxZrh

**Comment by mac12m99** [comment]
Grazie, corretto con 9f304abbee7e5f1f064d598bd79daa2701461a63
Tuttavia questo fix limita il numero di risultati a 1000, sarebbe opportuno implementare una paginazione, lascio aperto per promemoria.
