### ISSUE TITLE
StreamingCommunity

### ISSUE THREAD

**Issue by Gr33nR10t** [Stream4me/addon#290]
StreamingCommunity (streamingcommunity.co)

- Il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore

Ho aggiunto la serie "Mucca e Pollo" alla mia videoteca con KOD ma purtroppo sul S2E1 viene visualizzato sempre il link del S1E1; anche altri episodi della seconda serie fanno partire il S1E1 anche se il titolo dell'episodio è corretto.

Ho provato ad eliminare la serie e aggiungerla nuovamente aggiornando la libreria ma purtroppo il problema sussiste.

**Comment by mac12m99** [comment]
Ciao,
grazie della segnalazione, problema risolto, riavvia kodi o vai in aiuto -> controlla aggiornamenti
