### ISSUE TITLE
Non funziona la sincronizzazione con TV Time

### ISSUE THREAD

**Issue by Dance68** [Stream4me/addon#291]
❄️Fabio❄️, [23.03.21 17:49]
Salve, uso l'addon TV Time (simile a Trakt) per tenere traccia degli episodi visti delle serie TV, mi sono accorto che da un po' di tempo la sincronizzazione da Kodi a TV Time e viceversa, non funziona, ho provato anche Trakt e succede la stessa cosa (ora l'ho tolto perche' non mi piace, x me e' troppo incasinato). 
- Kodi 18.8.0
- KOD v1.6.1 a79a83b
- S.O. Windows10 

Quale potrebbe essere il problema? Grazie in anticipo.

**Comment by mac12m99** [comment]
Salve,
se con trakt potrebbe essere un problema riguardante l'addon (dato che è supportato), non può esserlo con tv time in quanto KoD non ha nulla a che fare con esso.

**Comment by Dance68** [comment]
Non ho per nulla capito la sua risposta, le dico che tutto ha sempre funzionato egregiamente con TV Time e dopo alcuni fix i Kod, non funziona piu'. Per me il problema risiede in KOD, probabilmente con gli aggiornamenti e' stato "toccato e variato" qualcosa che influisce sulla sincronizzazione bidirezionale. Trakt l'ho solo citato per far capire che il problema non sta' degli addon Trakt e TV Time perche', entrambi non sincronizzano.
