### ISSUE TITLE
Espansione del servizio al di fuori di kodi

### ISSUE THREAD

**Issue by MikeCoder96** [Stream4me/addon#292]
Salve, avevo iniziato un servizio simile a questo destinato ad un uso mobile e desktop senza l'utilizzo di kodi e quindi avevo realizzato delle app app dedicato al servizio streaming.
Avete in programma di fare una cosa simile e rendere questo servizio usufruibile senza l'uso di kodi ma con app proprie sia per desktop che per mobile?
Se si mi piacerebbe contribuire.

**Comment by mac12m99** [comment]
Salve, 
fare un app a nostro parere sarebbe inutile e insensato in quanto ce l'abbiamo già e funziona bene su tutte le principali piattaforme (kodi), perchè riscriverlo da capo?
Avevamo già un idea di "espanderci" all'infuori di kodi ma non con una app, bensi con un [mediaserver](https://github.com/kodiondemand/mediaserver) in modo da rendere questo software disponibile anche ai dispositivi per il quale kodi non è supportato (console con browser ad esempio, o tv non android). Poi questo mediaserver volendo lo si può far aprire anche da una app.. ma la navigazione avverrà da browser.

Detto questo siamo sempre aperti a [contribuzioni](https://github.com/kodiondemand/addon/blob/master/CONTRIBUTING.md)

**Comment by MikeCoder96** [comment]
Vero ma ci sta anche chi kodi non lo conosce e non lo sa usare mentre invece una app dedicata verrebbe più facile ed intuitiva ad un utente poco esperto!
Ad ogni modo sarò lieto di contribuire per la realizzazione del mediaserver e/o di fixare eventuali issue su questa repo.

**Comment by mac12m99** [comment]
> Vero ma ci sta anche chi kodi non lo conosce e non lo sa usare mentre invece una app dedicata verrebbe più facile ed intuitiva ad un utente poco esperto!

Si questo probabilmente è vero, tuttavia questo è un hobby dal quale non ricaviamo nulla, quindi avere più utenti non ci cambia più di tanto  :D

> Ad ogni modo sarò lieto di contribuire per la realizzazione del mediaserver e/o di fixare eventuali issue su questa repo.

Ottimo grazie! 
Per info sul funzionamento dell'addon inizia [da qui](https://github.com/kodiondemand/addon/blob/master/CONTRIBUTING.md#per-sviluppatori)
se poi vorrai entrare nel gruppo telegram di sviluppo facci sapere (non c'è nessun obbligo tranquillo, è un hobby)

**Comment by fatshotty** [comment]
ho sentito parlare di "mediaserver" e "app". Mi inserisco: ho scritto un servizio simil-mediaserver che magari puo' tornare utile...
Mi rendo disponibile per una chiacchierata su telegram :)

**Comment by fatshotty** [comment]
@MikeCoder96 niente? :D

**Comment by MikeCoder96** [comment]
@fatshotty a tempo libero sto estraendo le parti essenziali dell'addon come il solver e l'estractor dei siti ma richiede tempo e forse non è neanche una soluzione ottima visto il tempo che richiede per l'elaborazione.
A breve sul mio git andrò a caricare quella che è una vecchia versione di midiastrimi client scritto in flutter "puoi trovare il server sul mio git"

**Comment by fatshotty** [comment]
@MikeCoder96 se vuoi continuiamo la conversazione su telegram, cosi' cerchiamo di capire meglio :)
