### ISSUE TITLE
Buona sera,non funziona film per tutti,mi esce "errore inaspettato film per tutti, potrebbe essere dovuto alla connessione o la pagina web ha cambiato struttura".

### ISSUE THREAD

**Issue by sasy2001** [Stream4me/addon#294]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Inserisci il nome del canale

- Il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore

Es. non riesco ad aggiungere film nella videoteca, ne dal menu contestuale, ne dalla voce in fondo alla lista dei server.

Se faccio ricerca globale, non riesco ad aggiungere film/serie/anime nella videoteca o a scaricare il video.

- Allega il file di log nella sua completezza. Non cancellarne delle parti.

**Comment by mac12m99** [comment]
Buongiorno,
Non rilevo nessun problema su filmpertutti, per favore sii più specifico ed allega [il log](https://telegra.ph/LOG-11-20)

PS
Il template è fatto per essere compilato sostituendo il testo, non lasciare "Inserisci il nome del canale" o gli esempi.
