### ISSUE TITLE
Mediaset Play  e la7 live

### ISSUE THREAD

**Issue by step1975roma** [Stream4me/addon#295]
salve mi chiamo stefano, volevo segnalare che ci sono problemi su mediaset play, su mio smart tv, dove e installato kodi... serie tv (svegliati amore mio) riproduzione fallita su tutte le puntate, dovrebbe uscire riproduci.mpd diretto.. ma esce diverso bisogna ricontrollare tutto, perche' altre puntate di altre serie tv da anche errore... uso kodi 19 matrix...sulla smart tv...li voglio fare vedere le puntate di quella serie tv a mia madre...segnalo anche che la sette live  non parte esce una schermata nera mentre gira la palla in cerca dello stream sono giorni che quello stream non va.... attualmente solo la 7D Gira, vi prego sistemate perche la sette live lo vedo dalla mia stanza su pc dove non ho una tv...,grazie.

.....
non so come mandare un log di errore, ne come prenderlo da una smart tv.. mi scuso.

**Comment by step1975roma** [comment]
ciao innanzitutto grazie per la risposta, per quanto riguarda addon la sette tutto bene installato ma per  per l'altro  imput stream adaptive no mi dice sempre struttura non valida zip di una versione precedente 2.4.5 a me sembra strano tutto cio', perche se la 7d lo stream parte mentre e solo con la 7 che lo stream da questa schermata nera... e non parte, e le puntate di quella serie svegliati amore mio non partono, quando erano con .mpd le puntate andavano bene. non so cosa fare. se ai consigli bene accetti... buona giornata, aspetto notizie in merito.

**Comment by mac12m99** [comment]
Ciao,
il problema persiste ancora? E' stato rilasciato un fix per mediaset nel frattempo
