### ISSUE TITLE
KoD su Android TV non mantiene le impostazioni tra un avvio e l'altro

### ISSUE THREAD

**Issue by DarkSkull91** [Stream4me/addon#303]
Ciao, vorrei segnalare il fatto che KoD su Android TV (Philips 8535) non salva correttamente le configurazioni fatte. Esempio che mi ha fatto aprire questa issue: le opzioni di visualizzazione, quando si riavvia l'app di default va a finire su Icon Wall anche se prima era impostata a List ( su raspberry questo problema non lo dava). Oltre a questo , avevo disabilitato anche l'avvio automatico degli episodi successivi per le serie tv.
Per fortuna, serie e film nella videoteca li mantiene.

Fatemi sapere se vi occorre qualche dettaglio in più.

**Comment by mac12m99** [comment]
Ciao,
per quanto riguarda la perdita della vista selezionata, abbiamo ricevuto anche altre segnalazioni ma essendo randomico è molto difficile da riprodurre in ambiente di sviluppo, potresti indicare versione di kodi, skin che utilizzi e procedura per ricrearlo? (se capita sempre)
Un log inoltre sarebbe sicuramente d'aiuto
https://telegra.ph/LOG-11-20

Per quanto riguarda l'avvio automatico mi pare molto strano, secondo me non hai schiacciato ok e quindi non ha (giustamente) salvato.

**Comment by DarkSkull91** [comment]
Ciao @mac12m99,
per il problema della vista selezionata posso assicurarti che non è assolutamente randomico nel mio caso, ad ogni avvio dell'app quindi quando si fa esci dal bottoncino, se invece sta in background la modifica della vista persiste.
La versione di kodi è la 19 ma questo problema c'era anche con la 18, non utilizzo nessuna skin.

Gli step per riprodurlo sono:

- entrare su KoD
- premere col telecomando freccia sinistra
- cambiare la vista di default con un'altra
- tornare sul menu di Kodi
- premere il pulsante per uscire dall'app

Ripeto che su raspberry non riscontravo questo problema, forse è un bug che affligge solamente la versione android.

Per quanto riguarda l'avvio automatico, ti assicuro che ho premuto ok. Secondo me il problema è diffuso su tutte le impostazione della versione Android.

Spero di essere stato utile nella descrizione del problema.

P.S.: il log essendo su Android TV non so come prenderlo

**Comment by mac12m99** [comment]
Ciao,
un po' tardivo ma è stato mandato sulla beta un fix che dovrebbe risolvere, se sei ancora attivo per favore riprova e facci sapere.

**Comment by DarkSkull91** [comment]
Ciao @mac12m99,
certo che sono attivo! Come la installo la versione beta sulla smart tv?

**Comment by mac12m99** [comment]
Perfetto, devi re-installare l'addon (senza disintallarlo) e scegliere la versione beta.

**Comment by DarkSkull91** [comment]
Google Play mi mostra solamente i tasti Apri e Disinstalla... Non puoi rilasciare sulla versione stabile e nel caso non funzioni la reverti?

**Comment by DarkSkull91** [comment]
Ho provato a reinstallare l'addon dal repo... Mi ha cancellato la vecchia e adesso non parte più KoD con la nuova installazione, mi ha dato solo un warning di errore e al posto dell'icona di KoD vedo una cartella che non fa partire l'applicazione. Spero di non aver perso tutta la videoteca...

**Comment by DarkSkull91** [comment]
Ho cancellato i dati di Kodi e reinstallato KoD in versione Beta e adesso mantiene le impostazioni della vista salvate. Sai quando verrà aggiornata la versione stabile con questa fix?

**Comment by Alhaziel01** [comment]
Fix Rilasciato su Stable

**Comment by DarkSkull91** [comment]
Non ho capito in quali circostanze ma continua a perdersi le impostazioni ogni tanto...
