### ISSUE TITLE
Impossibile aggiungere hunter X hunter videoteca 

### ISSUE THREAD

**Issue by Cri2009** [Stream4me/addon#306]
Kodi 19.1 non riesco ad aggiungere un anime nella libreria.

**Comment by Cri2009** [comment]
Ho provato anche con kodi  18.9

**Comment by mac12m99** [comment]
Da che canale stai provando? Che ti succede? Potresti mandare [un log](https://telegra.ph/LOG-11-20)? 
Pare dare sulla beta ma nella stabile funziona, sicuro di avere versione stabile?

**Comment by Cri2009** [comment]
﻿Allora ho messo kodi 18.9 e ha funzionato.

[cid:FAD60FF5-8640-4824-901B-C412B7A39998]




Saluti. Cristian Ferri

Il giorno 20 mag 2021, alle ore 20:45, mac12m99 ***@***.***> ha scritto:

﻿

Da che canale stai provando? Che ti succede? Potresti mandare un log<https://telegra.ph/LOG-11-20>?
Pare dare sulla beta ma nella stabile funziona, sicuro di avere versione stabile?
