### ISSUE TITLE
findvideos...e altri

### ISSUE THREAD

**Issue by greko17** [Stream4me/addon#31]
Premessa...

1° legge del Greko:
Se puoi Copia/incolla(re). Fallo!
Corollario:
Se puoi Inoltrare. Devi!

2° legge del Greko:
Se esiste già la ruota. Migliorala.
Corollario:
Ma se stai lavorando sulla ruota e ti accorgi che devi inventarla... Allora non era una ruota!

3° legge del Greko:
Copia/incolla il meno che puoi.
A lungo andare può portare a gravi disfunzioni. Vedi: L'indice del postino'
Corollario. Se hai l'indice del postino... o sei un postino o hai copia/incollato troppo...

Date le premesse:
Sto apportando modifiche sul canale Eurostreaming ( Altrimenti devo restituire le donazioni), "analizzando" il codice di altri canali e controllando che tutto funzioni come deve.
Ora...
Sono arrivato al punto di definire la def findvideos:
Ma mi trovo con problemi, a cui forse ho trovato una "soluzione" o "toppa!" e prima di proseguire con quanto..., vorrei sentire voi... Poiché non so se tutto questo va a modificare poi il comportamento dei canali già esistenti.
Sul canale, eurostreaming, ci sono dei link verso vcrypt che non funzionavano utilizzando la sola funzione:
servertools.find_video_items()
Quindi come succede negli altri canali la soluzione più ovvia, sarebbe quella di usare ulteriori funzioni, vedi unshortenit.qualcosa o la def decode() o altri codici...
Ma
Analizzando il codice mi sono accorto che viene richiamato il modulo zcrypt che nonostante funzioni come deve non mi trova il server che apparentemente già esiste: vidtome che effettivamente ha l'url:vidto.me, nel file .json, però diverso da quello richiamato dal canale, che  è :vidtome.stream.
Ho così creato i file vidtomestream.[py, json]. Ora richiamando la funzione, il canale viene trovato e si apre.
Ma
Anche per alcuni siti, vedi linkup.pro, ho riscontrato anomalie, e ho dovuto modificare il file zcrypt per poter utilizzare la sola funzione: servertools.find_video_items().
```
                elif 'linkup' in url:
                    idata = httptools.downloadpage(url).data
                    data = scrapertoolsV2.find_single_match(idata, "<iframe[^<>]*src=\\'([^'>]*)\\'[^<>]*>")
                    if '/olink/' in url or '/delta/' in url: #fix by greko per openload
                        from lib import unshortenit #fix by greko per openload
                        data, status = unshortenit.unshorten(url) #fix by greko per openload
                        logger.info("SONO QUA#####" + data) 
```
in quanto la regex non trova nulla e la def ritornava il link inviato.
Ora sembrerebbe che funzioni...
RET=https://linkup.pro/delta/7b5ffidbgo48 ['https://deltabit.co/9ki9scuo3rw7']
Ma
il link rimanda al sito https://deltabit.co, e per quanto detto sopra dovrei creare, i file da inserire nella cartella servers per poterlo fare trovare dalla: servertools.find_video_items(). ( e qui...sta il difficile...)

Però non so quanto esposto sopra sia corretto... e se le varie modifiche vadano a "sputtanare" qualcosa nel codice di kod e nel funzionamento dei canali esistenti.

Poi nel caso che tutto l'esposto sopra sia scorretto: inutile perderci tempo ulteriore...Ma almeno so....che ho toppato!

Grazie per l'attenzione!

Coriandoli saluti etc etc

**Comment by mac12m99** [comment]
per quanto riguarda vidtome, è piuttosto probabile che basti aggiungere un pattern:
"patterns": [
      {
        "pattern": "vidto.me/(?:embed-|)([A-z0-9]+)",
        "url": "http://vidto.me/embed-\\1.html"
      },
      {
        "pattern": "vidtome.stream/(?:embed-|)([A-z0-9]+)",
        "url": "http://vidtome.stream/\\1.html"
      }

Non è necessario (anzi, non conviene proprio) copiare vidtome e cambiare pattern.
Per quanto riguarda zcrypt va bene, tuttavia credo sarebbe meglio eliminare l'if, in quanto in futuro potrebbero usare altri servizi e dovremmo aggiungerli uno ad uno tutte le volte.
