### ISSUE TITLE
Kod si freeza, non chiudendosi correttamente, ogni volta che kod si aggiorna

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#312]
Salve ragazzi,
come anticipato sul canale TG riporto qui quanto scritto là:
**Smartphone:**
**Schermata blocco dopo aggiornamento kod:**
![isuCfYp 1](https://user-images.githubusercontent.com/14861120/122566348-bef64c80-d047-11eb-971c-37f795a0ed7b.jpg)
**PC**
![S30MVY5 1](https://user-images.githubusercontent.com/14861120/122566427-d33a4980-d047-11eb-8b14-fb708390b842.png)
**schermata blocco dopo aggiornamento kod, PC:**
![K3UO1bO 1](https://user-images.githubusercontent.com/14861120/122566628-0977c900-d048-11eb-921d-bf7546aedc6a.png)
**Forzo la chiusura su PC e allego log:**
[kodi.log](https://github.com/kodiondemand/addon/files/6677213/kodi.log)
**Log dello smartphone:**
[kodi[smartphone].log](https://github.com/kodiondemand/addon/files/6677256/kodi.smartphone.log)

**Comment by mac12m99** [comment]
Buongiorno,
forse ho fixato, ma per esserne certo devo fare una prova mandando un aggiornamento fittizio, potresti installare la beta?
Quando mi dai l'ok mando l'aggiornamento e la volta successiva che apri kodi controlli se ancora si freeza, ci stai?

Testerò anch'io da cellulare nel frattempo

**Comment by omgfrost** [comment]
> Buongiorno,
> forse ho fixato, ma per esserne certo devo fare una prova mandando un aggiornamento fittizio, potresti installare la beta?
> Quando mi dai l'ok mando l'aggiornamento e la volta successiva che apri kodi controlli se ancora si freeza, ci stai?
> 
> Testerò anch'io da cellulare nel frattempo

Ok come da accordi su TG, ho aggiornato alla beta kodi windows, che rimane al momento piu' comodo per fare i test.
Rimango in attesa dell'aggiornamento che dovrai inviare.
Buon proseguimento

**Comment by mac12m99** [comment]
Ciao,
ho mandato l'aggiornamento, quando riapri kodi attendi di riceverlo e prova a chiuderlo.

Ho provato da cell ma ancora si blocca :(
Fammi sapere, magari da pc è diverso

Edit: mandato altro possibile fix, informami quando ricevuto che riproviamo

**Comment by omgfrost** [comment]
la sfortuna ha voluto che ieri ho dovuto reinstallare la stable sul pc
perchè mia madre voleva vedere qualcosa sul kodi pc.
Quindi credo che bisognerebbe rifare ma al momento sono impegnatissimo con
una cosa urgentissima

**Comment by omgfrost** [comment]
Quindi? che si fà?

**Comment by mac12m99** [comment]
Reinstalla la beta, quando hai fatto mando un update e vediamo.

Potrei fare il test anche da solo ma se proviamo in 2 con 2 device differenti è meglio, stiamo più sicuri.

**Comment by omgfrost** [comment]
> Reinstalla la beta, quando hai fatto mando un update e vediamo.
> 
> Potrei fare il test anche da solo ma se proviamo in 2 con 2 device differenti è meglio, stiamo più sicuri.

Ok ho installato la beta su cell.
Abilito il log di debug o aspetto solo l'agg?

**Comment by mac12m99** [comment]
Abilita anche il debug.
Ma non eri da pc? Su android stavo provando io :D

**Comment by omgfrost** [comment]
> Abilita anche il debug.
> Ma non eri da pc? Su android stavo provando io :D

Ero :D
Ora installo su pc

**Comment by mac12m99** [comment]
Installato?

**Comment by omgfrost** [comment]
> Installato?

Si vai

**Comment by mac12m99** [comment]
Ok mandato, su android sembra funzionare.

**Comment by omgfrost** [comment]
> Ok mandato, su android sembra funzionare.

Ma non ho capito...
Ora apro con beta fà agg, chiudo e riapro e installo la stable o lascio tutto così?
No perchè la beta non mi trova niente in ricerca...

**Comment by omgfrost** [comment]
Ok con la beta si è chiuso normalmente..
Posso reinstallare la stable ora?

**Comment by mac12m99** [comment]
Chiudi e vedi se si chiude "normalmente", poi puoi fare ciò che vuoi.

**Comment by mac12m99** [comment]
Si, reinstalla pure
Grazie del test, poi mando su stabile. (E' probabile che, dovendo aggiornarsi, capiterà di nuovo :D ma sarà l'ultima volta)

**Comment by omgfrost** [comment]
> Si, reinstalla pure
> Grazie del test, poi mando su stabile. (E' probabile che, dovendo aggiornarsi, capiterà di nuovo :D ma sarà l'ultima volta)

Posso sapere quando?
Dovrei vedere degli episodi..... xD

**Comment by omgfrost** [comment]
Ah scusa ok allora, reinstallata la stable si è freezato..ma questo perchè ancora non ha quello dei traceback giusto?

**Comment by omgfrost** [comment]
Cè un modo per levare il log solo la visualizzazione delle scritte sul player?
Ma cmq continua a loggare in background?
![Screenshot_20210622-185445266](https://user-images.githubusercontent.com/14861120/122968255-a3fb4380-d38b-11eb-8341-e07877a4504d.jpg)

**Comment by omgfrost** [comment]
Non hai ancora inviato l'agg per la stable vero? perchè ho aperto kodi ora e non mi dice che è stato aggiornato.
O forse magari l'ha fatto ieri..cmq
io ho: `v1.7 fd135f1`

**Comment by mac12m99** [comment]
Ho mandato su stabile adesso, chiudo l'issue.

Grazie :)

**Comment by omgfrost** [comment]
grazie a te! Mi piace quando spotto cose interessanti e doverose da
aggiustare :)
