### ISSUE TITLE
Errore su tutti i link de Il CorsaroNero

### ISSUE THREAD

**Issue by iz8mbw** [Stream4me/addon#313]
Ciao.
I link (magnet ?) de "Il CorsaroNero" non si aprono anche se il sito e le sotto pagine sono raggiungibili.
Grazie!

**Comment by mac12m99** [comment]
Ciao, usi la beta, giusto?

**Comment by iz8mbw** [comment]
Sì

**Comment by mac12m99** [comment]
Ora dovrebbe essere risolto, anche se in altri canali / casi capita ancora, è una feature che stiamo sviluppando.
Al solito, per uso quotidiano meglio la stabile.

Grazie comunque di averlo fatto notare :)

**Comment by iz8mbw** [comment]
Il problema persistente anche dopo aver aggiornato la commit
