### ISSUE TITLE
altadefinizione.click - HDMARIO

### ISSUE THREAD

**Issue by morisgroves** [Stream4me/addon#315]
Ciao,
ho notato che in **altadefinizione.click** non viene mostrato il link a **HDMARIO** in tutti i film dove è presente anche se invece controllando da browser https://altadefinizione.software il link è c'è.
Un esempio: The Kelly Gang https://altadefinizione.software/the-kelly-gang-streaming/ ma l'ho notato su più titoli.
Grazie!

**Comment by mac12m99** [comment]
Ciao,
controllando da browser, il link non c'è, al suo posto c'è questo link:
https://t.me/s/ilcontrolloreoriginale/4
