### ISSUE TITLE
Problemi di scraping degli artwork nella libreria di Kodi

### ISSUE THREAD

**Issue by Greenylie** [Stream4me/addon#321]
Sto avendo problemi con lo scraping degli artwork delle serie nella libreria di Kodi (ovviamente aggiunte da kod).
Il problema sembra essere dello scraper tmdb, però come discusso [qui](https://www.themoviedb.org/talk/60de0392a128560074955f5d) dovrebbe essere già fixato con la versione 3.2.15 di metadata.common.themoviedb.org.

Sono un paio di giorni che mi assicuro di aggiornare gli scraper, ma continuo a riscontrare problemi e dato che tecnicamente lato tmdb dovrebbe essere risolto, mi rivolgo a voi sperando ci sia qualche incongruenza ancora da fixare.

Vi allego il [log](https://paste.kodi.tv/efucodasid.kodi) nel quale ho aggiunto due serie: [Shadows House](https://www.themoviedb.org/tv/111576) e [Tokyo Revengers](https://www.themoviedb.org/tv/105009) che precedentemente restituivano vari artwork tra cui poster e fanart

![image](https://user-images.githubusercontent.com/41172833/124678379-aea4f500-dec2-11eb-869d-26901a1b7268.png)
La situazione attuale è la seguente, e tra la selezione degli artwork non esce nulla.

Non so più dove mettere le mani, se il problema non dovesse dipendere da voi, vi prego di indirizzarmi, perché non ho davvero idea di come risolvere.

**Comment by mac12m99** [comment]
Ciao,
prova ad andare in impostazioni (di kodi) -> elemento -> video -> videolibrary -> Serie tv  ed aprire il menu contestuale, per poi selezionale "cambi contenuto".
Lo scraper dovrebbe essere TMDb tvshows, se così non fosse impostalo e dai conferma quando ti chiede di riscansionare.

**Comment by Greenylie** [comment]
Avevo già provato in precedenza, quello che succede lo allego in foto e log:
![image](https://user-images.githubusercontent.com/41172833/124799135-84037c80-df54-11eb-9321-d4cc16e7ebed.png)
Vengono identificate delle serie totalmente errate.
(succede anche selezionando tmdb shows python e successivamente aggiungendo la serie con kod alla libreria)


Allego il log che è troppo lungo:
[kodi.log](https://github.com/kodiondemand/addon/files/6778893/kodi.log)

**Comment by mac12m99** [comment]
La cosa è decisamente strana, considera che prima di risponderti avevo provato io stesso, e così facendo avevo risolto :(
Purtroppo trattandosi di kodi/altro addon molte idee non le ho, non posso che consigliarti di provare con un altra istanza di kodi (pulita)..

**Comment by Greenylie** [comment]
> La cosa è decisamente strana, considera che prima di risponderti avevo provato io stesso, e così facendo avevo risolto :(
> Purtroppo trattandosi di kodi/altro addon molte idee non le ho, non posso che consigliarti di provare con un altra istanza di kodi (pulita)..

Si ma effettivamente il tuo consiglio era corretto, lo scraper in versione python dovrebbe essere ok...
Comunque questa era già un'installazione pulita, dato che il problema si presentava precedentemente.
Non ho idea di cosa fare :(

**Comment by Greenylie** [comment]
> La cosa è decisamente strana, considera che prima di risponderti avevo provato io stesso, e così facendo avevo risolto :(
> Purtroppo trattandosi di kodi/altro addon molte idee non le ho, non posso che consigliarti di provare con un altra istanza di kodi (pulita)..

Alla fine ho deciso di rollbackare a kodi 18.9 e sfruttare artwork beef
