### ISSUE TITLE
Streaming Community

### ISSUE THREAD

**Issue by KyrosWeb** [Stream4me/addon#322]
Non so se sia giusto segnalare qui ma Streaming Community ha cambiato proprio URL ma la struttura è rimasta invariata. Forse sarebbe solo necessario aggiornare la baseurl con la nuova?

**Comment by mac12m99** [comment]
L'url è stato aggiornato in automatico sulla beta da parte del nostro BOT, ma questa modifica non è ancora stata passata sulla stabile, e al momento non dovrebbe essere un problema dato che .tv reindirizza a .work (l'ultimo).
Non ti funziona?

**Comment by KyrosWeb** [comment]
Ciao,

No in realtà non mi funziona infatti non trovo  Streaming Community nemmeno con nuove ricerche.

**Comment by mac12m99** [comment]
In che senso non lo trovi? Se vai in canali -> film -> streamingcommunity?

**Comment by KyrosWeb** [comment]
Scusa l'attesa. 
Si, vedo Streaming community ma ho questo messaggio di errore 

" ... The web Page of the channel has changed its structure ..."

**Comment by mac12m99** [comment]
Ok ho provato su stabile e in effetti è vero, anche se c'è il redirect pare non funzioni. Ho aggiornato tutti i domini.
Grazie della segnalazione!

**Comment by KyrosWeb** [comment]
Grazie a voi
