### ISSUE TITLE
Kod ha smesso di "fetchare" da cb01

### ISSUE THREAD

**Issue by omgfrost** [Stream4me/addon#323]
Come appena segnalato su TG, riporto:
@ragazzi kod non aggiorna piu' da cb01 (,miami) ora..sono usciti degli ultimi episodi ma non appare nella ricerca

si può fare una segnalazione?

bisognerebbe dare sempre priorità a cb01 dato che è veramente il primo ad avere le ultime esclusive

hmm ok forse è normale il loro https://stayonline.pro/ è down al momento....si ma...zzzzzzzzzzzzz :D

@mac12m99 scusa stayonline.pro è tornato up ma kod ancora non fetcha da cb01 e ho soltanto li i links

ultimi interessati sono: fear street 1666 e tv show temple 1x3 , 1x4

sono andato a vedere se per forze superiori avesse messo il pallino alla serie ma no, c'era solo il check degli episodi visti ma è normale, ha sempre aggiornato anche con quello

**Comment by omgfrost** [comment]
![x1SVwzG 1](https://user-images.githubusercontent.com/14861120/125984309-0b34c43d-41f5-4725-9080-99caf65f2412.png)
hmm da pc funziona, però ho fatto la ricerca daccapo perchè non era memorizzato in libreria.
Ora provo a rifare la ricerca dal cell anche se è già memorizzato il libreria..

**Comment by omgfrost** [comment]
Allora, ho rifatto la ricerca e le puntate ci sono (in ricerca!) ma sta volta e non so il motivo, la libreria non le sta aggiungendo (prima volta che succede) cosi ora invece di aggiungerle subito e farmi gli affaracci miei andando a vedere le puntate,,abilito il log, richiudo kodi cosi il log registra la libreria che non aggiorna e poi vado a fetchare gli episodi nuovi dalla ricerca e aggiungo pure il db.sqlite! 😩

**Comment by omgfrost** [comment]
[Galaxy6kodi.log](https://github.com/kodiondemand/addon/files/6832481/Galaxy6kodi.log)
[Galaxy6db.sqlite](https://anonfiles.com/zfp8W86buf/Galaxy6db_sqlite)

**Comment by omgfrost** [comment]
any newzzzz?

**Comment by mac12m99** [comment]
Ciao,
il logging di debug non è attivo, per favore abilitalo dalle impostazioni dell'addon
https://telegra.ph/LOG-11-20

Comunque potrebbe essere che tu abbia modificato le impostazioni affinchè non scansioni sempre, prova a controllare
![Screenshot_12](https://user-images.githubusercontent.com/10120390/126066009-b828f0a6-d7d3-4ce2-9162-1e8c216796ed.png)

Magari, prova anche a forzare l'aggiornamento dal menu contestuale.

**Comment by omgfrost** [comment]
![Screenshot_20210718-142102706](https://user-images.githubusercontent.com/14861120/126066817-f1414a99-ef0c-4e54-80bb-4299f4a3e73a.jpg)
La videoteca\libreria è sempre stata così sin dal primo 19.
Per quanto riguarda il log io l'ho attivato manualmente da system > logging, poi ho richiuso e riaperto per far loggare la scansione dell'update.
Ora gli episodi li ho tutti avendo però dovuto fare la ricerca di nuovo...
Ma una cosa, attivarlo da system e attivarlo da help non è la stessa cosa?
Che faccio lo invio uguale ora che gli ep ci sono?
Attendo procedura!

**Comment by mac12m99** [comment]
Hai abilitato il logging di kodi ma non dell'addon, per abilitare quello dell'addon devi andare in: KOD-Impostazioni-Preferenze-Generale-Abilita Logging di Debug

Hai ri-aggiunto la serie quindi? Se si erano corrotti dei file ora hai sicuramente risolto.. comunque per vedere se l'aggiornamento funziona potresti andare in
/.kodi/userdata/addon_data/plugin.video.kod/videolibrary/Serie TV/Temple [tt7736572]/
E cancellare tutti i file 1x04, se all'avvio di kodi vengono ricreati l'aggiornamento funziona.
Ho provato anch'io e senza funzionare.

**Comment by omgfrost** [comment]
> Hai abilitato il logging di kodi ma non dell'addon, per abilitare quello dell'addon devi andare in: KOD-Impostazioni-Preferenze-Generale-Abilita Logging di Debug
> 
> Hai ri-aggiunto la serie quindi? Se si erano corrotti dei file ora hai sicuramente risolto.. comunque per vedere se l'aggiornamento funziona potresti andare in
> /.kodi/userdata/addon_data/plugin.video.kod/videolibrary/Serie TV/Temple [tt7736572]/
> E cancellare tutti i file 1x04, se all'avvio di kodi vengono ricreati l'aggiornamento funziona.
> Ho provato anch'io e senza funzionare.

Guarda ti giuro sul creatore che in tg mi era stato detto di prenderlo da temp kodi.log perchè era lo stesso,infatti io ho avuto i miei dubbi..
La prox volta faccio da li.
In che senso hai aggiunto e senza funzionare?
Insomma io ti servo ancora per qualcosa o lascio così o deleto la serie,abilito log e la riaddo?
O siccome mi è un pó scomodo ora, ,magari chiudiamo qui e al prossimo agg ep può anche essere in giornata, segnalo di nuovo,se dovrebbe riaccadere?

**Comment by mac12m99** [comment]
Abilita Logging di Debug fa si che inizi a registrare su kodi.log tutto ciò che accade, poi per mandarcelo puoi farlo a mano copiandolo, usando la sezione aiuto, con altri addon ecc..
Ti chiedevo se per farle apparire avevi aggiunto nuovamente la serie, comunque direi che conviene aspettare e vedere se ti capita di nuovo.
Intanto chiudo, se vedi che lo fa ancora riapri pure.

**Comment by omgfrost** [comment]
> Abilita Logging di Debug fa si che inizi a registrare su kodi.log tutto ciò che accade, poi per mandarcelo puoi farlo a mano copiandolo, usando la sezione aiuto, con altri addon ecc..
> Ti chiedevo se per farle apparire avevi aggiunto nuovamente la serie, comunque direi che conviene aspettare e vedere se ti capita di nuovo.
> Intanto chiudo, se vedi che lo fa ancora riapri pure.

Va bene, la prossima volta che non aggiorna la libreria nonostante abbia già il canale coi server memorizzati abilito direttamente da `KOD-Impostazioni-Preferenze-Generale-Abilita Logging di Debug`
tanto ormai gli episodi sono aggiunti e quindi ciccia.
Bè potrei fare che rimuovo completamente la serie, ne aggiungo 1 in ricerca e poi vedo se la libreria aggiorna anche i restanti..
Boh vabbè questa l'ho buttata lì, se ho tempo di farlo faccio instant senò alla prossima volta che accade.
Grazie, saluti.

**Comment by omgfrost** [comment]
Ok ho abilitato il log da kod,riavviato e fatto anche scan new content su "la storia di lisey
L'ultimo ep non l'ha preso
[kodi.log](https://github.com/kodiondemand/addon/files/6836882/kodi.log)
https://fileleaks.com/nE2MAOphXX/db.sqlite

**Comment by omgfrost** [comment]
Aggiornato da ricerca:
![Screenshot_20210718-223900533](https://user-images.githubusercontent.com/14861120/126081502-c26a5c08-1390-42e0-bfe2-a022af87805e.jpg)
Log aggiornato:
[kodi.log](https://github.com/kodiondemand/addon/files/6836918/kodi.log)

**Comment by mac12m99** [comment]
E' passsato un po' di tempo, riscontri ancora lo stesso problema?

**Comment by omgfrost** [comment]
Non mi ricordo neanche più. Chiudi pure
