### ISSUE TITLE
toonitalia.co  si vede soltanto il primo episodio di ogni stagione ma non gli altri solo il primo

### ISSUE THREAD

**Issue by filippo0000** [Stream4me/addon#327]
Nome canale: toonitalia.co
Problema:
si vede soltanto il primo episodio di ogni stagione ma non gli altri solo il primo

**Comment by mac12m99** [comment]
Ora dovrebbe essere ok, grazie della segnalazione.
(Crea una sola issue, non serve a nulla farne di più)
