### ISSUE TITLE
Download si blocca

### ISSUE THREAD

**Issue by brn5ck** [Stream4me/addon#33]
Il download con kodi on demand si blocca dopo circa 20-40 MB; nel frattempo il popup rimane aperto come se stesse continuando a scaricare, con la velocità riportata che lentamente scende a 0.
Il problema mi si presenta solo con kodi 18 su android, usando la stessa versione di kodi su altri sistemi operativi o la versione 17.6 sullo stesso dispositivo funziona normalmente.

Di seguito una prova che ho fatto:
-sistema android 8.1
-kodi 18.2
-addon 0.2
-trailer su youtube di la notte dei morti viventi del 68, link preso da italia-film (dimensione file <7mb)

In questo caso scelto apposta per avere un file più piccolo di 20mb, il download arriva al 100% in pochi secondi poi la velocità scende sempre più lentamente verso 0, senza riuscire a salvarlo.

[Capture+_2019-05-16-19-21-19](https://user-images.githubusercontent.com/50713358/57880077-2795ee00-781e-11e9-9d41-bc2bfab0c64b.png)

In allegato i log di kodi e il file favourites.xml con link al video usato per chi volesse fare delle prove con lo stesso file
[kodi.log](https://github.com/kodiondemand/addon/files/3188623/kodi.log)
[favourites.xml.txt](https://github.com/kodiondemand/addon/files/3188627/favourites.xml.txt)

**Comment by mac12m99** [comment]
Grazie del report dettagliato!
Pare accadere solo su android, lascio comunque la parte del log interessata:

Exception in thread File Writer:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/core/downloader.py", line 414, in __save_file__
                                                self.file.seek(self._download_info["parts"][save_id]["start"])
                                            IOError: [Errno 22] Invalid argument

Vedremo di sistemare, anche se adesso non è nelle nostre priorità.

**Comment by cttynul** [comment]
Come sostenuto da @mac12m99 si tratta di un known bug di Kodi 18.x solo su Android. 
Per un tuo personale fix ti lascio come riferimento questi link: 
- https://theminixforum.com/index.php?threads/help-with-kodi-permissions-to-allow-it-to-write-on-the-external-sd-card.350/
- https://forum.kodi.tv/showthread.php?tid=332669

**Comment by brn5ck** [comment]
Non so dire con quale update si sia risolto perché era da parecchio che non riprovavo, ma ho fatto alcuni test con stesso dispositivo, stessa versione android, stessa versione di kodi e addon aggiornato al commit bdac265 e il download ha funzionato senza problemi

**Comment by mac12m99** [comment]
Lo hai fatto sulla scheda sd esterna?
Sicuro di avere ancora kodi 18.2? Se si ti conviene aggiornarlo..

**Comment by brn5ck** [comment]
L'ho fatto sulla memoria interna, stesso percorso di quando ho aperto l'issue
Ho reinstallato la 18.2 solo per ricreare le stesse esatte condizioni iniziali in modo da essere certo che il problema sia stato risolto da un update dell' addon e non di kodi, ma non è la versione che uso abitualmente
