### ISSUE TITLE
Problema Altadefinizione.click e aggiungi alla videoteca

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#336]
Quando si prova ad aggiungere un film alla videoteca da Altadefinizione.click con autoplay attivo dal menu contestuale il film parte automaticamente al posto di essere aggiunto solo alla videoteca.

![screenshot00000](https://user-images.githubusercontent.com/53865707/130328991-18b46c1b-2eed-49ea-a8b0-d3ac459f2ca9.png)
![screenshot00001](https://user-images.githubusercontent.com/53865707/130328992-04d77a25-446b-4d05-bb9b-f4e1f673cad8.png)
![screenshot00003](https://user-images.githubusercontent.com/53865707/130328993-f7aba004-72ad-4987-a245-2f6e3ec7d73e.png)

**Comment by mac12m99** [comment]
Ciao,
grazie della segnalazione, ora dovrebbe essere risolto, se così non fosse, riapri questo issue.
