### ISSUE TITLE
Altadefinizione Community non vede e trova alcune serie tv

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#340]
@mac12m99 Su Altadefinizione Community alcune serie tv non vengono viste nella sezione serie tv e trovate dal cerca, le serie in questione sono tutte quelle in cui è presente il bollino Nuovi episodi, grazie anticipatamente.

![Cattura](https://user-images.githubusercontent.com/53865707/132430276-8f5e6073-96b2-491b-9e0a-7845dda49e0a.JPG)

![Immagine](https://user-images.githubusercontent.com/53865707/132430117-332ab4e1-21ab-4041-810e-cd1b62d08f84.png)

![screenshot00000](https://user-images.githubusercontent.com/53865707/132430146-210df1e8-8e6c-4e17-929f-d89e93595565.png)

**Comment by mac12m99** [comment]
Problema risolto, grazie della segnalazione.

**Comment by xXTimmy89Xx** [comment]
@mac12m99 Il problema sembra essere stato risolto per la maggior parte delle serie ma ci sono ancora alcune serie devo il problema sembra persistere, alcune delle serie in questioni sono le seguenti: Al Nuovo Gusto Di Ciliegia, Hip Hop - Uncovered, Katla.
