### ISSUE TITLE
Non funziona "Salva link"

### ISSUE THREAD

**Issue by Gythion** [Stream4me/addon#341]
https://anonfiles.com/1e6802G2ub

**Comment by mac12m99** [comment]
Che cosa succede quando lo usi? Su che cosa lo stai usando? Da che sezione?
Sii un po più preciso

Comunque dal log vedo che hai aperto la ricerca globale, ma non mi risulta che ti abbia provato a salvare un link, forse nemmeno è stata chiamata quella funzione, pertanto gli step per riprodurlo sono fondamentali.

**Comment by Gythion** [comment]
Vado su "Ricerca globale", "Serie tv". Quando trovo ciò che m'interessa,
provo a salvare il link, ma non succede niente. Problema riscontrato sia su
Windows che Android.

Il giorno mer 8 set 2021 alle ore 17:50 mac12m99 ***@***.***>
ha scritto:

**Comment by mac12m99** [comment]
Ho provato a salvare un risultato della ricerca e funziona...
Con "non succede niente" intendi che non ti esce la finestra che ti chiede in che cartella salvarlo?

**Comment by Gythion** [comment]
Sì

Il Gio 9 Set 2021, 17:53 mac12m99 ***@***.***> ha scritto:

**Comment by mac12m99** [comment]
Non riuscendo a riprodurre non posso che chiederti di riprovare, registrando il log durante tutto il processo (vai in aiuto -> segnala un problema e segui passo passo, magari prova più volte da più risultati)
