### ISSUE TITLE
Bug AnimeWorld

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#37]
Salve, nell'ultima release, l'archivio .zip preso da qui, non compaiono più gli ultimi episodi degli anime ma gli anime in ordine alfabetico.

**Comment by 4l3x87** [comment]
Dovrebbe esser stato risolto dopo il merge della pull #36

**Comment by hypno99** [comment]
Non é stato risolto, il bug in questione si riferisce ad AnimeWorld non AnimeSaturn.

**Comment by 4l3x87** [comment]
Si scusa, era tardi ed ero particolarmente fuso, siccome c'era lo stesso problema su anime saturn ho dato per scontato fosse quel canale. Ciao

**Comment by 4l3x87** [comment]
Ok ora dovrebbe funzionare!!

**Comment by hypno99** [comment]
Grazie mille, funziona perfettamente.
