### ISSUE TITLE
Cinemalibero e wstream non funzionano

### ISSUE THREAD

**Issue by mattitotti** [Stream4me/addon#45]
Ragazzi nel mio Kodi on demand non funzionano cinemalibero (non ci sono i link dei video praticamente non ci sono elementi da mostrare) e wstream non funziona...per favore potete controllare e risolvere?

**Comment by greko17** [comment]
- Cambio host e aggiunta la possibilità di cambiarlo in auto
-  Fixato wstream

**Comment by greko17** [comment]
> Ragazzi nel mio Kodi on demand non funzionano cinemalibero (non ci sono i link dei video praticamente non ci sono elementi da mostrare) e wstream non funziona...per favore potete controllare e risolvere?

Per **wstream** prova a modificare i DNS.
Cerca sui motori di ricerca i DNS alternativi e come inserirli nel tuo dispositivo.

**Comment by cttynul** [comment]
Dovrebbe essere risolto, chiudo?
