### ISSUE TITLE
Speedvideo non funziona 

### ISSUE THREAD

**Issue by Joshuathree** [Stream4me/addon#46]
Speedvideo versione HD/SD non funziona su nessun canale da diversi giorni ormai

Vi chiedo di  risolvere il problema

Grazie del lavoro che fate

**Comment by greko17** [comment]
Ho inserito dei fix per il server speedvideo nella pull 

[https://github.com/kodiondemand/addon/pull/47](url)

Se poteste provarla e confermare che va...

grazie!

**Comment by cttynul** [comment]
Il fix sarà rilasciato nella prossima release, se testi lo zip da GitHub dovrebbe funzionare senza alcun problema
