### ISSUE TITLE
Ricerche separate per sezione Film/SerieTV e sezione XXX. Stessi termini nella "Ricerca Globale" ?

### ISSUE THREAD

**Issue by DjDiabolik** [Stream4me/addon#51]
Ebbene si........ in pratica se si fa ricerca all'interno dei canali della sezione XXX i termini cercati finiscono nello stesso storico della "Ricerca Globale" per i film e serie tv.
Sapete quando uno dice "Elimina Cronologia" :)

**Comment by cttynul** [comment]
Succede questo, perché una ricerca sul canale XXX equivale ad una ricerca su un qualsiasi altro canale, data l'omologazione del codice di tutti i canali, è una feature aggiuntiva molto marginale ed opzionale, ma che, eventualmente, verrà presa in considerazione, grazie per il suggerimento!

**Comment by DjDiabolik** [comment]
Esattamente :) Poco dopo ci sono arrivato anche io... cioè se ho capito bene ad ora la combinazione dei file  json/py di un sito XXX ora come ora viene esattamente trattato come un file di un sito di film giusto ?
Nei file .json poi c'è la categoria...... questo appunto spiega perchè la ricerca di fatto sia una sola. Dico bene ?

Cioè per assurdo ciò che ho chiesto dovrebbe essere una feature aggiunta direttamente dal team di sviluppo di "Alfa"... giusto ?
