### ISSUE TITLE
fix real-debrid authorization

### ISSUE THREAD

**Issue by SiNaPsEr0x** [Stream4me/addon#52]
è possibile correggere la parte per l'autorizzazione del debrid? con la 0.3.1 il menu adesso funziona ma non chiede l'autorizzazione per real-debrid

**Comment by SiNaPsEr0x** [comment]
fixato personalmente! ti invio un push in caso... comunque nella cartella addon_Data e setting_servers il file realdebrid_data.json non viene sovrascritto con true quando nelle impostazioni lo si setta

**Comment by cttynul** [comment]
Risolto nella nightly, in attesa del rilascio della nuova versione stabile.

**Comment by giuseppevalenti** [comment]
Non ho capito se l'autorizzazione dovrebbe esser stata fixata, a me quando attivo l'opzione per Real Debrid Premium continua a non chiedere l'auth.

Vi risulta?

**Comment by cttynul** [comment]
Il pair, previa supporto del link, viene richiesta al primo avvio di uno di questi.

**Comment by giuseppevalenti** [comment]
Ho abilitato l'opzione Account Premium di Real Debrid nelle impostazioni server, e provato ad avviare due link supportati:
- Link Openload: non chiede l'auth (lo streaming funziona ma senza "passare" da RD
- Link Rapidgator: lo streaming non parte, viene visualizzato l'alert che dice che è necessario un account di RD o All Debrid

Dove sbaglio?

**Comment by giuseppevalenti** [comment]
Perdonate il bump, nessuno?

**Comment by mac12m99** [comment]
Ciao,
scusa per il ritardo, il fix di @SiNaPsEr0x suppongo sia stato questo:
nel file .kodi/userdata/addon_data/plugin.video.kod/settings_servers/realdebrid_data.json
modifica:
"premium": false
in:
"premium": true

Sembra che la finestra delle impostazioni non lo cambi (vedrò di risolvere appena avrò tempo), comunque nessuno di noi possiede un account, quindi non so dirti se realmente funziona.
Il codice non è altro che quello di alfa (il fix di cui parlava @cttynul è relativo a dei cambiamenti che abbiamo fatto che l'avevano reso inutilizzabile).
 
Per attivare i debrider anche per link che normalmente non lo necessitano (openload ad esempio) recati in impostazioni -> generale e in priorità e setta "debriders prima".

Fammi sapere se funziona!
