### ISSUE TITLE
Ma non si era detto che non si copiava da altri?

### ISSUE THREAD

**Issue by H2RIS** [Stream4me/addon#53]
ragazzi ma cosi sminuite tutto il lavoro fatto. netlovers,py e copiato papale papale da SOD pureita poi se pensate che  una piccolissima rivisita per non farla apparire un copia-incolla vi esonera...........
Mi sono permesso questa osservazione perche state facendo un ottimo lavoro e sarebbe un peccato perdere  credibilita e il lavoro fatto per motivi del genere o per qualcuno che si e portato queste abitudini da altri addon.
Buon Lavoro

**Comment by cttynul** [comment]
Il canale, che probabilmente non sarà incluso in nessuna release, o meglio, la regex, è stata scritta (e anche male, non becca, palesemente, tutti i risultati) di mio pugno (il resto della sintassi è la sintassi classica di qualsiasi canale che giri su core Pelis), i menù altro non sono che gli stessi menù del sito di Netflix Lovers, guardar per credere.
Accusare qualcuno di copiare quando, il canale "ora in TV", scritto da un collaboratore come un altro, adattato da Icarus è stato riscritto, facendo scraping addirittura su un sito web differente, proprio per evitare di cadere in eventuali accuse di "copia".

Accetto che possa essere additata come "copia" l'idea dell'inserirlo come canale, ma non il codice del canale in sé, anche perché questo è scritto prendendo filmontv, facendo un copia e incolla aggressivo e cambiando indirizzi e regex, puoi facilmente notarlo dalle informazioni dei log che non son state cambiate proprio alla luce dello stato non pubblico ed embrionale del lavoro. 
Personalmente ritengo spiacevole il fatto che si possa perdere di "credibilità" per una cosa del genere, o addirittura, che possa vanificare tutto il buon lavoro svolto finora da una community che non ha alcun secondo fine. 

PS. Non ho il codice del canale perché lo sviluppatore ha ben deciso di rimuoverlo dal sito, in caso lo postassi qui mi faresti un favore, giusto per notare queste similitudini, mera curiosità, nient'altro.

**Comment by H2RIS** [comment]
Non ti offendere personalmente ammiro il lavoro che svolgete  e lungi da me accusare ma il canale netlovers sembra davvero copiato  il regex sembra scritto in modo appunto da nascondere l'originale.  Quando mi viene fatto notare in Forum, telegram ecc e mi viene mostrato il file originale confrontando i 2 sembra davvero una brutta copia. Questo mi dispiace perche e un bel progetto e quindi mi sono sentito in dovere di comunicarlo

**Comment by cttynul** [comment]
Non la prendo assolutamente come un'offesa, anzi, i consigli sono ben apprezzati negativi o positivi che siano, alla luce di ciò onde evitare spiacevoli disguidi o incomprensioni ho deciso di mia iniziativa che il canale sarà rimosso e mai reso pubblico su nessuna delle releases pubbliche, ci tengo a ribadire il fatto che ciò non sia mai stato fatto, visto che questo repo viene utilizzato per lo sviluppo è normale trovarci di tutto.

La regex non è "mascherata" per nascondere quella "originale" bensì è scritta alla bene e meglio giusto per test, non a caso scrapa metà dei contenuti presenti.

PS. Per quanto ci sia possibile cerchiamo di "riscrivere" il più possibile di codice non sia farina del nostro sacco e, quando ciò non viene fatto vengono lasciati i debiti ringraziamenti, nel pieno rispetto della licenza GNU GPL v3, su cui è stato rilasciato Pelisalacarta e tutte le sue opere derivate, SOD, PureITA, Alfa o Icarus che sia.
