### ISSUE TITLE
Errore inaspettato sul canale serietvsubita

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#54]
Come da titolo appare non appena tenti di accedere alla sezione Novità del suddetto canale.

**Comment by mac12m99** [comment]
Il problema è causato dalla serie "cobra kai", la quale è stata messa come novità come stagione intera (purché il loro solito sia mettere episodio per episodio).
Per il momento ci ho messo una pezza (che lo elimina dai risultati), spero non sia un problema (in futuro vedremo di gestire anche questi casi... purtroppo quel sito non è molto "standard").

Riceverai il fix nella prossima versione.

**Comment by hypno99** [comment]
ok grazie.
