### ISSUE TITLE
traspottare la videoteca su piu dispositivi 

### ISSUE THREAD

**Issue by alex-military** [Stream4me/addon#59]
salve team di KoD il lavoro che avete svolto e eccezionale ma vorrei sapere se esiste un modo per sincronizzare la videoteca su piu dispositivi dato che in molto abbiano magari un box multimediale con kodi un pc e uno smartphone magari tornerebbe molto utile poter sincronizzare la videoteca con tutti i dispositivi.

**Comment by cttynul** [comment]
Le informazioni della videoteca di KOD sono salvate all'interno della cartella userdata/addon_data/plugin.video.kod puoi copiare e incollare quella cartella su tutti i tuoi dispotivi o, in alternativa, se preferisci una soluzione più naive dai un'occhiata a [Emby Server](https://emby.media/)
