### ISSUE TITLE
Errore inaspettato sul canale mondoserietv

### ISSUE THREAD

**Issue by spidermax7** [Stream4me/addon#6]
Buongiorno, sono Massimo, ho installato KOD ieri per la prima volta, stavo dando un’occhiata ai numerosi contenuti disponibili sul canale mondoserietv e mi sono imbattuto in un errore inaspettato. Credo che la pagina web del canale (mondoserietv) abbia cambiato la sua struttura 

XIAOMI MI BOX

Sistema operativo: Android 8.1.0. API level 27 (kernel: Linus 4.9.61)

Versione: Kodi 18.2

Skin: A Confluence ZEITGEIST (Beta)(KODI 18)

**Comment by cttynul** [comment]
Grazie della segnalazione e per la verbosity della stessa, provvederemo a risolvere!

**Comment by 4l3x87** [comment]
Ho testato il canale sembra funzionare tutto correttamente, sei sicuro che non è un problema di DNS?

**Comment by mac12m99** [comment]
Ho provato anch'io e sembra funzionare tutto, potresti indicare di preciso che operazioni hai effettuato e cosa hai cercato?
Assicurati inoltre di aver impostato i DNS "liberi" (come indicato anche da 4l3x87), e magari prova ad eseguire la stessa operazione da browser.
