### ISSUE TITLE
Problema vari canali

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#60]
Salve, stavo notando che la sezione **Aggiornamenti serie tv di cb01 risolto**, ora faro un check per vedere dove mancano e vi aggiorno.
Edit: ci sono anche molti canali che danno errore o non sono aggiornati/inattivi si potrebbero togliere.

Filmi Gratis (pagina successiva); **Film per Tutti risolto**; GuardSerie.click (pagina successiva); GuardoGratis non è funzionante; **Italia Serie risolto**; MondoLunatico 2.0 (pagina successiva); Pirate streaming non è aggiornato; SerieTvSubITA (pagina successiva); SerieHD (pagina successiva); SerieTVU (pagina successiva), Questi solo della sezione Serie TV, poi metto le altre.

Sezione Film: **CasaCinema risolto** Italia-Film.co nella sezione Film escono le serie tv; **Guardare film risolto**; **ItaliaFilm HD risolto**.

Sezione Anime: AnimeForce manca la possibilità di scorrere le pagine; **AnimeSubIta risolto** Bleach Portal si pò anche togliere, gli episodi iniziano dall'episodio 52; DreamSub manca la pagina successiva e ci sono dei numeri davanti agli episodi nella sezione Ultimi Episodi.

**Comment by phede86** [comment]
Anche Filmi Gratis; Film per Tutti non è funzionante; GuardSerie.click; GuardoGratis non è funzionante; Italia serie non funzionante; MondoLunatico; Pirate streaming non è aggiornato; SerieTvSubITA; SerieHD; SerieTVU,  Questi solo della sezione Serie TV, poi metto le altre.

**Comment by phede86** [comment]
Sezione Film CasaCinema non funziona; Italia-Film.co nella sezione Film escono le serie tv; Guardare film ci sono film del 2018; ItaliaFilm HD non funziona.

**Comment by phede86** [comment]
Sezione Anime AnimeForce manca la possibilità di scorrere le pagine; AnimeSubIta errore inaspettato; Bleach Portal si pò anche togliere gli episodi iniziano dall'episodio 52; DreamSub manca la pagina successiva e ci sono dei numeri davanti agli episodi nella sezione Ultimi Episodi.

**Comment by greko17** [comment]
Ciao ,

Fatti e funzionali, saranno disponibili prossimamente, i seguente canali da te segnalati:

-Altadefinizione01 C
-AnimeSubIta
-Casacinema
-Cb01
-Cinetecabologna
-Filmpertutti Disattivato!
-Guardarefim
-Istituto Luce
-Italia Serie
-ItaliaFilmHD
-VedoHD

Ciao e grazie per la segnalazione

**Comment by hypno99** [comment]
Aggiorno il post, grazie a voi per quello che fate, mi rendo conto che gestire tutti questi canali non è facile.

**Comment by hypno99** [comment]
C'è un problema e un errata traduzione su animeworld, la voce "in corso" é completamente inutile, mentre ultimi aggiunti si riferisce ai film mentre ultimi episodi alle serie TV, bisognerebbe specificarlo.

**Comment by PiccoloKimico** [comment]
Ciao, sul canale SERIEHD se fai click su "Serie TV" l'addon restiruisce un valore di 25 titoli, non c'è l'opzione "pagina successiva".
Se si fa comunque una ricerca su un titolo che NON compare nei nei 25 l'addon lo trova.

Grazie per quello che fate.

**Comment by PiccoloKimico** [comment]
Okay grazie... ora compare "Successivo"

**Comment by mac12m99** [comment]
Grazie a te per la segnalazione!
