### ISSUE TITLE
Download su NAS di rete con credenziali

### ISSUE THREAD

**Issue by Diabolik2** [Stream4me/addon#67]
Buongiorno, chiedo se è possibile abilitare il download su un NAS di rete che è accessibile solo con utente e password. Attualmente i percorsi non prevedono l'inserimento delle credenziali.
Kodi su fire-stick e addon ultima versione.
Grazie

**Comment by cttynul** [comment]
Provato anche a flaggare tra le impostazioni di Kodi "consenti a Kodi la scrittura dei file su disco"? Purtroppo è known bug che capita solo con Android a causa delle sue politiche stringenti in fatto di permessi.
Credo che tu sia già sul gruppo Telegram in alternativa puoi provare a testare una delle tante soluzioni proposte cercando la keyword "fritz".
