### ISSUE TITLE
Errore addon

### ISSUE THREAD

**Issue by thegreatyellow67** [Stream4me/addon#70]
Salve, l'addon kodi on demand in data odierna ha smesso di funzionare. Faccio notare che ieri funzionava tutto benissimo. Dai log ottengo questo:

2019-08-05 15:21:39.945 T:1452794592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named httplib2
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.kod/default.py", line 27, in <module>
                                                launcher.start()
                                              File "/home/osmc/.kodi/addons/plugin.video.kod/platformcode/launcher.py", line 37, in start
                                                from specials.checkhost import test_conn, check_channels
                                              File "/home/osmc/.kodi/addons/plugin.video.kod/specials/checkhost.py", line 8, in <module>
                                                import httplib2
                                            ImportError: No module named httplib2
                                            -->End of Python script error report<--
2019-08-05 15:21:40.104 T:1652548320   ERROR: GetDirectory - Error getting plugin://plugin.video.kod/
2019-08-05 15:21:40.106 T:1915291184   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/) failed

Da questo link:
https://raw.githubusercontent.com/dannyperry571/theapprentice/master/_repo/script.module.httplib2/script.module.httplib2-0.8.0.zip

ho provato ad installare il modulo httplib2, ma nessun successo.

L'addon è installato su sistema OSMC 2019.06-1 (kernel linux 4.14.78-4-osmc) con versione Kodi 18.3 compilata 2019-06-19.

Posso riparare in qualche modo a questo errore? Grazie.

**Comment by greko17** [comment]
Ciao,
grazie per la segnalazione.
Alla prossima accensione di kodi, o nel caso riavvialo, ti si aggiorna KOD con il fix...

ciao

**Comment by mac12m99** [comment]
Ciao,
noto che hai installato la beta, questo va benissimo per provare nuove funzionalità/fix, ma non è affatto consigliato per l'utilizzo quotidiano.
Questo perchè la beta è il nostro "luogo di sviluppo", che è pubblico, ma ciò che pubblichiamo li dev'essere prima testato per poi andare in stable.
Se utilizzi la beta nel tuo dispositivo per uso quotidiano ti consiglio di reinstallare KoD secondo la guida sul [sito](https://kodiondemand.github.io/) 
PS
hai scaricato lo zip da github o hai usato l'installer? (curiosità, non cambia nulla dato che l'installer non fa altro che scaricare da github)

**Comment by thegreatyellow67** [comment]
Ringrazio greko17 e mac12m99 per la tempestiva risposta. In effetti non mi ero accorto di aver installato la versione beta dell'addon. Venerdì scorso la micro sd del mio raspi 3b+ si è, per qualche motivo inspiegabile, corrotta e non sono stato più in grado di ripristinare il vecchio setup (non mi ero fatto una copia di backup della microsd!!), quindi ho dovuto reinstallare tutto e probabilmente, essendo piuttosto arrabbiato per dover spendere un paio d'ore a riconfigurare osmc e tutti gli addons, nella fretta ho installato la ver beta in formato zip da questo repo github e installato quindi dal file zip (per rispondere alla domanda di mac12m99). Comunque, per il momento lascio la beta, anche per testare il fix che voi farete e darvi così un feedback positivo. Ottimo addon, grazie per il vostro eccellente lavoro, non ne potrei più fare a meno! E poi, una volta ogni tanto, un repo github dove si può scrivere in italiano, uso moltissimo linux e spesso devo stare lì a spiegare le cose che non vanno in inglese, una fatica!

**Comment by mac12m99** [comment]
DI nulla :)
Eventualmente, saresti disposto a farci da beta tester?

**Comment by thegreatyellow67** [comment]
Attualmente ho installata la versione beta, se posso essere di aiuto volentieri. In cosa consiste? E' sufficiente avere installata la versione beta e segnalarvi qua eventuali errori?

Tra l'altro, curiosità: avendo ieri sera ripristinato la versione stable dal repo "kod repo", stamattina ho voluto reinstallare la versione beta. Ho prima disinstallato la versione stable, poi sempre dal repo utilizzando il file zip KoD-installer-BETA.zip per installare la ver BETA, ma mi ritrovo sempre la versione stable (senza dicitura BETA). Se invece installo dal file master.zip scaricato da questa pagina github, allora mi ritrovo la versione beta. Cosa sbaglio?

Comunque al momento la versione BETA funziona regolarmente.

**Comment by mac12m99** [comment]
In sostanza a volte necessitiamo di persone che testino le ultime modifiche o provino a fare alcuni test specifici (o semplicemente renderci a conoscenza di alcuni problemi come hai appena fatto tu :+1:  ).
Al momento "sfruttiamo" gli admin del gruppo telegram, ma una mano in più è sempre ben accetta quando serve.

Per quanto riguarda KoD-installer-BETA è dovuto al fatto che kodi non aggiorna le info degli addon finchè non riavvii, in pratica avevi la beta ma non risultava la dicitura nel nome dell'addon.
Comunque ora ho fixato, se riprovi vedrai che la scritta BETA appare :)
