### ISSUE TITLE
Adesso in Onda

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#74]
Adesso in onda non funziona correttamente, il problema è dovuto dal sito che viene usato per recuperare le informazioni https://www.superguidatv.it/, le informazioni non sono per nulla attendibili o sono risalenti a giorni precedenti, consiglierei l'utilizzo di un sito più affidabile come https://www.comingsoon.it/tv/oggi/in-onda/ o altri ,in più consiglierei di tenere solo 3 opzioni al posto delle 10 attuali, suddivise in Tutta la programmazione, Film, Serie TV, e ripristinare se possibile la vecchia distinzione per fascia oraria tipo Mattina, Pomeriggio, Sera, Notte, In Onda molto più intuitiva, grazie mille per il lavoro svolto. 
![Esempio](https://user-images.githubusercontent.com/53865707/62844063-dda69200-bcbe-11e9-94dc-d023454f8e90.jpg)
Attualmente sono le ore 05:00 a sinistra quello che dichiara https://www.superguidatv.it/ora-in-onda/ e a destra quello che è realmente in onda prendendo come esempio Italia 1.

**Comment by cttynul** [comment]
È il 12 di agosto, è possibile che i gestori del sito web stiano avendo problemi e che diversi sviluppatori siamo in ferie e, magari, non abbiano fixato la fonte che fornisce informazioni non corrette.
Superguidatv è l'unico sito web che fornisce più informazioni per ogni evento (distinzione tra film in onda nella giornata per emittenti, programmazione in onda nel momento in cui si accede alla sezione e via dicendo), informazioni presenti anche su Comingsoon.it, ma non in maniera esaustiva (leggesi locandine mancanti).

Il sito verrà sostituito solo se continuerà a fornire informazioni errate con l'inizio della nuova stagione televisiva, la programmazione dei film quotidiana (unica funzione presente nella vecchia Guidatv) mi risulta fornisca informazioni ancora attendibili.

**Comment by cttynul** [comment]
Il sito web è stato fixato ed ora fornisce le informazioni corrette.
