### ISSUE TITLE
IMDB

### ISSUE THREAD

**Issue by wnocella** [Stream4me/addon#82]
Ciao

Volevo sapere se potete correggere questi bug:

1) Nella ricerca alternativa tramite IMDB qualunque cosa uso si ferma alla prima pagina di risultati...se vedo alla pagina successiva dice che non ci sono risultati mentre sul sito di IMDB ce ne sono.

2) Ho impostato IMDB come motore di ricerca di default per lo universal scraper però quando vado sui siti non ci sono i voti oppure i voti sono diversi.

**Comment by Alhaziel01** [comment]
> 
> 
> Ciao
> 
> Volevo sapere se potete correggere questi bug:
> 
>     1. Nella ricerca alternativa tramite IMDB qualunque cosa uso si ferma alla prima pagina di risultati...se vedo alla pagina successiva dice che non ci sono risultati mentre sul sito di IMDB ce ne sono.
> 
>     2. Ho impostato IMDB come motore di ricerca di default per lo universal scraper però quando vado sui siti non ci sono i voti oppure i voti sono diversi.

Ciao wnocella,

il punto **1 è stato corretto**, per quanto riguarda il punto due, **IMDB come scraper di Kodi ha effetto solo sulla libreria di Kodi,** Kod si basa su TMDB e prende i voti dal sito se esistono.
