### ISSUE TITLE
Chiarezza del menù Animeworld

### ISSUE THREAD

**Issue by hypno99** [Stream4me/addon#85]
Salve, nel menù sono presenti tre voci non chiare, la voce "In corso" manca il soggetto ed é un doppione della voce "Ultimi Episodi", anche qui comunque manca il soggetto e anche nella voce "Ultimi aggiunti", mele o pere?

**Comment by Alhaziel01** [comment]
Penso banane...

**Comment by cttynul** [comment]
Alla luce del nome del sito web: *ANIME*world, credo che il soggetto sia anche abbastanza chiaro.

**Comment by hypno99** [comment]
Basta mettere Ultimi film/movie aggiunti, ultimi episodi, va anche bene perché si capisce che sono episodi di una serie, mentre In corso é un doppione di Ultimi Episodi.

**Comment by cttynul** [comment]
All'interno della sezione "Nuove Aggiunte" sono presenti sia Anime che OAV/Film, sarebbe fuorviante precisare l'oggetto.
Il menu è scritto sulla base del sito web a cui fa riferimento, come tutti gli altri canali scritti per l'addon.

"In corso" e "Ultimi Episodi" fanno riferimento a due diverse pagine del sito web, KOD è un browser e presenta i contenuti proprio allo stesso modo di come faccia il sito web; eventuali doppioni sono imputabili ai gestori del sito web. 
In caso non ti piacesse la nomenclatura potresti modificarla da te andando ad editare il file ./channels/animeworld.py
