### ISSUE TITLE
Problemi con la Videoteca e cartelle di rete

### ISSUE THREAD

**Issue by Danieleeee** [Stream4me/addon#94]
Se imposto una cartella di rete come percorso della videoteca di KOD vengono dati errori.
La cartella di rete è stata duplicata da quella locale (videolibrary) di un PC linux, messa su un HD di Rete, per poi poter essere visualizzata su Box android.
Inoltre se aggiungo la cartella solo su KODI (file->Aggiungi video..), la cartella ed i file vengono visualizzati, ma cercando di aprire i file, KOD da errore, come se i file fossero riconosciuti per KOD. In effetti sono quelli che popolano la videoteca del KOD che ho sul PC.

Grazie della disponibilità,
Buon lavoro.

**Comment by mac12m99** [comment]
Buongiorno,
il percorso di rete della videoteca necessita di essere un indirizzo ad un'altra istanza di kodi, ad esempio se hai 2 box android puoi impostarne uno come "server" e configurare il secondo così:
Nome server: ip primo box
Porta: 8080
(controlla prima che il webserver sia abilitato e  raggiungibile)
La stessa cosa la puoi fare con un pc con installato kodi, non è la stessa cosa di un HD di rete ma al momento non è possibile fare ciò, quella parte deriva da alfa e non è stata toccata.

Se ci provi, fammi sapere se funziona!

**Comment by Danieleeee** [comment]
Ciao,
impostando come percorso di rete una cartella condivisa dal PC dove ho KODI, funziona.
Sarebbe stato meglio poter usare l'HD di Rete così da non dover lasciare il PC acceso per vedere i film.

Grazie delle informazioni.

**Comment by mac12m99** [comment]
Anche a me farebbe comodo (lo farei direttamente dal modem), ma adesso siamo un po incasinati con la riscrittura di parecchie parti dell'addon..
Lo metto nei TODO :+1:
