### ISSUE TITLE
CB01 su KOD non visualizza alcuni link dei siti di hosting in HD

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#95]
CB01 su KOD non visualizza alcuni link dei siti di hosting in HD , prendiamo come esempio il film Annabelle 3 sul sito https://cb01.productions/annabelle-3-hd-2019/ nella sezione Streamig HD sono presenti i link sui vari host perfettamente funzionanti in qualità HD, se invece effettuo la ricerca su KOD dello stesso film invece vengono trovati solo gli host in SD, il problema mi si era presentato anche con altri film che purtroppo al momento non ricordo.

**Comment by mac12m99** [comment]
Confermo, su alcuni non appare, grazie della segnalazione, vedremo di sistemare :)
Ti aggiorniamo quando fatto

**Comment by mac12m99** [comment]
Il problema deriva dal fatto che hanno sbagliato a scrivere streaming :D, siccome kod cerca "streaming HD", non trova la sezione.
Risolto con 0f3098d1694702dfe2dc8100cd32e55c087fa346, spero solo non ci siano altri errori di digitazione...

Il fix è attualmente solo sulla beta, se ti ricordi qualche altro caso, riesci a testare?

**Comment by xXTimmy89Xx** [comment]
si ho notato solo ora... effettuerò altri test e nel caso comunicherò, grazie
